Kicker Controller: relinker.target_c Class Reference
relinker.target_c Class Reference
Public Member Functions
__init__ (self, lib, lib_path, file, fsecs)
__str__ (self)
Public Attributes
lib = lib
file = file
lib_path = lib_path
fsecs = func2sect(fsecs)
str desc = '*%s:%s.*'%(lib, file.split('.')[0])
secs = filter_secs(secs, ('.iram1.',))
isecs = strip_secs(self.secs, self.fsecs)
Detailed Description
Definition at line 90 of file relinker.py.
Constructor & Destructor Documentation
__init__()
relinker.target_c.__init__ (self, lib, lib_path, file, fsecs)
Definition at line 91 of file relinker.py.
Member Function Documentation
__str__()
relinker.target_c.__str__ (self)
Definition at line 106 of file relinker.py.
References desc, file, fsecs, isecs, lib, lib_path, and secs.
Member Data Documentation
desc
str relinker.target_c.desc = '*%s:%s.*'%(lib, file.split('.')[0])
Definition at line 97 of file relinker.py.
Referenced by __str__().
file
relinker.target_c.file = file
Definition at line 93 of file relinker.py.
Referenced by __str__().
fsecs
relinker.target_c.fsecs = func2sect(fsecs)
Definition at line 96 of file relinker.py.
Referenced by __str__().
isecs
relinker.target_c.isecs = strip_secs(self.secs, self.fsecs)
Definition at line 104 of file relinker.py.
Referenced by __str__().
lib
relinker.target_c.lib = lib
Definition at line 92 of file relinker.py.
Referenced by __str__().
lib_path
relinker.target_c.lib_path = lib_path
Definition at line 95 of file relinker.py.
Referenced by __str__().
secs
relinker.target_c.secs = filter_secs(secs, ('.iram1.',))
Definition at line 101 of file relinker.py.
Referenced by __str__().
The documentation for this class was generated from the following file:
managed_components/espressif__cmake_utilities/scripts/relinker/relinker.py