Kicker Controller: relinker.relink_c Class Reference
relinker.relink_c Class Reference
Public Member Functions
__init__ (self, input, library_file, object_file, function_file, sdkconfig_file, missing_function_info)
__transform__ (self)
__replace__ (self, lines)
save (self, input, output)
Public Attributes
filter = filter_c(input)
targets = list()
str iram1_exclude
str iram1_include = '\n'.join(iram1_include)
str flash_include = '\n'.join(flash_include)
Protected Member Functions
_replace_func (self, l)
Detailed Description
Definition at line 112 of file relinker.py.
Constructor & Destructor Documentation
__init__()
relinker.relink_c.__init__ (self, input, library_file, object_file, function_file, sdkconfig_file, missing_function_info)
Definition at line 113 of file relinker.py.
Member Function Documentation
__replace__()
relinker.relink_c.__replace__ (self, lines)
Definition at line 160 of file relinker.py.
References _replace_func(), flash_include, iram1_exclude, iram1_include, and len.
Referenced by save().
__transform__()
relinker.relink_c.__transform__ (self)
Definition at line 132 of file relinker.py.
References relinker.filter_secs(), len, list, and targets.
_replace_func()
relinker.relink_c._replace_func (self, l) protected
Definition at line 193 of file relinker.py.
References len, and targets.
Referenced by __replace__().
save()
relinker.relink_c.save (self, input, output)
Definition at line 234 of file relinker.py.
References __replace__(), read, and write.
Member Data Documentation
filter
relinker.relink_c.filter = filter_c(input)
Definition at line 114 of file relinker.py.
flash_include
relinker.relink_c.flash_include = '\n'.join(flash_include)
Definition at line 154 of file relinker.py.
Referenced by __replace__().
iram1_exclude
relinker.relink_c.iram1_exclude
Initial value:
=  '    *(EXCLUDE_FILE(%s %s) .iram1.*) *(EXCLUDE_FILE(%s %s) .iram1)' % \
                             (self.filter.add(), ' '.join(iram1_exclude), \
                              self.filter.add(), ' '.join(iram1_exclude))
Definition at line 150 of file relinker.py.
Referenced by __replace__().
iram1_include
relinker.relink_c.iram1_include = '\n'.join(iram1_include)
Definition at line 153 of file relinker.py.
Referenced by __replace__().
targets
relinker.relink_c.targets = list()
Definition at line 117 of file relinker.py.
Referenced by __transform__(), and _replace_func().
The documentation for this class was generated from the following file:
managed_components/espressif__cmake_utilities/scripts/relinker/relinker.py