Kicker Controller: ps4 Class Reference
ps4 Class Reference
This class is for creating a ps4 controller object and handling all tasks related to the ps4 controller.
#include <ps4.h>
Classes
struct app_event_queue_t
APP event queue.
Public Member Functions
ps4 ()
Construct the ps4 object, which creates the required tasks for the usb host, and processing the usb datafv.
Private Types
enum app_event_group_t { APP_EVENT = 0 , APP_EVENT_HID_HOST }
APP event group.
Private Member Functions
void hid_host_device_event (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
USB HID Host Device event.
Static Private Member Functions
static void hid_host_generic_report_callback (const uint8_t *const data, const int length)
USB HID Host Generic Interface report callback handler.
static void hid_host_interface_callback (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void *arg)
USB HID Host interface callback.
static void usb_lib_task (void *arg)
Start USB Host install and handle common USB host library events while app pin not low.
static void hid_host_device_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
HID Host Device callback.
Static Private Attributes
static QueueHandle_t app_event_queue = nullptr
queue used for sending data inbetween the usb callbacks and task
Detailed Description
This class is for creating a ps4 controller object and handling all tasks related to the ps4 controller.
A modified version of the example code from the esp-idf examples, with the addition of ds4 for decoding the ps4 / controller data exported data is sent to a set of queues, hotswaping of controllers is supported https://github.com/espressif/esp-idf/blob/v5.3.2/examples/peripherals/usb/host/hid/main/hid_host_example.c https://www.psdevwiki.com/ps4/DS4-USB
Definition at line 38 of file ps4.h.
Member Enumeration Documentation
app_event_group_t
enum ps4::app_event_group_t private
APP event group.
Application logic can be different. There is a one among other ways to distingiush the event by application event group. In this example we have two event groups: APP_EVENT - General event, which is APP_QUIT_PIN press event (Generally, it is IO0). APP_EVENT_HID_HOST - HID Host Driver event, such as device connection/disconnection or input report.
Enumerator
APP_EVENT
APP_EVENT_HID_HOST
Definition at line 50 of file ps4.h.
Constructor & Destructor Documentation
ps4()
ps4::ps4 ()
Construct the ps4 object, which creates the required tasks for the usb host, and processing the usb datafv.
Definition at line 209 of file ps4.cpp.
References APP_EVENT, APP_EVENT_HID_HOST, app_event_queue, ps4::app_event_queue_t::arg, ps4::app_event_queue_t::event, ps4::app_event_queue_t::event_group, ps4::app_event_queue_t::handle, ps4::app_event_queue_t::hid_host_device, hid_host_device_callback(), hid_host_device_event(), hid_host_drvier_priority, usb_events_priority, usb_events_queue_size, usb_events_stack_size, usb_lib_task(), and usb_lib_task_wait_time.
Member Function Documentation
hid_host_device_callback()
void ps4::hid_host_device_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg) static private
HID Host Device callback.
Puts new HID Device event to the queue
Parameters
[in] hid_device_handle HID Device handle
[in] event HID Device event
[in] arg Not used
Definition at line 191 of file ps4.cpp.
References APP_EVENT_HID_HOST, and app_event_queue.
Referenced by ps4().
hid_host_device_event()
void ps4::hid_host_device_event (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg) private
USB HID Host Device event.
Parameters
[in] hid_device_handle HID Device handle
[in] event HID Host Device event
[in] arg Pointer to arguments, does not used
Definition at line 119 of file ps4.cpp.
References contoller_connected, hid_host_interface_callback(), main_menu_values_mutex, ps4_controller_connected, update_main_display, and update_main_display_mutex.
Referenced by ps4().
hid_host_generic_report_callback()
void ps4::hid_host_generic_report_callback (const uint8_t *const data, const int length) static private
USB HID Host Generic Interface report callback handler.
'generic' means anything else than mouse or keyboard
Parameters
[in] data Pointer to input report data buffer
[in] length Length of input report data buffer
Definition at line 22 of file ps4.cpp.
References controller_byte_2, controller_byte_3, controller_byte_5, controller_byte_6, new_controller_data, values_2, values_3, values_5, and values_6.
Referenced by hid_host_interface_callback().
hid_host_interface_callback()
void ps4::hid_host_interface_callback (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void * arg) static private
USB HID Host interface callback.
Parameters
[in] hid_device_handle HID Device handle
[in] event HID Host interface event
[in] arg Pointer to arguments, does not used
Definition at line 74 of file ps4.cpp.
References contoller_connected, hid_host_generic_report_callback(), main_menu_values_mutex, ps4_controller_connected, update_main_display, update_main_display_mutex, and usb_data_read_size.
Referenced by hid_host_device_event().
usb_lib_task()
void ps4::usb_lib_task (void * arg) static private
Start USB Host install and handle common USB host library events while app pin not low.
Parameters
[in] arg Not used
Definition at line 162 of file ps4.cpp.
References usb_lib_disconnect_wait_time.
Referenced by ps4().
Member Data Documentation
app_event_queue
QueueHandle_t ps4::app_event_queue = nullptr static private
queue used for sending data inbetween the usb callbacks and task
Definition at line 39 of file ps4.h.
Referenced by hid_host_device_callback(), and ps4().
The documentation for this class was generated from the following files:
include/drivers/ps4.h
main/drivers/ps4.cpp