Kicker Controller: configuration.object_c Class Reference
configuration.object_c Class Reference
Public Member Functions
read_dump_info (self, pathes)
get_func_section (self, dumps, func)
__init__ (self, name, pathes, libray)
append (self, func)
functions (self)
sections (self)
Public Attributes
name = name
libray = libray
funcs = dict()
pathes = pathes
dumps = self.read_dump_info(pathes)
Detailed Description
Definition at line 56 of file configuration.py.
Constructor & Destructor Documentation
__init__()
configuration.object_c.__init__ (self, name, pathes, libray)
Definition at line 83 of file configuration.py.
Member Function Documentation
append()
configuration.object_c.append (self, func)
Definition at line 90 of file configuration.py.
References dumps, funcs, and get_func_section().
functions()
configuration.object_c.functions (self)
Definition at line 95 of file configuration.py.
References funcs, and list.
get_func_section()
configuration.object_c.get_func_section (self, dumps, func)
Definition at line 70 of file configuration.py.
Referenced by append().
read_dump_info()
configuration.object_c.read_dump_info (self, pathes)
Definition at line 57 of file configuration.py.
References list.
sections()
configuration.object_c.sections (self)
Definition at line 101 of file configuration.py.
References funcs, and list.
Member Data Documentation
dumps
configuration.object_c.dumps = self.read_dump_info(pathes)
Definition at line 88 of file configuration.py.
Referenced by append().
funcs
configuration.object_c.funcs = dict()
Definition at line 86 of file configuration.py.
Referenced by append(), functions(), and sections().
libray
configuration.object_c.libray = libray
Definition at line 85 of file configuration.py.
name
configuration.object_c.name = name
Definition at line 84 of file configuration.py.
Referenced by configuration.library_c.append().
pathes
configuration.object_c.pathes = pathes
Definition at line 87 of file configuration.py.
The documentation for this class was generated from the following file:
managed_components/espressif__cmake_utilities/scripts/relinker/configuration.py