Kicker Controller: configuration.libraries_c Class Reference
configuration.libraries_c Class Reference
Public Member Functions
__init__ (self)
append (self, lib, lib_path, obj, obj_path, func)
dump (self)
Public Attributes
libs = dict()
Detailed Description
Definition at line 118 of file configuration.py.
Constructor & Destructor Documentation
__init__()
configuration.libraries_c.__init__ (self)
Definition at line 119 of file configuration.py.
Member Function Documentation
append()
configuration.libraries_c.append (self, lib, lib_path, obj, obj_path, func)
Definition at line 122 of file configuration.py.
References append(), and libs.
Referenced by append().
dump()
configuration.libraries_c.dump (self)
Definition at line 127 of file configuration.py.
References libs.
Member Data Documentation
libs
configuration.libraries_c.libs = dict()
Definition at line 120 of file configuration.py.
Referenced by append(), dump(), and relinker.filter_c.match().
The documentation for this class was generated from the following file:
managed_components/espressif__cmake_utilities/scripts/relinker/configuration.py