Kicker Controller: managed_components/espressif__esp-now/src/debug/src/commands/cmd_iperf.c File Reference
cmd_iperf.c File Reference
#include <string.h>
#include "esp_console.h"
#include "argtable3/argtable3.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_timer.h"
#include "espnow.h"
#include "espnow_console.h"
#include "espnow_ctrl.h"
#include "espnow_log.h"
#include "espnow_ota.h"
#include "espnow_prov.h"
#include "espnow_utils.h"
#include <esp_https_ota.h>
#include <esp_log.h>
#include <esp_ota_ops.h>
#include <errno.h>
#include <sys/param.h>
#include "driver/gpio.h"
Classes
struct espnow_iperf_cfg
struct espnow_iperf_data_t
struct iperf_recv_data_t
Macros
#define IPERF_QUEUE_SIZE 10
Enumerations
enum iperf_type_t {
IPERF_BANDWIDTH , IPERF_BANDWIDTH_STOP , IPERF_BANDWIDTH_STOP_ACK , IPERF_PING ,
IPERF_PING_ACK
}
Functions
void register_espnow_config ()
void register_espnow_iperf ()
void register_iperf (void)
Variables
struct espnow_iperf_cfg g_iperf_cfg
Macro Definition Documentation
IPERF_QUEUE_SIZE
#define IPERF_QUEUE_SIZE 10
Definition at line 205 of file cmd_iperf.c.
Enumeration Type Documentation
iperf_type_t
enum iperf_type_t
Enumerator
IPERF_BANDWIDTH
IPERF_BANDWIDTH_STOP
IPERF_BANDWIDTH_STOP_ACK
IPERF_PING
IPERF_PING_ACK
Definition at line 191 of file cmd_iperf.c.
Function Documentation
register_espnow_config()
void register_espnow_config ()
Definition at line 146 of file cmd_iperf.c.
Referenced by register_iperf().
register_espnow_iperf()
void register_espnow_iperf ()
Definition at line 677 of file cmd_iperf.c.
Referenced by register_iperf().
register_iperf()
void register_iperf (void)
Definition at line 704 of file cmd_iperf.c.
References register_espnow_config(), and register_espnow_iperf().
Referenced by espnow_console_commands_register().
Variable Documentation
abort
struct arg_lit* abort
Definition at line 551 of file cmd_iperf.c.
ack
struct arg_lit* ack
Definition at line 549 of file cmd_iperf.c.
broadcast
struct arg_int* broadcast
Definition at line 547 of file cmd_iperf.c.
channel
struct arg_int* channel
Definition at line 46 of file cmd_iperf.c.
count
struct arg_int* count
Definition at line 543 of file cmd_iperf.c.
country_code
struct arg_str* country_code
Definition at line 52 of file cmd_iperf.c.
end
struct arg_end* end
Definition at line 54 of file cmd_iperf.c.
g_iperf_cfg
struct espnow_iperf_cfg g_iperf_cfg
Initial value:
= {
    .finish = true,
    .packet_len      = ESPNOW_DATA_LEN,
    .transmit_time   = 60,
    .report_interval = 3,
    .ping_count      = 64,
    .frame_head.group     = false,
    .type            = ESPNOW_DATA_TYPE_RESERVED,
}
gpio
struct arg_int* gpio
Definition at line 550 of file cmd_iperf.c.
group
struct arg_lit* group
Definition at line 548 of file cmd_iperf.c.
info
struct arg_lit* info
Definition at line 53 of file cmd_iperf.c.
initiator
struct arg_str* initiator
Definition at line 540 of file cmd_iperf.c.
interval
struct arg_int* interval
Definition at line 544 of file cmd_iperf.c.
len
struct arg_int* len
Definition at line 545 of file cmd_iperf.c.
ping
struct arg_lit* ping
Definition at line 542 of file cmd_iperf.c.
protocol
struct arg_int* protocol
Definition at line 51 of file cmd_iperf.c.
Referenced by hid_class_request_get_protocol(), and hid_class_request_set_protocol().
rate
struct arg_int* rate
Definition at line 48 of file cmd_iperf.c.
responder
struct arg_lit* responder
Definition at line 541 of file cmd_iperf.c.
time
struct arg_int* time
Definition at line 546 of file cmd_iperf.c.
Referenced by espnow_log_flash_write(), espnow_timesync_check(), and espnow_timesync_wait().
tx_power
struct arg_int* tx_power
Definition at line 50 of file cmd_iperf.c.