Kicker Controller: managed_components/espressif__esp-now/src/debug/src/commands/cmd_wifi.c File Reference
cmd_wifi.c File Reference
#include <stdio.h>
#include <string.h>
#include "sdkconfig.h"
#include "lwip/inet.h"
#include "lwip/netdb.h"
#include "lwip/sockets.h"
#include "esp_console.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "esp_wifi.h"
#include "espnow_utils.h"
#include "nvs_flash.h"
#include "argtable3/argtable3.h"
#include "ping/ping_sock.h"
Functions
void register_wifi_scan ()
Register wifi scan command.
void register_wifi_ping (void)
void register_wifi_ap (void)
void register_wifi (void)
Function Documentation
register_wifi()
void register_wifi (void)
Definition at line 508 of file cmd_wifi.c.
References register_wifi_ap(), register_wifi_ping(), and register_wifi_scan().
Referenced by espnow_console_commands_register().
register_wifi_ap()
void register_wifi_ap (void)
Definition at line 491 of file cmd_wifi.c.
Referenced by register_wifi().
register_wifi_ping()
void register_wifi_ping (void)
Definition at line 422 of file cmd_wifi.c.
Referenced by register_wifi().
register_wifi_scan()
void register_wifi_scan ()
Register wifi scan command.
Definition at line 128 of file cmd_wifi.c.
Referenced by register_wifi().
Variable Documentation
bssid
struct arg_str* bssid
Definition at line 43 of file cmd_wifi.c.
channel
struct arg_int* channel
Definition at line 149 of file cmd_wifi.c.
count
struct arg_int* count
Definition at line 337 of file cmd_wifi.c.
country_code
struct arg_str* country_code
Definition at line 148 of file cmd_wifi.c.
data_size
struct arg_int* data_size
Definition at line 336 of file cmd_wifi.c.
Referenced by espnow_log_flash_read().
disconnt
struct arg_lit* disconnt
Definition at line 155 of file cmd_wifi.c.
end
struct arg_end* end
Definition at line 45 of file cmd_wifi.c.
host
struct arg_str* host
Definition at line 339 of file cmd_wifi.c.
Referenced by sdcard_init().
info
struct arg_lit* info
Definition at line 154 of file cmd_wifi.c.
interval
struct arg_dbl* interval
Definition at line 335 of file cmd_wifi.c.
passive
struct arg_int* passive
Definition at line 44 of file cmd_wifi.c.
password
struct arg_str* password
Definition at line 152 of file cmd_wifi.c.
rssi
struct arg_int* rssi
Definition at line 41 of file cmd_wifi.c.
ssid
struct arg_str* ssid
Definition at line 42 of file cmd_wifi.c.
timeout
struct arg_dbl* timeout
Definition at line 334 of file cmd_wifi.c.
Referenced by hid_host_handle_events().
tos
struct arg_int* tos
Definition at line 338 of file cmd_wifi.c.
tx_power
struct arg_int* tx_power
Definition at line 153 of file cmd_wifi.c.