Kicker Controller: managed_components/espressif__esp-now/examples/coin_cell_demo/bulb/main/app_main.c File Reference
app_main.c File Reference
#include "esp_log.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/timers.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "espnow_utils.h"
#include "espnow.h"
#include "espnow_ctrl.h"
#include "led_strip.h"
#include "driver/gpio.h"
Macros
#define UNBIND_TOTAL_COUNT (5)
#define BULB_STATUS_KEY "bulb_key"
Functions
void app_led_set_color (uint8_t red, uint8_t green, uint8_t blue)
void app_main (void)
Macro Definition Documentation
BULB_STATUS_KEY
#define BULB_STATUS_KEY "bulb_key"
Definition at line 58 of file app_main.c.
UNBIND_TOTAL_COUNT
#define UNBIND_TOTAL_COUNT (5)
Definition at line 56 of file app_main.c.
Function Documentation
app_led_set_color()
void app_led_set_color (uint8_t red, uint8_t green, uint8_t blue)
Definition at line 160 of file app_main.c.
Referenced by app_main().
app_main()
void app_main (void)
Definition at line 252 of file app_main.c.
References app_led_set_color(), espnow_init(), ESPNOW_INIT_CONFIG_DEFAULT, and espnow_storage_init().