Kicker Controller: main/tasks/display_task.cpp File Reference
display_task.cpp File Reference
This is the file that contains the display task.
#include "../../include/tasks/display_task.h"
Functions
void display_task (void *pv)
This is the task that handles driving the display with the menus and values.
Detailed Description
This is the file that contains the display task.
Author
Shane Wood
Definition in file display_task.cpp.
Function Documentation
display_task()
void display_task (void * pv)
This is the task that handles driving the display with the menus and values.
Definition at line 10 of file display_task.cpp.
References battery_voltage_string, boot_screen_wait_time, bus_handle, ssd1306::clear_buffer(), contoller_connected, current_network_channel, display_task_wait_time, menu< T >::draw_to_display(), drive_motor_speed, drive_motor_speed_modifier_step_size, i2c_frequency, maximum_drive_motor_speed_modifier, maximum_network_channel, maximum_turn_motor_speed_modifier, maximum_velocity_gain, maximum_velocity_integrator_gain, maximum_velocity_ramp_limit, minimum_drive_motor_speed_modifier, minimum_network_channel, minimum_turn_motor_speed_modifier, minimum_velocity_gain, minimum_velocity_integrator_gain, minimum_velocity_ramp_limit, robot_connected, SSD1306_address, status, turn_motor_speed, turn_motor_speed_modifier_step_size, menu_handler::update(), values_2, values_3, values_4, velocity_gain, velocity_gain_step_size, velocity_integrator_gain, velocity_integrator_gain_step_size, velocity_ramp_limit, velocity_ramp_limit_step_size, and ssd1306::write_buffer_SSD1306().
Referenced by app_main().