Kicker Controller: managed_components/espressif__esp-now/examples/wireless_debug/components/web_server/dns_server.c File Reference
dns_server.c File Reference
#include "dns_server.h"
Classes
struct dns_header_flags_t
struct dns_header_t
struct dns_answer
struct dns_query
Macros
#define DNS_MAX_HOST_NAME_LEN 128
Typedefs
typedef struct dns_answer dns_answer_t
typedef struct dns_query dns_query_t
Functions
err_t dnserv_init (const ip_addr_t *bind, uint16_t port, dns_query_proc_t qp)
void dnserv_free ()
Variables
dns_query_proc_t query_proc = NULL
Macro Definition Documentation
DNS_MAX_HOST_NAME_LEN
#define DNS_MAX_HOST_NAME_LEN 128
Definition at line 32 of file dns_server.c.
Typedef Documentation
dns_answer_t
typedef struct dns_answer dns_answer_t
dns_query_t
typedef struct dns_query dns_query_t
Function Documentation
dnserv_free()
void dnserv_free (void)
Definition at line 236 of file dns_server.c.
Referenced by dnserv_init().
dnserv_init()
err_t dnserv_init (const ip_addr_t * bind, uint16_t port, dns_query_proc_t qp)
Definition at line 213 of file dns_server.c.
References bind, dnserv_free(), and query_proc.
Referenced by web_server_start().
Variable Documentation
query_proc
dns_query_proc_t query_proc = NULL
Definition at line 35 of file dns_server.c.
Referenced by dnserv_init().