Kicker Controller: managed_components/espressif__esp-now/examples/wireless_debug/components/web_server/dns_server.h File Reference
dns_server.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "lwip/def.h"
#include "lwip/err.h"
#include "lwip/udp.h"
#include "netif/etharp.h"
Macros
#define DNS_SERVER_PORT 53
Typedefs
typedef bool(* dns_query_proc_t) (const char *name, ip_addr_t *addr)
Functions
err_t dnserv_init (const ip_addr_t *bind, uint16_t port, dns_query_proc_t query_proc)
void dnserv_free (void)
Macro Definition Documentation
DNS_SERVER_PORT
#define DNS_SERVER_PORT 53
DNS server port address
Definition at line 44 of file dns_server.h.
Referenced by web_server_start().
Typedef Documentation
dns_query_proc_t
typedef bool(* dns_query_proc_t) (const char *name, ip_addr_t *addr)
Definition at line 47 of file dns_server.h.
Function Documentation
dnserv_free()
void dnserv_free (void)
Definition at line 236 of file dns_server.c.
Referenced by dnserv_init().
dnserv_init()
err_t dnserv_init (const ip_addr_t * bind, uint16_t port, dns_query_proc_t query_proc)
Definition at line 213 of file dns_server.c.
References bind, dnserv_free(), and query_proc.
Referenced by web_server_start().