Kicker Controller: managed_components/espressif__esp-now/src/espnow/include/espnow.h File Reference
espnow.h File Reference
#include "esp_now.h"
#include "espnow_utils.h"
#include "espnow_security.h"
Classes
struct espnow_config_t
Initialize the configuration of espnow.
struct espnow_frame_head_s
Frame header of espnow.
Macros
#define ESPNOW_PACKED_STRUCT __attribute__ ((packed))
#define ESPNOW_PAYLOAD_LEN (230)
#define ESPNOW_DATA_LEN ESPNOW_PAYLOAD_LEN
#define ESPNOW_ADDR_LEN (6)
#define ESPNOW_ADDR_IS_EMPTY(addr)
#define ESPNOW_ADDR_IS_BROADCAST(addr)
#define ESPNOW_ADDR_IS_SELF(addr)
#define ESPNOW_ADDR_IS_EQUAL(addr1, addr2)
#define ESP_EVENT_ESPNOW_PROV_BASE 0x100
#define ESP_EVENT_ESPNOW_CTRL_BASE 0x200
#define ESP_EVENT_ESPNOW_OTA_BASE 0x300
#define ESP_EVENT_ESPNOW_DEBUG_BASE 0x400
#define ESP_EVENT_ESPNOW_RESERVED_BASE 0x500
#define ESPNOW_CHANNEL_CURRENT 0x0
The channel on which the device sends packets.
#define ESPNOW_CHANNEL_ALL 0x0f
#define ESPNOW_RETRANSMIT_MAX_COUNT 0x1f
#define ESPNOW_FORWARD_MAX_COUNT 0x1f
#define ESPNOW_INIT_CONFIG_DEFAULT()
#define ESPNOW_FRAME_CONFIG_DEFAULT()
Typedefs
typedef uint8_t espnow_addr_t[6]
typedef uint8_t espnow_group_t[6]
typedef struct espnow_frame_head_s espnow_frame_head_t
Frame header of espnow.
typedef esp_err_t(* handler_for_data_t) (uint8_t *src_addr, void *data, size_t size, wifi_pkt_rx_ctrl_t *rx_ctrl)
ESP-NOW data receive callback function for the corresponding data type.
Enumerations
enum espnow_data_type_t {
ESPNOW_DATA_TYPE_ACK , ESPNOW_DATA_TYPE_FORWARD , ESPNOW_DATA_TYPE_GROUP , ESPNOW_DATA_TYPE_PROV ,
ESPNOW_DATA_TYPE_CONTROL_BIND , ESPNOW_DATA_TYPE_CONTROL_DATA , ESPNOW_DATA_TYPE_OTA_STATUS , ESPNOW_DATA_TYPE_OTA_DATA ,
ESPNOW_DATA_TYPE_DEBUG_LOG , ESPNOW_DATA_TYPE_DEBUG_COMMAND , ESPNOW_DATA_TYPE_DATA , ESPNOW_DATA_TYPE_SECURITY_STATUS ,
ESPNOW_DATA_TYPE_SECURITY , ESPNOW_DATA_TYPE_SECURITY_DATA , ESPNOW_DATA_TYPE_RESERVED , ESPNOW_DATA_TYPE_MAX
}
Divide ESP-NOW data into multiple pipes.
Functions
ESP_EVENT_DECLARE_BASE (ESP_EVENT_ESPNOW)
Declaration of the task events family.
esp_err_t espnow_add_peer (const espnow_addr_t addr, const uint8_t *lmk)
When used for unicast, add the target device.
esp_err_t espnow_del_peer (const espnow_addr_t addr)
When used for unicast, delete the target device.
esp_err_t espnow_send (espnow_data_type_t type, const espnow_addr_t dest_addr, const void *data, size_t size, const espnow_frame_head_t *frame_config, TickType_t wait_ticks)
Send ESP-NOW data.
esp_err_t espnow_deinit (void)
De-initialize ESP-NOW function.
esp_err_t espnow_init (const espnow_config_t *config)
Initialize ESP-NOW function.
esp_err_t espnow_set_config_for_data_type (espnow_data_type_t type, bool enable, handler_for_data_t handle)
Set configuration when receiving the corresponding ESP-NOW data type Include: Set to enable/disable handling the corresponding ESP-NOW data type Set the callback function when receiving the corresponding ESP-NOW data type.
esp_err_t espnow_get_config_for_data_type (espnow_data_type_t type, bool *enable)
Get the configuration that whether to handle the corresponding ESP-NOW data type.
esp_err_t espnow_add_group (const espnow_group_t group_id)
Set group ID addresses.
esp_err_t espnow_del_group (const espnow_group_t group_id)
Delete group ID addresses.
int espnow_get_group_num (void)
Get the number of group ID addresses.
esp_err_t espnow_get_group_list (espnow_group_t *group_id_list, size_t num)
Get group ID addresses.
bool espnow_is_my_group (const espnow_group_t group_id)
Check whether the specified group address is my group.
esp_err_t espnow_set_group (const espnow_addr_t *addrs_list, size_t addrs_num, const espnow_group_t group_id, espnow_frame_head_t *frame_head, bool enable, TickType_t wait_ticks)
Dynamically set the grouping of devices through commands.
esp_err_t espnow_set_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
esp_err_t espnow_get_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
esp_err_t espnow_erase_key (void)
Erase the security key info stored in flash.
esp_err_t espnow_set_dec_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
esp_err_t espnow_get_dec_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
esp_err_t espnow_erase_dec_key (void)
Erase the security key info stored in flash.
Variables
const uint8_t ESPNOW_ADDR_NONE [6]
const uint8_t ESPNOW_ADDR_BROADCAST [6]
const uint8_t ESPNOW_ADDR_GROUP_OTA [6]
const uint8_t ESPNOW_ADDR_GROUP_SEC [6]
const uint8_t ESPNOW_ADDR_GROUP_PROV [6]
Macro Definition Documentation
ESP_EVENT_ESPNOW_CTRL_BASE
#define ESP_EVENT_ESPNOW_CTRL_BASE 0x200
Definition at line 56 of file espnow.h.
ESP_EVENT_ESPNOW_DEBUG_BASE
#define ESP_EVENT_ESPNOW_DEBUG_BASE 0x400
Definition at line 58 of file espnow.h.
ESP_EVENT_ESPNOW_OTA_BASE
#define ESP_EVENT_ESPNOW_OTA_BASE 0x300
Definition at line 57 of file espnow.h.
ESP_EVENT_ESPNOW_PROV_BASE
#define ESP_EVENT_ESPNOW_PROV_BASE 0x100
Definition at line 55 of file espnow.h.
ESP_EVENT_ESPNOW_RESERVED_BASE
#define ESP_EVENT_ESPNOW_RESERVED_BASE 0x500
Definition at line 59 of file espnow.h.
ESPNOW_ADDR_IS_BROADCAST
#define ESPNOW_ADDR_IS_BROADCAST (addr)
Value:
(((addr)[0] & (addr)[1] & (addr)[2] & (addr)[3] & (addr)[4] & (addr)[5]) == 0xFF)
Definition at line 37 of file espnow.h.
Referenced by espnow_del_peer(), espnow_ota_initiator_send(), espnow_recv_cb(), and espnow_send().
ESPNOW_ADDR_IS_EMPTY
#define ESPNOW_ADDR_IS_EMPTY (addr)
Value:
(((addr)[0] | (addr)[1] | (addr)[2] | (addr)[3] | (addr)[4] | (addr)[5]) == 0x0)
Definition at line 36 of file espnow.h.
ESPNOW_ADDR_IS_EQUAL
#define ESPNOW_ADDR_IS_EQUAL (addr1, addr2)
Value:
!memcmp(addr1, addr2, 6)
Definition at line 39 of file espnow.h.
ESPNOW_ADDR_IS_SELF
#define ESPNOW_ADDR_IS_SELF (addr)
Value:
!memcmp(addr, ESPNOW_ADDR_SELF, 6)
Definition at line 38 of file espnow.h.
Referenced by espnow_recv_cb().
ESPNOW_ADDR_LEN
#define ESPNOW_ADDR_LEN (6)
Definition at line 35 of file espnow.h.
Referenced by app_main(), espnow_ota_initiator_send(), espnow_recv_cb(), and espnow_set_group().
ESPNOW_CHANNEL_ALL
#define ESPNOW_CHANNEL_ALL 0x0f
All supported channels
Definition at line 65 of file espnow.h.
Referenced by espnow_recv_cb(), espnow_send(), and espnow_set_group().
ESPNOW_CHANNEL_CURRENT
#define ESPNOW_CHANNEL_CURRENT 0x0
The channel on which the device sends packets.
Only in the current channel
Definition at line 64 of file espnow.h.
ESPNOW_DATA_LEN
#define ESPNOW_DATA_LEN ESPNOW_PAYLOAD_LEN
Definition at line 32 of file espnow.h.
Referenced by espnow_send().
ESPNOW_FORWARD_MAX_COUNT
#define ESPNOW_FORWARD_MAX_COUNT 0x1f
Maximum number of forwards
Definition at line 68 of file espnow.h.
Referenced by espnow_recv_cb().
ESPNOW_FRAME_CONFIG_DEFAULT
#define ESPNOW_FRAME_CONFIG_DEFAULT ()
Value:
    { \
        .broadcast = true, \
        .retransmit_count = 10, \
    }
Definition at line 174 of file espnow.h.
Referenced by espnow_ota_responder_stop().
ESPNOW_INIT_CONFIG_DEFAULT
#define ESPNOW_INIT_CONFIG_DEFAULT ()
Value:
    { \
    .pmk = "ESP_NOW", \
    .forward_enable = 1, \
    .forward_switch_channel = 0, \
    .sec_enable = 0, \
    .reserved1 = 0,   \
    .qsize = 32, \
    .send_retry_num = 10, \
    .send_max_timeout = pdMS_TO_TICKS(3000),\
    .receive_enable = { \
                .ack           = 1, \
                .forward       = 1, \
                .group         = 1, \
                .provisoning   = 0, \
                .control_bind  = 0, \
                .control_data  = 0, \
                .ota_status    = 0, \
                .ota_data      = 0, \
                .debug_log     = 0, \
                .debug_command = 0, \
                .data          = 0, \
                .sec_status    = 0, \
                .sec           = 0, \
                .sec_data      = 0, \
                .reserved2     = 0, \
                }, \
    }
Definition at line 101 of file espnow.h.
Referenced by app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), app_main(), and app_main().
ESPNOW_PACKED_STRUCT
#define ESPNOW_PACKED_STRUCT __attribute__ ((packed))
< _cplusplus
Definition at line 26 of file espnow.h.
ESPNOW_PAYLOAD_LEN
#define ESPNOW_PAYLOAD_LEN (230)
Definition at line 27 of file espnow.h.
Referenced by espnow_set_group().
ESPNOW_RETRANSMIT_MAX_COUNT
#define ESPNOW_RETRANSMIT_MAX_COUNT 0x1f
Maximum number of retransmissions
Definition at line 67 of file espnow.h.
Typedef Documentation
espnow_addr_t
typedef uint8_t espnow_addr_t[6]
Definition at line 41 of file espnow.h.
espnow_frame_head_t
typedef struct espnow_frame_head_s espnow_frame_head_t
Frame header of espnow.
espnow_group_t
typedef uint8_t espnow_group_t[6]
Definition at line 42 of file espnow.h.
handler_for_data_t
typedef esp_err_t(* handler_for_data_t) (uint8_t *src_addr, void *data, size_t size, wifi_pkt_rx_ctrl_t *rx_ctrl)
ESP-NOW data receive callback function for the corresponding data type.
Parameters
[in] src_addr peer MAC address
[in] data received data
[in] size length of received data
[in] rx_ctrl received packet radio metadata header
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 231 of file espnow.h.
Enumeration Type Documentation
espnow_data_type_t
enum espnow_data_type_t
Divide ESP-NOW data into multiple pipes.
Enumerator
ESPNOW_DATA_TYPE_ACK
For reliable data transmission
ESPNOW_DATA_TYPE_FORWARD
Set to forward packets
ESPNOW_DATA_TYPE_GROUP
Send a packet that sets the group type
ESPNOW_DATA_TYPE_PROV
Network configuration packet
ESPNOW_DATA_TYPE_CONTROL_BIND
Binding or unbinding packet
ESPNOW_DATA_TYPE_CONTROL_DATA
Control data packet
ESPNOW_DATA_TYPE_OTA_STATUS
Status packet for rapid upgrade of batch Device
ESPNOW_DATA_TYPE_OTA_DATA
Data packet for rapid upgrade of batch Device
ESPNOW_DATA_TYPE_DEBUG_LOG
Equipment debugging log packet
ESPNOW_DATA_TYPE_DEBUG_COMMAND
Equipment debugging command packet
ESPNOW_DATA_TYPE_DATA
User-defined use
ESPNOW_DATA_TYPE_SECURITY_STATUS
Security status packet
ESPNOW_DATA_TYPE_SECURITY
Security handshake packet
ESPNOW_DATA_TYPE_SECURITY_DATA
Security packet
ESPNOW_DATA_TYPE_RESERVED
Reserved for other function
ESPNOW_DATA_TYPE_MAX
Definition at line 132 of file espnow.h.
Function Documentation
ESP_EVENT_DECLARE_BASE()
ESP_EVENT_DECLARE_BASE (ESP_EVENT_ESPNOW)
Declaration of the task events family.
espnow_add_group()
esp_err_t espnow_add_group (const espnow_group_t group_id)
Set group ID addresses.
Parameters
[in] group_id pointer to new group ID addresses
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Referenced by espnow_recv_cb().
espnow_add_peer()
esp_err_t espnow_add_peer (const espnow_addr_t addr, const uint8_t * lmk)
When used for unicast, add the target device.
Parameters
[in] addr peer MAC address
[in] lmk peer local master key that is used to encrypt data. It can be null or ESP_NOW_KEY_LEN length data
< If peer exists, delete a peer from peer list
< Add a peer to peer list
Definition at line 422 of file espnow.c.
References addr, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.
Referenced by espnow_init(), and espnow_prov_initiator_send().
espnow_deinit()
esp_err_t espnow_deinit (void)
De-initialize ESP-NOW function.
Returns
ESP_OK
ESP_ERR_ESPNOW_NOT_INIT
< De-initialize ESPNOW function
Definition at line 1102 of file espnow.c.
References ESP_ERROR_RETURN, ESP_FREE, ESPNOW_DATA_TYPE_MAX, ESPNOW_EVENT_STOP, and espnow_sec_deinit().
espnow_del_group()
esp_err_t espnow_del_group (const espnow_group_t group_id)
Delete group ID addresses.
Parameters
[in] group_id pointer to deleted group ID address
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 62 of file espnow_group.c.
References ESP_FREE, and espnow_group_item::id.
Referenced by espnow_recv_cb().
espnow_del_peer()
esp_err_t espnow_del_peer (const espnow_addr_t addr)
When used for unicast, delete the target device.
Parameters
[in] addr MAC address
Returns
ESP_OK
ESP_ERR_INVALID_ARG
< If peer exists, delete a peer from peer list
Definition at line 450 of file espnow.c.
References addr, ESP_ERROR_RETURN, ESP_PARAM_CHECK, and ESPNOW_ADDR_IS_BROADCAST.
Referenced by espnow_prov_initiator_send().
espnow_erase_dec_key()
esp_err_t espnow_erase_dec_key (void)
Erase the security key info stored in flash.
ESP_OK
ESP_ERR_NVS_NOT_FOUND _cplusplus
Definition at line 1250 of file espnow.c.
References APP_KEY_LEN, and espnow_storage_erase().
espnow_erase_key()
esp_err_t espnow_erase_key (void)
Erase the security key info stored in flash.
ESP_OK
ESP_ERR_NVS_NOT_FOUND
Definition at line 1208 of file espnow.c.
References APP_KEY_LEN, and espnow_storage_erase().
espnow_get_config_for_data_type()
esp_err_t espnow_get_config_for_data_type (espnow_data_type_t type, bool * enable)
Get the configuration that whether to handle the corresponding ESP-NOW data type.
Parameters
[in] type data type defined by espnow_data_type_t
[out] enable store the current receiving status of this data type
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1164 of file espnow.c.
References ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_MAX, and type.
espnow_get_dec_key()
esp_err_t espnow_get_dec_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
Parameters
[out] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1233 of file espnow.c.
References APP_KEY_LEN, ESP_PARAM_CHECK, and espnow_storage_get().
espnow_get_group_list()
esp_err_t espnow_get_group_list (espnow_group_t * group_id_list, size_t num)
Get group ID addresses.
Parameters
[out] group_id_list pointer to group ID addresses
[in] num the number of group ID addresses
Returns
ESP_OK
ESP_ERR_INVALID_ARG
espnow_get_group_num()
int espnow_get_group_num (void)
Get the number of group ID addresses.
Returns
the number of group ID addresses
Definition at line 77 of file espnow_group.c.
References count.
Referenced by espnow_recv_cb().
espnow_get_key()
esp_err_t espnow_get_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
Parameters
[out] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1191 of file espnow.c.
References APP_KEY_LEN, ESP_PARAM_CHECK, and espnow_storage_get().
Referenced by app_espnow_responder(), app_main(), and espnow_send().
espnow_init()
esp_err_t espnow_init (const espnow_config_t * config)
Initialize ESP-NOW function.
Parameters
[in] config configuration of ESP-NOW
Returns
ESP_OK
ESP_FAIL
< Event group for espnow sent cb
Definition at line 1041 of file espnow.c.
References config, ESP_ERROR_RETURN, ESP_MALLOC, ESP_PARAM_CHECK, espnow_add_peer(), ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_MAX, espnow_recv_cb(), espnow_sec_init(), espnow_send_cb(), ESPNOW_VERSION, and g_self_country.
Referenced by app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), app_main(), and app_main().
espnow_is_my_group()
bool espnow_is_my_group (const espnow_group_t group_id)
Check whether the specified group address is my group.
Parameters
[in] group_id pointer to the specified group ID addresses
Returns
true/false
Definition at line 105 of file espnow_group.c.
References espnow_group_item::id.
Referenced by espnow_recv_cb().
espnow_send()
esp_err_t espnow_send (espnow_data_type_t type, const espnow_addr_t dest_addr, const void * data, size_t size, const espnow_frame_head_t * frame_config, TickType_t wait_ticks)
Send ESP-NOW data.
Parameters
[in] type ESP-NOW data type defined by espnow_data_type_t
[in] dest_addr destination mac address
[in] data the sending data which must not be NULL
[in] size the maximum length of data, must be no more than ESPNOW_DATA_LEN
[in] frame_config if frame_config is NULL, Use ESPNOW_FRAME_CONFIG_DEFAULT configuration
[in] wait_ticks the maximum sending time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
ESP_ERR_TIMEOUT
ESP_ERR_WIFI_TIMEOUT
< Wait for other tasks to be sent before send ESP-NOW data
Definition at line 523 of file espnow.c.
References ack, espnow_frame_head_s::ack, addr, APP_KEY_LEN, espnow_frame_head_s::broadcast, espnow_frame_head_s::channel, count, ESP_ERROR_CONTINUE, ESP_ERROR_GOTO, ESP_ERROR_RETURN, ESP_FREE, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_ADDR_BROADCAST, ESPNOW_ADDR_IS_BROADCAST, ESPNOW_CHANNEL_ALL, ESPNOW_DATA_LEN, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_FORWARD, ESPNOW_DATA_TYPE_MAX, ESPNOW_DATA_TYPE_SECURITY, ESPNOW_DATA_TYPE_SECURITY_STATUS, espnow_get_key(), espnow_sec_auth_encrypt(), ESPNOW_SEC_OVER, espnow_set_key(), ESPNOW_VERSION, espnow_frame_head_s::forward_rssi, g_self_country, IV_LEN, KEY_LEN, espnow_frame_head_s::magic, espnow_frame_head_s::retransmit_count, espnow_frame_head_s::security, SEND_CB_FAIL, SEND_CB_OK, and type.
Referenced by espnow_ctrl_initiator_bind(), espnow_ctrl_initiator_send(), espnow_ctrl_send(), espnow_ota_initiator_scan(), espnow_ota_initiator_send(), espnow_ota_responder_stop(), espnow_prov_initiator_send(), and espnow_sec_initiator_scan().
espnow_set_config_for_data_type()
esp_err_t espnow_set_config_for_data_type (espnow_data_type_t type, bool enable, handler_for_data_t handle)
Set configuration when receiving the corresponding ESP-NOW data type Include: Set to enable/disable handling the corresponding ESP-NOW data type Set the callback function when receiving the corresponding ESP-NOW data type.
Parameters
[in] type data type defined by espnow_data_type_t
[in] enable enable or disable the receive of data type, false - disable, true - enable
[in] handle the receive callback function for data type
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1146 of file espnow.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_MAX, and type.
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_main(), espnow_console_deinit(), espnow_console_init(), espnow_ctrl_recv(), espnow_ctrl_responder_bind(), espnow_ctrl_responder_data(), espnow_ota_initiator_scan(), espnow_ota_initiator_send(), espnow_ota_responder_start(), espnow_prov_initiator_scan(), espnow_prov_initiator_send(), espnow_prov_responder_start(), espnow_sec_initiator_scan(), and espnow_sec_initiator_start().
espnow_set_dec_key()
esp_err_t espnow_set_dec_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
Attention
Set sec_enable in espnow_config to true when ESP-NOW initializes, or the function will return failed.
Parameters
[in] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1215 of file espnow.c.
References APP_KEY_LEN, ESP_ERROR_RETURN, ESP_PARAM_CHECK, espnow_sec_setkey(), espnow_storage_set(), and KEY_LEN.
Referenced by app_espnow_responder(), and app_main().
espnow_set_group()
esp_err_t espnow_set_group (const espnow_addr_t * addrs_list, size_t addrs_num, const espnow_group_t group_id, espnow_frame_head_t * frame_head, bool enable, TickType_t wait_ticks)
Dynamically set the grouping of devices through commands.
Parameters
[in] addrs_list MAC address list of the grouping devices
[in] addrs_num number of the grouping devices
[in] group_id pointer to the specified group ID addresses
[in] frame_head use ESPNOW_FRAME_CONFIG_DEFAULT configuration if frame_config is NULL
[in] enable true: add group, false: delete group
[in] wait_ticks the maximum sending time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
References APP_KEY_LEN.
Referenced by espnow_ota_initiator_send().
espnow_set_key()
esp_err_t espnow_set_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
Attention
Set sec_enable in espnow_config to true when ESP-NOW initializes, or the function will return failed.
Parameters
[in] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1173 of file espnow.c.
References APP_KEY_LEN, ESP_ERROR_RETURN, ESP_PARAM_CHECK, espnow_sec_setkey(), espnow_storage_set(), and KEY_LEN.
Referenced by app_espnow_responder(), app_main(), and espnow_send().
Variable Documentation
ESPNOW_ADDR_BROADCAST
const uint8_t ESPNOW_ADDR_BROADCAST[6] extern
Definition at line 133 of file espnow.c.
Referenced by espnow_ctrl_initiator_bind(), espnow_ctrl_initiator_send(), espnow_ctrl_send(), espnow_init(), espnow_ota_initiator_scan(), espnow_ota_responder_stop(), espnow_sec_initiator_scan(), espnow_send(), and espnow_set_group().
ESPNOW_ADDR_GROUP_OTA
const uint8_t ESPNOW_ADDR_GROUP_OTA[6] extern
Definition at line 134 of file espnow.c.
Referenced by espnow_ota_initiator_send().
ESPNOW_ADDR_GROUP_PROV
const uint8_t ESPNOW_ADDR_GROUP_PROV[6] extern
Definition at line 135 of file espnow.c.
ESPNOW_ADDR_GROUP_SEC
const uint8_t ESPNOW_ADDR_GROUP_SEC[6] extern
Definition at line 136 of file espnow.c.
ESPNOW_ADDR_NONE
const uint8_t ESPNOW_ADDR_NONE[6] extern
Definition at line 132 of file espnow.c.