Kicker Controller: managed_components/espressif__esp-now/src/ota/include/espnow_ota.h File Reference
espnow_ota.h File Reference
#include "esp_ota_ops.h"
#include "esp_partition.h"
#include "esp_app_format.h"
#include "espnow.h"
#include "espnow_utils.h"
Classes
struct espnow_ota_info_s
Firmware upgrade information.
struct espnow_ota_responder_s
Responder upgrade information.
struct espnow_ota_packet_s
Firmware packet.
struct espnow_ota_config_s
Upgrade configuration.
struct espnow_ota_status_s
Status packet.
struct espnow_ota_result_s
List of device status during the upgrade process.
Macros
#define ESPNOW_OTA_HASH_LEN 16
#define ESP_ERR_ESPNOW_OTA_BASE 0x1000
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_NOT_INIT (ESP_ERR_ESPNOW_OTA_BASE + 1)
Upgrade error code definition.
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_PARTITION (ESP_ERR_ESPNOW_OTA_BASE + 2)
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_INVALID (ESP_ERR_ESPNOW_OTA_BASE + 3)
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_INCOMPLETE (ESP_ERR_ESPNOW_OTA_BASE + 4)
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_DOWNLOAD (ESP_ERR_ESPNOW_OTA_BASE + 5)
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_FINISH (ESP_ERR_ESPNOW_OTA_BASE + 6)
#define ESP_ERR_ESPNOW_OTA_DEVICE_NO_EXIST (ESP_ERR_ESPNOW_OTA_BASE + 7)
#define ESP_ERR_ESPNOW_OTA_SEND_PACKET_LOSS (ESP_ERR_ESPNOW_OTA_BASE + 8)
#define ESP_ERR_ESPNOW_OTA_NOT_INIT (ESP_ERR_ESPNOW_OTA_BASE + 9)
#define ESP_ERR_ESPNOW_OTA_STOP (ESP_ERR_ESPNOW_OTA_BASE + 10)
#define ESP_ERR_ESPNOW_OTA_FINISH (ESP_ERR_ESPNOW_OTA_BASE + 11)
#define ESP_EVENT_ESPNOW_OTA_STARTED (ESP_EVENT_ESPNOW_OTA_BASE + 1)
enumerated list of upgrade event id
#define ESP_EVENT_ESPNOW_OTA_STATUS (ESP_EVENT_ESPNOW_OTA_BASE + 2)
#define ESP_EVENT_ESPNOW_OTA_FINISH (ESP_EVENT_ESPNOW_OTA_BASE + 3)
#define ESP_EVENT_ESPNOW_OTA_STOPED (ESP_EVENT_ESPNOW_OTA_BASE + 4)
#define ESP_EVENT_ESPNOW_OTA_FIRMWARE_DOWNLOAD (ESP_EVENT_ESPNOW_OTA_BASE + 5)
#define ESP_EVENT_ESPNOW_OTA_SEND_FINISH (ESP_EVENT_ESPNOW_OTA_BASE + 6)
#define ESPNOW_OTA_PROGRESS_MAX_SIZE (ESPNOW_DATA_LEN - 30)
Firmware subcontract upgrade.
#define ESPNOW_OTA_PACKET_MAX_SIZE ((ESPNOW_DATA_LEN - 4) - (ESPNOW_DATA_LEN -4) % 16)
#define ESPNOW_OTA_PACKET_MAX_NUM (4 * 1024 * 1024/ ESPNOW_OTA_PACKET_MAX_SIZE)
#define ESPNOW_OTA_GET_BITS(data, bits)
Bit operations to get and modify a bit in an array.
#define ESPNOW_OTA_SET_BITS(data, bits)
#define CONFIG_ESPNOW_OTA_SECURITY 0
Typedefs
typedef struct espnow_ota_info_s espnow_ota_info_t
Firmware upgrade information.
typedef struct espnow_ota_responder_s espnow_ota_responder_t
Responder upgrade information.
typedef struct espnow_ota_packet_s espnow_ota_packet_t
Firmware packet.
typedef struct espnow_ota_config_s espnow_ota_config_t
Upgrade configuration.
typedef struct espnow_ota_status_s espnow_ota_status_t
Status packet.
typedef struct espnow_ota_result_s espnow_ota_result_t
List of device status during the upgrade process.
typedef esp_err_t(* espnow_ota_initiator_data_cb_t) (size_t src_offset, void *dst, size_t size)
The upgrade data callback function Read firmware data from flash to send to unfinished device.
Enumerations
enum espnow_ota_type_t { ESPNOW_OTA_TYPE_REQUEST , ESPNOW_OTA_TYPE_INFO , ESPNOW_OTA_TYPE_DATA , ESPNOW_OTA_TYPE_STATUS }
Type of packet.
Functions
esp_err_t espnow_ota_initiator_send (const espnow_addr_t *addrs_list, size_t addrs_num, const uint8_t sha_256[ESPNOW_OTA_HASH_LEN], size_t size, espnow_ota_initiator_data_cb_t ota_data_cb, espnow_ota_result_t *res)
Root sends firmware to other nodes.
esp_err_t espnow_ota_initiator_stop ()
Stop root to send firmware to other nodes.
esp_err_t espnow_ota_initiator_result_free (espnow_ota_result_t *result)
Free memory in the result list.
esp_err_t espnow_ota_initiator_scan (espnow_ota_responder_t **info_list, size_t *num, TickType_t wait_ticks)
Root scans other nodes.
esp_err_t espnow_ota_initiator_scan_result_free (void)
Free memory in the responder information list.
esp_err_t espnow_ota_responder_get_status (espnow_ota_status_t *status)
Get the status of the upgrade.
esp_err_t espnow_ota_responder_stop ()
Stop upgrading.
esp_err_t espnow_ota_responder_start (const espnow_ota_config_t *config)
Start upgrading.
Macro Definition Documentation
CONFIG_ESPNOW_OTA_SECURITY
#define CONFIG_ESPNOW_OTA_SECURITY 0
Definition at line 146 of file espnow_ota.h.
Referenced by espnow_ota_initiator_scan(), espnow_ota_initiator_send(), and espnow_ota_responder_stop().
ESP_ERR_ESPNOW_OTA_BASE
#define ESP_ERR_ESPNOW_OTA_BASE 0x1000
Definition at line 29 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_DEVICE_NO_EXIST
#define ESP_ERR_ESPNOW_OTA_DEVICE_NO_EXIST (ESP_ERR_ESPNOW_OTA_BASE + 7)
The device that needs to be upgraded does not exist
Definition at line 39 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send().
ESP_ERR_ESPNOW_OTA_FINISH
#define ESP_ERR_ESPNOW_OTA_FINISH (ESP_ERR_ESPNOW_OTA_BASE + 11)
The running firmware has been upgraded
Definition at line 43 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_FIRMWARE_DOWNLOAD
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_DOWNLOAD (ESP_ERR_ESPNOW_OTA_BASE + 5)
Firmware write flash error
Definition at line 37 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_FIRMWARE_FINISH
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_FINISH (ESP_ERR_ESPNOW_OTA_BASE + 6)
The firmware has been written to completion
Definition at line 38 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_FIRMWARE_INCOMPLETE
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_INCOMPLETE (ESP_ERR_ESPNOW_OTA_BASE + 4)
The firmware received by the device is incomplete
Definition at line 36 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send().
ESP_ERR_ESPNOW_OTA_FIRMWARE_INVALID
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_INVALID (ESP_ERR_ESPNOW_OTA_BASE + 3)
Non-project generated firmware
Definition at line 35 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_FIRMWARE_NOT_INIT
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_NOT_INIT (ESP_ERR_ESPNOW_OTA_BASE + 1)
Upgrade error code definition.
Uninitialized firmware configuration
Definition at line 33 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_FIRMWARE_PARTITION
#define ESP_ERR_ESPNOW_OTA_FIRMWARE_PARTITION (ESP_ERR_ESPNOW_OTA_BASE + 2)
Partition table error
Definition at line 34 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_NOT_INIT
#define ESP_ERR_ESPNOW_OTA_NOT_INIT (ESP_ERR_ESPNOW_OTA_BASE + 9)
Upgrade configuration is not initialized
Definition at line 41 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_SEND_PACKET_LOSS
#define ESP_ERR_ESPNOW_OTA_SEND_PACKET_LOSS (ESP_ERR_ESPNOW_OTA_BASE + 8)
Request device upgrade status failed
Definition at line 40 of file espnow_ota.h.
ESP_ERR_ESPNOW_OTA_STOP
#define ESP_ERR_ESPNOW_OTA_STOP (ESP_ERR_ESPNOW_OTA_BASE + 10)
Upgrade stops with error
Definition at line 42 of file espnow_ota.h.
Referenced by espnow_ota_responder_stop().
ESP_EVENT_ESPNOW_OTA_FINISH
#define ESP_EVENT_ESPNOW_OTA_FINISH (ESP_EVENT_ESPNOW_OTA_BASE + 3)
The upgrade is complete and the new firmware will run after the reboot
Definition at line 50 of file espnow_ota.h.
ESP_EVENT_ESPNOW_OTA_FIRMWARE_DOWNLOAD
#define ESP_EVENT_ESPNOW_OTA_FIRMWARE_DOWNLOAD (ESP_EVENT_ESPNOW_OTA_BASE + 5)
Start writing firmware to flash
Definition at line 52 of file espnow_ota.h.
ESP_EVENT_ESPNOW_OTA_SEND_FINISH
#define ESP_EVENT_ESPNOW_OTA_SEND_FINISH (ESP_EVENT_ESPNOW_OTA_BASE + 6)
Send the firmware to other devices to complete
Definition at line 53 of file espnow_ota.h.
ESP_EVENT_ESPNOW_OTA_STARTED
#define ESP_EVENT_ESPNOW_OTA_STARTED (ESP_EVENT_ESPNOW_OTA_BASE + 1)
enumerated list of upgrade event id
The device starts to upgrade
Definition at line 48 of file espnow_ota.h.
ESP_EVENT_ESPNOW_OTA_STATUS
#define ESP_EVENT_ESPNOW_OTA_STATUS (ESP_EVENT_ESPNOW_OTA_BASE + 2)
Proactively report progress
Definition at line 49 of file espnow_ota.h.
ESP_EVENT_ESPNOW_OTA_STOPED
#define ESP_EVENT_ESPNOW_OTA_STOPED (ESP_EVENT_ESPNOW_OTA_BASE + 4)
Stop upgrading
Definition at line 51 of file espnow_ota.h.
ESPNOW_OTA_GET_BITS
#define ESPNOW_OTA_GET_BITS (data, bits)
Value:
((((uint8_t *)(data))[(bits) >> 0x3]) & (1 << ((bits) & 0x7)))
Bit operations to get and modify a bit in an array.
Definition at line 65 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send().
ESPNOW_OTA_HASH_LEN
#define ESPNOW_OTA_HASH_LEN 16
< _cplusplus
Definition at line 28 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send(), and espnow_ota_initiator_send().
ESPNOW_OTA_PACKET_MAX_NUM
#define ESPNOW_OTA_PACKET_MAX_NUM (4 * 1024 * 1024/ ESPNOW_OTA_PACKET_MAX_SIZE)
The maximum number of packets
Definition at line 60 of file espnow_ota.h.
ESPNOW_OTA_PACKET_MAX_SIZE
#define ESPNOW_OTA_PACKET_MAX_SIZE ((ESPNOW_DATA_LEN - 4) - (ESPNOW_DATA_LEN -4) % 16)
Maximum length of a single packet transmitted
Definition at line 59 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send().
ESPNOW_OTA_PROGRESS_MAX_SIZE
#define ESPNOW_OTA_PROGRESS_MAX_SIZE (ESPNOW_DATA_LEN - 30)
Firmware subcontract upgrade.
Maximum length of the array which indicates the packet processed
Definition at line 58 of file espnow_ota.h.
Referenced by espnow_ota_initiator_send().
ESPNOW_OTA_SET_BITS
#define ESPNOW_OTA_SET_BITS (data, bits)
Value:
do { (((uint8_t *)(data))[(bits) >> 0x3]) |= (1 << ((bits) & 0x7)); } while(0);
Definition at line 66 of file espnow_ota.h.
Typedef Documentation
espnow_ota_config_t
typedef struct espnow_ota_config_s espnow_ota_config_t
Upgrade configuration.
espnow_ota_info_t
typedef struct espnow_ota_info_s espnow_ota_info_t
Firmware upgrade information.
espnow_ota_initiator_data_cb_t
typedef esp_err_t(* espnow_ota_initiator_data_cb_t) (size_t src_offset, void *dst, size_t size)
The upgrade data callback function Read firmware data from flash to send to unfinished device.
Parameters
[in] src_offset address of the data to be read, relative to the beginning of the partition.
[out] dst pointer to the buffer where data should be stored. Pointer must be non-NULL and buffer must be at least 'size' bytes long.
[in] size size of data to be read, in bytes.
Returns
ESP_OK
ESP_FAIL
Definition at line 164 of file espnow_ota.h.
espnow_ota_packet_t
typedef struct espnow_ota_packet_s espnow_ota_packet_t
Firmware packet.
espnow_ota_responder_t
typedef struct espnow_ota_responder_s espnow_ota_responder_t
Responder upgrade information.
espnow_ota_result_t
typedef struct espnow_ota_result_s espnow_ota_result_t
List of device status during the upgrade process.
espnow_ota_status_t
typedef struct espnow_ota_status_s espnow_ota_status_t
Status packet.
Enumeration Type Documentation
espnow_ota_type_t
enum espnow_ota_type_t
Type of packet.
Enumerator
ESPNOW_OTA_TYPE_REQUEST
ESPNOW_OTA_TYPE_INFO
ESPNOW_OTA_TYPE_DATA
ESPNOW_OTA_TYPE_STATUS
Definition at line 89 of file espnow_ota.h.
Function Documentation
espnow_ota_initiator_result_free()
esp_err_t espnow_ota_initiator_result_free (espnow_ota_result_t * result)
Free memory in the result list.
Parameters
[in] result pointer to device upgrade status
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 506 of file espnow_ota_initiator.c.
References ESP_FREE, ESP_PARAM_CHECK, espnow_ota_result_s::requested_addr, espnow_ota_result_s::requested_num, espnow_ota_result_s::successed_addr, espnow_ota_result_s::successed_num, espnow_ota_result_s::unfinished_addr, and espnow_ota_result_s::unfinished_num.
Referenced by espnow_ota_initiator_send().
espnow_ota_initiator_scan()
esp_err_t espnow_ota_initiator_scan (espnow_ota_responder_t ** info_list, size_t * num, TickType_t wait_ticks)
Root scans other nodes.
Parameters
[out] info_list responder information list
[out] num responder number
[in] wait_ticks the maximum scanning time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 176 of file espnow_ota_initiator.c.
References CONFIG_ESPNOW_OTA_RETRANSMISSION_TIMES, CONFIG_ESPNOW_OTA_SECURITY, CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI, CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL, ESP_ERROR_GOTO, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_OTA_DATA, ESPNOW_DATA_TYPE_OTA_STATUS, espnow_ota_initiator_scan_result_free(), ESPNOW_OTA_TYPE_REQUEST, espnow_send(), and espnow_set_config_for_data_type().
Referenced by espnow_ota_initiator_send().
espnow_ota_initiator_scan_result_free()
esp_err_t espnow_ota_initiator_scan_result_free (void)
Free memory in the responder information list.
Returns
ESP_OK
Definition at line 214 of file espnow_ota_initiator.c.
References ESP_FREE.
Referenced by espnow_ota_initiator_scan(), and espnow_ota_initiator_send().
espnow_ota_initiator_send()
esp_err_t espnow_ota_initiator_send (const espnow_addr_t * addrs_list, size_t addrs_num, const uint8_t sha_256[ESPNOW_OTA_HASH_LEN], size_t size, espnow_ota_initiator_data_cb_t ota_data_cb, espnow_ota_result_t * res)
Root sends firmware to other nodes.
Attention
Only called at the root
Parameters
[in] addrs_list destination node mac list
[in] addrs_num number of destination nodes
[in] sha_256 SHA-256 digest for the upgrade partition
[in] size upgrade firmware total size
[in] ota_data_cb upgrade data callback function
[out] res must call espnow_ota_initiator_result_free to free memory
Returns
ESP_OK
ESP_ERR_ESPNOW_OTA_FIRMWARE_NOT_INIT
ESP_ERR_ESPNOW_OTA_DEVICE_NO_EXIST
References config, ESPNOW_OTA_HASH_LEN, and status.
espnow_ota_initiator_stop()
esp_err_t espnow_ota_initiator_stop ()
Stop root to send firmware to other nodes.
Returns
ESP_OK
ESP_ERR_NOT_SUPPORTED
Definition at line 520 of file espnow_ota_initiator.c.
espnow_ota_responder_get_status()
esp_err_t espnow_ota_responder_get_status (espnow_ota_status_t * status)
Get the status of the upgrade.
Parameters
[out] status the status of the upgrade
Returns
ESP_OK
ESP_ERR_INVALID_ARG
ESP_ERR_NOT_SUPPORTED
Definition at line 361 of file espnow_ota_responder.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, and status.
espnow_ota_responder_start()
esp_err_t espnow_ota_responder_start (const espnow_ota_config_t * config)
Start upgrading.
Parameters
[in] config upgrade configuration
Returns
ESP_OK
ESP_FAIL _cplusplus
Definition at line 437 of file espnow_ota_responder.c.
References config, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_OTA_DATA, and espnow_set_config_for_data_type().
Referenced by app_espnow_responder(), and app_main().
espnow_ota_responder_stop()
esp_err_t espnow_ota_responder_stop ()
Stop upgrading.
Returns
ESP_OK
ESP_FAIL
Definition at line 371 of file espnow_ota_responder.c.
References CONFIG_ESPNOW_OTA_SECURITY, ESP_ERR_ESPNOW_OTA_STOP, ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_OTA_STATUS, ESPNOW_FRAME_CONFIG_DEFAULT, ESPNOW_OTA_STORE_CONFIG_KEY, ESPNOW_OTA_TYPE_STATUS, espnow_send(), espnow_storage_erase(), and espnow_frame_head_s::security.