Kicker Controller: managed_components/espressif__esp-now/src/utils/src/espnow_storage.c File Reference
espnow_storage.c File Reference
#include "string.h"
#include "stdio.h"
#include "stdlib.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "esp_ota_ops.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
Functions
esp_err_t espnow_storage_init ()
Intialise ESP Storage.
esp_err_t espnow_storage_erase (const char *key)
Erase the information with given key.
esp_err_t espnow_storage_set (const char *key, const void *value, size_t length)
Save the information with given key.
esp_err_t espnow_storage_get (const char *key, void *value, size_t length)
Load the information with given key.
Function Documentation
espnow_storage_erase()
esp_err_t espnow_storage_erase (const char * key)
Erase the information with given key.
Parameters
[in] key the corresponding key of the information that want to erase
Returns
ESP_FAIL
ESP_OK
< Open non-volatile storage with a given namespace from the default NVS partition
If key is CONFIG_ESPNOW_NVS_NAMESPACE, erase all info in CONFIG_ESPNOW_NVS_NAMESPACE
< Close the storage handle and free any allocated resources
Definition at line 63 of file espnow_storage.c.
References CONFIG_ESPNOW_NVS_NAMESPACE, and ESP_ERROR_RETURN.
Referenced by espnow_erase_dec_key(), espnow_erase_key(), and espnow_ota_responder_stop().
espnow_storage_get()
esp_err_t espnow_storage_get (const char * key, void * value, size_t length)
Load the information with given key.
Parameters
[in] key the corresponding key of the information that want to load
[out] value the corresponding value of key
[in] length the length of the value, can be 0 or no less than the value length
Returns
ESP_FAIL
ESP_OK
< Open non-volatile storage with a given namespace from the default NVS partition
< Close the storage handle and free any allocated resources
Definition at line 122 of file espnow_storage.c.
References CONFIG_ESPNOW_NVS_NAMESPACE, ESP_ERROR_RETURN, ESP_PARAM_CHECK, and length.
Referenced by espnow_get_dec_key(), and espnow_get_key().
espnow_storage_init()
esp_err_t espnow_storage_init (void)
Intialise ESP Storage.
Returns
ESP_FAIL
ESP_OK
Definition at line 28 of file espnow_storage.c.
References ESP_ERROR_RETURN.
Referenced by app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), app_main(), and app_main().
espnow_storage_set()
esp_err_t espnow_storage_set (const char * key, const void * value, size_t length)
Save the information with given key.
Parameters
[in] key key name. Maximal length is 15 characters. Shouldn't be empty.
[in] value the value to set
[in] length length of binary value to set, in bytes; Maximum length is 1984 bytes or (508000 bytes or (97.6% of the partition size - 4000) bytes whichever is lower, in case multi-page blob support is enabled).
Returns
ESP_FAIL
ESP_OK
< Open non-volatile storage with a given namespace from the default NVS partition
< set variable length binary value for given key
< Write any pending changes to non-volatile storage
< Close the storage handle and free any allocated resources
Definition at line 95 of file espnow_storage.c.
References CONFIG_ESPNOW_NVS_NAMESPACE, ESP_ERROR_RETURN, ESP_PARAM_CHECK, and length.
Referenced by espnow_ctrl_responder_clear_bindlist(), espnow_ctrl_responder_remove_bindlist(), espnow_ctrl_responder_set_bindlist(), espnow_set_dec_key(), and espnow_set_key().