Kicker Controller: managed_components/espressif__esp-now/src/ota/espnow_ota_responder.c File Reference
espnow_ota_responder.c File Reference
#include <string.h>
#include <stdio.h>
#include "esp_wifi.h"
#include "esp_mac.h"
#include "espnow.h"
#include "espnow_ota.h"
#include "espnow_utils.h"
Classes
struct ota_config_t
Macros
#define ESPNOW_OTA_STORE_CONFIG_KEY "upugrad_config"
#define CONFIG_ESPNOW_OTA_SKIP_VERSION_CHECK
Functions
esp_err_t espnow_ota_responder_get_status (espnow_ota_status_t *status)
Get the status of the upgrade.
esp_err_t espnow_ota_responder_stop ()
Stop upgrading.
esp_err_t espnow_ota_responder_start (const espnow_ota_config_t *config)
Start upgrading.
Macro Definition Documentation
CONFIG_ESPNOW_OTA_SKIP_VERSION_CHECK
#define CONFIG_ESPNOW_OTA_SKIP_VERSION_CHECK
Definition at line 33 of file espnow_ota_responder.c.
ESPNOW_OTA_STORE_CONFIG_KEY
#define ESPNOW_OTA_STORE_CONFIG_KEY "upugrad_config"
Definition at line 32 of file espnow_ota_responder.c.
Referenced by espnow_ota_responder_stop().
Function Documentation
espnow_ota_responder_get_status()
esp_err_t espnow_ota_responder_get_status (espnow_ota_status_t * status)
Get the status of the upgrade.
Parameters
[out] status the status of the upgrade
Returns
ESP_OK
ESP_ERR_INVALID_ARG
ESP_ERR_NOT_SUPPORTED
Definition at line 361 of file espnow_ota_responder.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, and status.
espnow_ota_responder_start()
esp_err_t espnow_ota_responder_start (const espnow_ota_config_t * config)
Start upgrading.
Parameters
[in] config upgrade configuration
Returns
ESP_OK
ESP_FAIL _cplusplus
Definition at line 437 of file espnow_ota_responder.c.
References config, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_OTA_DATA, and espnow_set_config_for_data_type().
Referenced by app_espnow_responder(), and app_main().
espnow_ota_responder_stop()
esp_err_t espnow_ota_responder_stop ()
Stop upgrading.
Returns
ESP_OK
ESP_FAIL
Definition at line 371 of file espnow_ota_responder.c.
References CONFIG_ESPNOW_OTA_SECURITY, ESP_ERR_ESPNOW_OTA_STOP, ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_OTA_STATUS, ESPNOW_FRAME_CONFIG_DEFAULT, ESPNOW_OTA_STORE_CONFIG_KEY, ESPNOW_OTA_TYPE_STATUS, espnow_send(), espnow_storage_erase(), and espnow_frame_head_s::security.