Kicker Controller: managed_components/espressif__esp-now/src/debug/src/espnow_console.c File Reference
espnow_console.c File Reference
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include "esp_system.h"
#include "esp_log.h"
#include "esp_console.h"
#include "esp_vfs_dev.h"
#include "esp_vfs_fat.h"
#include "esp_vfs_cdcacm.h"
#include "esp_vfs_usb_serial_jtag.h"
#include "driver/uart.h"
#include "driver/uart_vfs.h"
#include "driver/usb_serial_jtag.h"
#include "linenoise/linenoise.h"
#include "argtable3/argtable3.h"
#include "espnow_log.h"
#include "espnow.h"
#include "esp_spiffs.h"
#include "espnow_console.h"
Macros
#define PROMPT_STR CONFIG_IDF_TARGET
Functions
esp_err_t espnow_console_init (const espnow_console_config_t *config)
Initialize console module.
esp_err_t espnow_console_deinit ()
De-initialize console module Call this once when done using console module functions.
Macro Definition Documentation
PROMPT_STR
#define PROMPT_STR CONFIG_IDF_TARGET
Definition at line 41 of file espnow_console.c.
Function Documentation
espnow_console_deinit()
esp_err_t espnow_console_deinit (void)
De-initialize console module Call this once when done using console module functions.
Returns
ESP_OK
ESP_FAIL
Definition at line 315 of file espnow_console.c.
References ESP_ERROR_RETURN, ESP_FREE, ESPNOW_DATA_TYPE_DEBUG_COMMAND, and espnow_set_config_for_data_type().
espnow_console_init()
esp_err_t espnow_console_init (const espnow_console_config_t * config)
Initialize console module.
Initialize the console
Register help commands
Initialize filesystem
Create console handle task
Parameters
[in] config pointer to the console configuration structure
Returns
ESP_OK
ESP_FAIL
Definition at line 202 of file espnow_console.c.
References config, CONFIG_ESP_CONSOLE_UART_BAUDRATE, CONFIG_ESP_CONSOLE_UART_NUM, ESPNOW_DATA_TYPE_DEBUG_COMMAND, and espnow_set_config_for_data_type().
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), and app_espnow_responder().