Kicker Controller: managed_components/espressif__esp-now/src/ota/espnow_ota_initiator.c File Reference
espnow_ota_initiator.c File Reference
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include "freertos/timers.h"
#include "freertos/event_groups.h"
#include "freertos/semphr.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "espnow.h"
#include "espnow_ota.h"
#include "espnow_utils.h"
Classes
struct espnow_ota_data_t
Macros
#define CONFIG_ESPNOW_OTA_RETRY_COUNT 50
#define CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL 0
#define CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI -65
#define CONFIG_ESPNOW_OTA_WAIT_RESPONSE_TIMEOUT (10 * 1000)
Functions
esp_err_t espnow_ota_initiator_scan (espnow_ota_responder_t **info_list, size_t *num, TickType_t wait_ticks)
Root scans other nodes.
esp_err_t espnow_ota_initiator_scan_result_free (void)
Free memory in the responder information list.
esp_err_t espnow_ota_initiator_send (const uint8_t addrs_list[][6], size_t addrs_num, const uint8_t sha_256[ESPNOW_OTA_HASH_LEN], size_t size, espnow_ota_initiator_data_cb_t ota_data_cb, espnow_ota_result_t *res)
esp_err_t espnow_ota_initiator_result_free (espnow_ota_result_t *result)
Free memory in the result list.
esp_err_t espnow_ota_initiator_stop ()
Stop root to send firmware to other nodes.
Macro Definition Documentation
CONFIG_ESPNOW_OTA_RETRY_COUNT
#define CONFIG_ESPNOW_OTA_RETRY_COUNT 50
Definition at line 47 of file espnow_ota_initiator.c.
CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI
#define CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI -65
Definition at line 55 of file espnow_ota_initiator.c.
CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL
#define CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL 0
Definition at line 51 of file espnow_ota_initiator.c.
CONFIG_ESPNOW_OTA_WAIT_RESPONSE_TIMEOUT
#define CONFIG_ESPNOW_OTA_WAIT_RESPONSE_TIMEOUT (10 * 1000)
Definition at line 59 of file espnow_ota_initiator.c.
Function Documentation
espnow_ota_initiator_result_free()
esp_err_t espnow_ota_initiator_result_free (espnow_ota_result_t * result)
Free memory in the result list.
Parameters
[in] result pointer to device upgrade status
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 506 of file espnow_ota_initiator.c.
References ESP_FREE, ESP_PARAM_CHECK, espnow_ota_result_s::requested_addr, espnow_ota_result_s::requested_num, espnow_ota_result_s::successed_addr, espnow_ota_result_s::successed_num, espnow_ota_result_s::unfinished_addr, and espnow_ota_result_s::unfinished_num.
Referenced by espnow_ota_initiator_send().
espnow_ota_initiator_scan()
esp_err_t espnow_ota_initiator_scan (espnow_ota_responder_t ** info_list, size_t * num, TickType_t wait_ticks)
Root scans other nodes.
Parameters
[out] info_list responder information list
[out] num responder number
[in] wait_ticks the maximum scanning time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 176 of file espnow_ota_initiator.c.
References CONFIG_ESPNOW_OTA_RETRANSMISSION_TIMES, CONFIG_ESPNOW_OTA_SECURITY, CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI, CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL, ESP_ERROR_GOTO, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_OTA_DATA, ESPNOW_DATA_TYPE_OTA_STATUS, espnow_ota_initiator_scan_result_free(), ESPNOW_OTA_TYPE_REQUEST, espnow_send(), and espnow_set_config_for_data_type().
Referenced by espnow_ota_initiator_send().
espnow_ota_initiator_scan_result_free()
esp_err_t espnow_ota_initiator_scan_result_free (void)
Free memory in the responder information list.
Returns
ESP_OK
Definition at line 214 of file espnow_ota_initiator.c.
References ESP_FREE.
Referenced by espnow_ota_initiator_scan(), and espnow_ota_initiator_send().
espnow_ota_initiator_send()
esp_err_t espnow_ota_initiator_send (const uint8_t addrs_list[][6], size_t addrs_num, const uint8_t sha_256[ESPNOW_OTA_HASH_LEN], size_t size, espnow_ota_initiator_data_cb_t ota_data_cb, espnow_ota_result_t * res)
Request all devices upgrade status.
Read firmware data from Flash to send to unfinished device.
Definition at line 375 of file espnow_ota_initiator.c.
References CONFIG_ESPNOW_OTA_RETRANSMISSION_TIMES, CONFIG_ESPNOW_OTA_RETRY_COUNT, CONFIG_ESPNOW_OTA_SECURITY, CONFIG_ESPNOW_OTA_SEND_FORWARD_RSSI, CONFIG_ESPNOW_OTA_SEND_FORWARD_TTL, espnow_ota_data_t::data, espnow_ota_packet_s::data, ESP_CALLOC, ESP_ERR_ESPNOW_OTA_DEVICE_NO_EXIST, ESP_ERR_ESPNOW_OTA_FIRMWARE_INCOMPLETE, ESP_ERROR_BREAK, ESP_ERROR_CONTINUE, ESP_ERROR_GOTO, ESP_FREE, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_ADDR_GROUP_OTA, ESPNOW_ADDR_IS_BROADCAST, ESPNOW_ADDR_LEN, ESPNOW_DATA_TYPE_OTA_DATA, ESPNOW_DATA_TYPE_OTA_STATUS, ESPNOW_OTA_GET_BITS, ESPNOW_OTA_HASH_LEN, espnow_ota_initiator_result_free(), espnow_ota_initiator_scan(), espnow_ota_initiator_scan_result_free(), ESPNOW_OTA_PACKET_MAX_SIZE, ESPNOW_OTA_PROGRESS_MAX_SIZE, ESPNOW_OTA_TYPE_DATA, ESPNOW_OTA_TYPE_STATUS, espnow_send(), espnow_set_config_for_data_type(), espnow_set_group(), espnow_ota_responder_s::mac, espnow_ota_result_s::requested_num, espnow_ota_packet_s::seq, espnow_ota_packet_s::size, status, espnow_ota_result_s::successed_num, espnow_ota_packet_s::type, espnow_ota_result_s::unfinished_addr, and espnow_ota_result_s::unfinished_num.
espnow_ota_initiator_stop()
esp_err_t espnow_ota_initiator_stop ()
Stop root to send firmware to other nodes.
Returns
ESP_OK
ESP_ERR_NOT_SUPPORTED
Definition at line 520 of file espnow_ota_initiator.c.