Kicker Controller: managed_components/espressif__esp-now/src/debug/include/espnow_log.h File Reference
espnow_log.h File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "esp_log.h"
#include "espnow_mem.h"
#include "espnow_utils.h"
Classes
struct espnow_log_config_s
Log sending configuration.
Macros
#define DEBUG_LOG_PRINTF(fmt, ...)
Configuration of debug log stored in flash. Whether to output information according to the client needs. Please assign CONFIG_ESPNOW_DEBUG_LOG_PRINTF_ENABLE a value.
#define DEBUG_LOG_MALLOC malloc
#define DEBUG_LOG_FREE free
#define CONFIG_ESPNOW_DEBUG_SECURITY 0
#define ESP_EVENT_ESPNOW_LOG_FLASH_FULL (ESP_EVENT_ESPNOW_DEBUG_BASE + 1)
Enumerated list of debug event id.
Typedefs
typedef esp_err_t(* espnow_log_custom_write_cb) (const char *data, size_t size, const char *tag, esp_log_level_t level)
The log callback function.
typedef struct espnow_log_config_s espnow_log_config_t
Log sending configuration.
Functions
esp_err_t espnow_log_get_config (espnow_log_config_t *config)
Get the configuration of the log during wireless debugging.
esp_err_t espnow_log_set_config (const espnow_log_config_t *config)
Set the configuration of the log during wireless debugging.
esp_err_t espnow_log_init (const espnow_log_config_t *config)
Initialize log debug.
esp_err_t espnow_log_deinit (void)
De-initialize log debug Call this once when done using log debug functions.
esp_err_t espnow_log_flash_read (char *data, size_t *size)
Read memory log data in flash.
size_t espnow_log_flash_size (void)
Get the size of log stored in flash.
Macro Definition Documentation
CONFIG_ESPNOW_DEBUG_SECURITY
#define CONFIG_ESPNOW_DEBUG_SECURITY 0
Definition at line 52 of file espnow_log.h.
DEBUG_LOG_FREE
#define DEBUG_LOG_FREE free
Definition at line 46 of file espnow_log.h.
Referenced by __wrap_esp_log_writev(), and espnow_log_deinit().
DEBUG_LOG_MALLOC
#define DEBUG_LOG_MALLOC malloc
Definition at line 45 of file espnow_log.h.
Referenced by __wrap_esp_log_writev().
DEBUG_LOG_PRINTF
#define DEBUG_LOG_PRINTF (fmt, ...)
Configuration of debug log stored in flash. Whether to output information according to the client needs. Please assign CONFIG_ESPNOW_DEBUG_LOG_PRINTF_ENABLE a value.
< _cplusplus
Note
CONFIG_ESPNOW_DEBUG_LOG_PRINTF_ENABLE = 1 enable CONFIG_ESPNOW_DEBUG_LOG_PRINTF_ENABLE = 0 disable
Definition at line 42 of file espnow_log.h.
Referenced by espnow_log_flash_read(), and espnow_log_flash_write().
ESP_EVENT_ESPNOW_LOG_FLASH_FULL
#define ESP_EVENT_ESPNOW_LOG_FLASH_FULL (ESP_EVENT_ESPNOW_DEBUG_BASE + 1)
Enumerated list of debug event id.
Definition at line 59 of file espnow_log.h.
Referenced by espnow_log_flash_write().
Typedef Documentation
espnow_log_config_t
typedef struct espnow_log_config_s espnow_log_config_t
Log sending configuration.
espnow_log_custom_write_cb
typedef esp_err_t(* espnow_log_custom_write_cb) (const char *data, size_t size, const char *tag, esp_log_level_t level)
The log callback function.
Attention
Each time a log is sent, the callback function will be called if defined.
Parameters
[in] data the log data
[in] size the log data size in bytes
[in] tag the log tag
[in] level the log level
Returns
ESP_OK
ESP_FAIL
Definition at line 75 of file espnow_log.h.
Function Documentation
espnow_log_deinit()
esp_err_t espnow_log_deinit (void)
De-initialize log debug Call this once when done using log debug functions.
Returns
ESP_OK
Definition at line 173 of file espnow_log.c.
References log_info::data, DEBUG_LOG_FREE, and espnow_log_flash_deinit().
espnow_log_flash_read()
esp_err_t espnow_log_flash_read (char * data, size_t * size)
Read memory log data in flash.
Parameters
[out] data log data read from the flash's spiffs files
[in,out] size size of the read data in bytes
Returns
ESP_OK
ESP_FAIL
First find Target file index address, then read the this files data
Note
The file address read is different from the file address written, so that the same address can be prevented from being written and read.
Definition at line 274 of file espnow_log_flash.c.
References data_size, DEBUG_LOG_PRINTF, ESP_PARAM_CHECK, LOG_FLASH_FILE_MAX_NUM, LOG_FLASH_STORE_KEY, and log_info::size.
espnow_log_flash_size()
size_t espnow_log_flash_size (void)
Get the size of log stored in flash.
Returns
size _cplusplus
Definition at line 336 of file espnow_log_flash.c.
References LOG_FLASH_FILE_MAX_NUM.
Referenced by espnow_log_flash_write().
espnow_log_get_config()
esp_err_t espnow_log_get_config (espnow_log_config_t * config)
Get the configuration of the log during wireless debugging.
Parameters
[out] config the configuration of the log
Returns
ESP_OK
ESP_FAIL
Definition at line 44 of file espnow_log.c.
References config, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.
espnow_log_init()
esp_err_t espnow_log_init (const espnow_log_config_t * config)
Initialize log debug.
Set log debug configuration
Create the log sendinng task
Parameters
[in] config the configuration of the log
Returns
ESP_OK
Definition at line 142 of file espnow_log.c.
References config, CONFIG_DEBUG_TASK_DEFAULT_PRIOTY, CONFIG_DEBUG_TASK_PINNED_TO_CORE, DEBUG_LOG_QUEUE_SIZE, ESP_CALLOC, ESP_ERROR_RETURN, and espnow_log_flash_init().
Referenced by app_espnow_monitored_device_start(), and app_espnow_responder().
espnow_log_set_config()
esp_err_t espnow_log_set_config (const espnow_log_config_t * config)
Set the configuration of the log during wireless debugging.
Parameters
[in] config the configuration of the log
Returns
ESP_OK
ESP_FAIL
Definition at line 53 of file espnow_log.c.
References config, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.