Kicker Controller: managed_components/espressif__esp-now/src/debug/src/espnow_log.c File Reference
espnow_log.c File Reference
#include "esp_wifi.h"
#include "esp_console.h"
#include "espnow.h"
#include "espnow_log.h"
#include "espnow_log_flash.h"
#include <sys/param.h>
Classes
struct log_info
Macros
#define DEBUG_LOG_STORE_KEY "log_config"
#define DEBUG_LOG_QUEUE_SIZE (16)
#define DEBUG_LOG_TIMEOUT_MS (30 * 1000)
#define DEBUG_LOG_QUEUE_BUFFER_MAX_SIZE (10 * 1024)
#define CONFIG_DEBUG_TASK_DEFAULT_PRIOTY 1
#define CONFIG_DEBUG_TASK_PINNED_TO_CORE 0
#define CONFIG_DEBUG_LOG_MAX_SIZE 1024
Typedefs
typedef struct log_info log_info_t
Functions
esp_err_t espnow_log_get_config (espnow_log_config_t *config)
Get the configuration of the log during wireless debugging.
esp_err_t espnow_log_set_config (const espnow_log_config_t *config)
Set the configuration of the log during wireless debugging.
void __real_esp_log_writev (esp_log_level_t level, const char *tag, const char *format, va_list args)
void __wrap_esp_log_writev (esp_log_level_t level, const char *tag, const char *format, va_list args)
void __wrap_esp_log_write (esp_log_level_t level, const char *tag, const char *format,...)
esp_err_t espnow_log_init (const espnow_log_config_t *config)
Initialize log debug.
esp_err_t espnow_log_deinit ()
De-initialize log debug Call this once when done using log debug functions.
Macro Definition Documentation
CONFIG_DEBUG_LOG_MAX_SIZE
#define CONFIG_DEBUG_LOG_MAX_SIZE 1024
Set log length size
Definition at line 30 of file espnow_log.c.
CONFIG_DEBUG_TASK_DEFAULT_PRIOTY
#define CONFIG_DEBUG_TASK_DEFAULT_PRIOTY 1
Definition at line 28 of file espnow_log.c.
Referenced by espnow_log_init().
CONFIG_DEBUG_TASK_PINNED_TO_CORE
#define CONFIG_DEBUG_TASK_PINNED_TO_CORE 0
Definition at line 29 of file espnow_log.c.
Referenced by espnow_log_init().
DEBUG_LOG_QUEUE_BUFFER_MAX_SIZE
#define DEBUG_LOG_QUEUE_BUFFER_MAX_SIZE (10 * 1024)
Definition at line 26 of file espnow_log.c.
DEBUG_LOG_QUEUE_SIZE
#define DEBUG_LOG_QUEUE_SIZE (16)
Definition at line 24 of file espnow_log.c.
Referenced by espnow_log_init().
DEBUG_LOG_STORE_KEY
#define DEBUG_LOG_STORE_KEY "log_config"
Definition at line 23 of file espnow_log.c.
DEBUG_LOG_TIMEOUT_MS
#define DEBUG_LOG_TIMEOUT_MS (30 * 1000)
Definition at line 25 of file espnow_log.c.
Typedef Documentation
log_info_t
typedef struct log_info log_info_t
Function Documentation
__real_esp_log_writev()
void __real_esp_log_writev (esp_log_level_t level, const char * tag, const char * format, va_list args)
References level, and tag.
Referenced by __wrap_esp_log_writev().
__wrap_esp_log_write()
void __wrap_esp_log_write (esp_log_level_t level, const char * tag, const char * format, ...)
Definition at line 131 of file espnow_log.c.
References level, list, and tag.
__wrap_esp_log_writev()
void __wrap_esp_log_writev (esp_log_level_t level, const char * tag, const char * format, va_list args)
Definition at line 104 of file espnow_log.c.
References __real_esp_log_writev(), log_info::data, DEBUG_LOG_FREE, DEBUG_LOG_MALLOC, level, log_info::level, log_info::size, log_info::tag, and tag.
espnow_log_deinit()
esp_err_t espnow_log_deinit (void)
De-initialize log debug Call this once when done using log debug functions.
Returns
ESP_OK
Definition at line 173 of file espnow_log.c.
References log_info::data, DEBUG_LOG_FREE, and espnow_log_flash_deinit().
espnow_log_get_config()
esp_err_t espnow_log_get_config (espnow_log_config_t * config)
Get the configuration of the log during wireless debugging.
Parameters
[out] config the configuration of the log
Returns
ESP_OK
ESP_FAIL
Definition at line 44 of file espnow_log.c.
References config, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.
espnow_log_init()
esp_err_t espnow_log_init (const espnow_log_config_t * config)
Initialize log debug.
Set log debug configuration
Create the log sendinng task
Parameters
[in] config the configuration of the log
Returns
ESP_OK
Definition at line 142 of file espnow_log.c.
References config, CONFIG_DEBUG_TASK_DEFAULT_PRIOTY, CONFIG_DEBUG_TASK_PINNED_TO_CORE, DEBUG_LOG_QUEUE_SIZE, ESP_CALLOC, ESP_ERROR_RETURN, and espnow_log_flash_init().
Referenced by app_espnow_monitored_device_start(), and app_espnow_responder().
espnow_log_set_config()
esp_err_t espnow_log_set_config (const espnow_log_config_t * config)
Set the configuration of the log during wireless debugging.
Parameters
[in] config the configuration of the log
Returns
ESP_OK
ESP_FAIL
Definition at line 53 of file espnow_log.c.
References config, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.