Kicker Controller: managed_components/espressif__esp-now/src/debug/include/espnow_cmd.h File Reference
espnow_cmd.h File Reference
Functions
void register_espnow (void)
void register_system (void)
void register_wifi (void)
void register_peripherals (void)
void register_iperf (void)
void register_wifi_sniffer ()
void register_sdcard ()
Register sdcard command.
Function Documentation
register_espnow()
void register_espnow (void)
Definition at line 1201 of file cmd_espnow.c.
References register_command(), register_control(), register_ota(), register_provisioning(), and register_scan().
Referenced by espnow_console_commands_register().
register_iperf()
void register_iperf (void)
Definition at line 704 of file cmd_iperf.c.
References register_espnow_config(), and register_espnow_iperf().
Referenced by espnow_console_commands_register().
register_peripherals()
void register_peripherals (void)
Definition at line 182 of file cmd_peripherals.c.
Referenced by espnow_console_commands_register().
register_sdcard()
void register_sdcard ()
Register sdcard command.
Definition at line 76 of file cmd_sdcard.c.
Referenced by espnow_console_commands_register().
register_system()
void register_system (void)
Definition at line 677 of file cmd_system.c.
Referenced by espnow_console_commands_register().
register_wifi()
void register_wifi (void)
Definition at line 508 of file cmd_wifi.c.
References register_wifi_ap(), register_wifi_ping(), and register_wifi_scan().
Referenced by espnow_console_commands_register().
register_wifi_sniffer()
void register_wifi_sniffer ()
Definition at line 374 of file cmd_wifi_sniffer.c.
Referenced by espnow_console_commands_register().