Kicker Controller: managed_components/espressif__esp-now/src/control/include/espnow_ctrl.h File Reference
espnow_ctrl.h File Reference
#include "esp_now.h"
#include "esp_event.h"
#include "espnow.h"
Classes
struct espnow_ctrl_bind_info_s
Bind information from initiator.
struct espnow_ctrl_data_s
Control data from initiator.
Macros
#define ESP_EVENT_ESPNOW_CTRL_BIND (ESP_EVENT_ESPNOW_CTRL_BASE + 0)
Enumerated list of control event id.
#define ESP_EVENT_ESPNOW_CTRL_UNBIND (ESP_EVENT_ESPNOW_CTRL_BASE + 1)
#define ESP_EVENT_ESPNOW_CTRL_BIND_ERROR (ESP_EVENT_ESPNOW_CTRL_BASE + 2)
#define ESPNOW_BIND_LIST_MAX_SIZE 32
Maximum number of device in bind list.
Typedefs
typedef struct espnow_ctrl_bind_info_s espnow_ctrl_bind_info_t
Bind information from initiator.
typedef struct espnow_ctrl_data_s espnow_ctrl_data_t
Control data from initiator.
typedef bool(* espnow_ctrl_bind_cb_t) (espnow_attribute_t initiator_attribute, uint8_t mac[6], int8_t rssi)
The bind callback function.
typedef void(* espnow_ctrl_data_cb_t) (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The control data callback function.
typedef void(* espnow_ctrl_data_raw_cb_t) (espnow_addr_t src_addr, espnow_ctrl_data_t *data, wifi_pkt_rx_ctrl_t *rx_ctrl)
The raw control data callback function.
Enumerations
enum espnow_attribute_t {
ESPNOW_ATTRIBUTE_BASE = 0x0000 , ESPNOW_ATTRIBUTE_POWER = 0x0001 , ESPNOW_ATTRIBUTE_POWER_ADD = 0x0002 , ESPNOW_ATTRIBUTE_ATTRIBUTE = 0x0003 ,
ESPNOW_ATTRIBUTE_LIGHT_BASE = 0x0100 , ESPNOW_ATTRIBUTE_BRIGHTNESS = 0x0101 , ESPNOW_ATTRIBUTE_BRIGHTNESS_ADD = 0x0102 , ESPNOW_ATTRIBUTE_HUE = 0x0103 ,
ESPNOW_ATTRIBUTE_HUE_ADD = 0x0104 , ESPNOW_ATTRIBUTE_SATURATION = 0x0105 , ESPNOW_ATTRIBUTE_SATURATION_ADD = 0x0106 , ESPNOW_ATTRIBUTE_WARM = 0x0107 ,
ESPNOW_ATTRIBUTE_WARM_ADD = 0x0108 , ESPNOW_ATTRIBUTE_COLD = 0x0109 , ESPNOW_ATTRIBUTE_COLD_ADD = 0x010a , ESPNOW_ATTRIBUTE_RED = 0x010b ,
ESPNOW_ATTRIBUTE_RED_ADD = 0x010c , ESPNOW_ATTRIBUTE_GREEN = 0x010d , ESPNOW_ATTRIBUTE_GREEN_ADD = 0x010e , ESPNOW_ATTRIBUTE_BLUE = 0x010f ,
ESPNOW_ATTRIBUTE_BLUE_ADD = 0x0110 , ESPNOW_ATTRIBUTE_MODE = 0x0111 , ESPNOW_ATTRIBUTE_MODE_ADD = 0x0112 , ESPNOW_ATTRIBUTE_BUTTON_BASE = 0x0200 ,
ESPNOW_ATTRIBUTE_KEY_1 = 0x0201 , ESPNOW_ATTRIBUTE_KEY_2 = 0x0202 , ESPNOW_ATTRIBUTE_KEY_3 = 0x0203 , ESPNOW_ATTRIBUTE_KEY_4 = 0x0204 ,
ESPNOW_ATTRIBUTE_KEY_5 = 0x0205 , ESPNOW_ATTRIBUTE_KEY_6 = 0x0206 , ESPNOW_ATTRIBUTE_KEY_7 = 0x0207 , ESPNOW_ATTRIBUTE_KEY_8 = 0x0208 ,
ESPNOW_ATTRIBUTE_KEY_9 = 0x0209 , ESPNOW_ATTRIBUTE_KEY_10 = 0x0210 , ESPNOW_ATTRIBUTE_BATTERY_BASE = 0x0300 , ESPNOW_ATTRIBUTE_STATUS_LOW_BATTERY = 0x0301 ,
ESPNOW_ATTRIBUTE_BATTERY_LEVEL = 0x0302 , ESPNOW_ATTRIBUTE_CHARGING_STATE = 0x0303
}
Control attribute. The high byte is device type, the low byte is device attribute.
enum espnow_ctrl_bind_error_t { ESPNOW_BIND_ERROR_NONE , ESPNOW_BIND_ERROR_TIMEOUT , ESPNOW_BIND_ERROR_RSSI , ESPNOW_BIND_ERROR_LIST_FULL }
Functions
esp_err_t espnow_ctrl_initiator_bind (espnow_attribute_t initiator_attribute, bool enable)
The initiator sends a broadcast bind frame.
esp_err_t espnow_ctrl_initiator_send (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The initiator sends a broadcast control data frame.
esp_err_t espnow_ctrl_responder_bind (uint32_t wait_ms, int8_t rssi, espnow_ctrl_bind_cb_t cb)
The responder creates a bind task to process the received bind frame.
esp_err_t espnow_ctrl_responder_data (espnow_ctrl_data_cb_t cb)
The responder registers control data callback function.
esp_err_t espnow_ctrl_responder_get_bindlist (espnow_ctrl_bind_info_t *list, size_t *size)
The responder gets bound list.
esp_err_t espnow_ctrl_responder_set_bindlist (const espnow_ctrl_bind_info_t *info)
The responder sets bound list.
esp_err_t espnow_ctrl_responder_remove_bindlist (const espnow_ctrl_bind_info_t *info)
The responder removes bound list.
esp_err_t espnow_ctrl_responder_clear_bindlist (void)
Remove all bound devices from bindlist.
esp_err_t espnow_ctrl_send (const espnow_addr_t dest_addr, const espnow_ctrl_data_t *data, const espnow_frame_head_t *frame_head, TickType_t wait_ticks)
Send control data frame.
esp_err_t espnow_ctrl_recv (espnow_ctrl_data_raw_cb_t cb)
The responder registers raw control data callback function.
Macro Definition Documentation
ESP_EVENT_ESPNOW_CTRL_BIND
#define ESP_EVENT_ESPNOW_CTRL_BIND (ESP_EVENT_ESPNOW_CTRL_BASE + 0)
Enumerated list of control event id.
< _cplusplus
Definition at line 21 of file espnow_ctrl.h.
ESP_EVENT_ESPNOW_CTRL_BIND_ERROR
#define ESP_EVENT_ESPNOW_CTRL_BIND_ERROR (ESP_EVENT_ESPNOW_CTRL_BASE + 2)
Definition at line 23 of file espnow_ctrl.h.
ESP_EVENT_ESPNOW_CTRL_UNBIND
#define ESP_EVENT_ESPNOW_CTRL_UNBIND (ESP_EVENT_ESPNOW_CTRL_BASE + 1)
Definition at line 22 of file espnow_ctrl.h.
ESPNOW_BIND_LIST_MAX_SIZE
#define ESPNOW_BIND_LIST_MAX_SIZE 32
Maximum number of device in bind list.
Definition at line 28 of file espnow_ctrl.h.
Referenced by espnow_ctrl_responder_clear_bindlist().
Typedef Documentation
espnow_ctrl_bind_cb_t
typedef bool(* espnow_ctrl_bind_cb_t) (espnow_attribute_t initiator_attribute, uint8_t mac[6], int8_t rssi)
The bind callback function.
Attention
Each time a bind frame is received, the callback function will be called.
Parameters
[in] initiator_attribute initiator attribute
[in] mac initiator mac address
[in] rssi rssi of bind information
Returns
TRUE
FALSE
Definition at line 132 of file espnow_ctrl.h.
espnow_ctrl_bind_info_t
typedef struct espnow_ctrl_bind_info_s espnow_ctrl_bind_info_t
Bind information from initiator.
espnow_ctrl_data_cb_t
typedef void(* espnow_ctrl_data_cb_t) (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The control data callback function.
Parameters
[in] initiator_attribute the received initiator's attribute
[in] responder_attribute the received responder's attribute
[in] responder_value the received responder value
Definition at line 142 of file espnow_ctrl.h.
espnow_ctrl_data_raw_cb_t
typedef void(* espnow_ctrl_data_raw_cb_t) (espnow_addr_t src_addr, espnow_ctrl_data_t *data, wifi_pkt_rx_ctrl_t *rx_ctrl)
The raw control data callback function.
Parameters
[in] src_addr MAC address of sender
[in] data control data from sender
[in] rx_ctrl received packet radio metadata header
Definition at line 154 of file espnow_ctrl.h.
espnow_ctrl_data_t
typedef struct espnow_ctrl_data_s espnow_ctrl_data_t
Control data from initiator.
Enumeration Type Documentation
espnow_attribute_t
enum espnow_attribute_t
Control attribute. The high byte is device type, the low byte is device attribute.
Enumerator
ESPNOW_ATTRIBUTE_BASE
ESPNOW_ATTRIBUTE_POWER
ESPNOW_ATTRIBUTE_POWER_ADD
ESPNOW_ATTRIBUTE_ATTRIBUTE
light
ESPNOW_ATTRIBUTE_LIGHT_BASE
ESPNOW_ATTRIBUTE_BRIGHTNESS
ESPNOW_ATTRIBUTE_BRIGHTNESS_ADD
ESPNOW_ATTRIBUTE_HUE
ESPNOW_ATTRIBUTE_HUE_ADD
ESPNOW_ATTRIBUTE_SATURATION
ESPNOW_ATTRIBUTE_SATURATION_ADD
ESPNOW_ATTRIBUTE_WARM
ESPNOW_ATTRIBUTE_WARM_ADD
ESPNOW_ATTRIBUTE_COLD
ESPNOW_ATTRIBUTE_COLD_ADD
ESPNOW_ATTRIBUTE_RED
ESPNOW_ATTRIBUTE_RED_ADD
ESPNOW_ATTRIBUTE_GREEN
ESPNOW_ATTRIBUTE_GREEN_ADD
ESPNOW_ATTRIBUTE_BLUE
ESPNOW_ATTRIBUTE_BLUE_ADD
ESPNOW_ATTRIBUTE_MODE
ESPNOW_ATTRIBUTE_MODE_ADD
button
ESPNOW_ATTRIBUTE_BUTTON_BASE
ESPNOW_ATTRIBUTE_KEY_1
ESPNOW_ATTRIBUTE_KEY_2
ESPNOW_ATTRIBUTE_KEY_3
ESPNOW_ATTRIBUTE_KEY_4
ESPNOW_ATTRIBUTE_KEY_5
ESPNOW_ATTRIBUTE_KEY_6
ESPNOW_ATTRIBUTE_KEY_7
ESPNOW_ATTRIBUTE_KEY_8
ESPNOW_ATTRIBUTE_KEY_9
ESPNOW_ATTRIBUTE_KEY_10
battery
ESPNOW_ATTRIBUTE_BATTERY_BASE
ESPNOW_ATTRIBUTE_STATUS_LOW_BATTERY
ESPNOW_ATTRIBUTE_BATTERY_LEVEL
ESPNOW_ATTRIBUTE_CHARGING_STATE
Definition at line 34 of file espnow_ctrl.h.
espnow_ctrl_bind_error_t
enum espnow_ctrl_bind_error_t
Enumerator
ESPNOW_BIND_ERROR_NONE
ESPNOW_BIND_ERROR_TIMEOUT
ESPNOW_BIND_ERROR_RSSI
ESPNOW_BIND_ERROR_LIST_FULL
Definition at line 82 of file espnow_ctrl.h.
Function Documentation
espnow_ctrl_initiator_bind()
esp_err_t espnow_ctrl_initiator_bind (espnow_attribute_t initiator_attribute, bool enable)
The initiator sends a broadcast bind frame.
Parameters
[in] initiator_attribute initiator attribute
[in] enable bind or unbind
Returns
TRUE
FALSE
Definition at line 467 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_BIND, espnow_send(), and espnow_frame_head_s::forward_ttl.
espnow_ctrl_initiator_send()
esp_err_t espnow_ctrl_initiator_send (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The initiator sends a broadcast control data frame.
Parameters
[in] initiator_attribute the sending initiator's attribute
[in] responder_attribute the sending responder's attribute
[in] responder_value the sending responder value
Returns
ESP_OK: succeed
others: fail
Definition at line 486 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_send(), responder_attribute, and responder_value.
espnow_ctrl_recv()
esp_err_t espnow_ctrl_recv (espnow_ctrl_data_raw_cb_t cb)
The responder registers raw control data callback function.
Parameters
[in] cb the raw control data callback function
Returns
ESP_OK: succeed
others: fail _cplusplus
Definition at line 520 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_set_config_for_data_type(), and g_data_raw_cb.
espnow_ctrl_responder_bind()
esp_err_t espnow_ctrl_responder_bind (uint32_t wait_ms, int8_t rssi, espnow_ctrl_bind_cb_t cb)
The responder creates a bind task to process the received bind frame.
Attention
The bind frame will be processed if the callback function returns true and wait time is not timeout, and bind frame's RSSI is higher than the set RSSI.
The responder will bind or unbind with the sender according to the value in bind frame.
Parameters
[in] wait_ms maximum waiting bind time in millisecond
[in] rssi the minimum bind frame RSSI
[in] cb the bind callback function
Returns
ESP_OK: succeed
others: fail
Definition at line 285 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_BIND, espnow_set_config_for_data_type(), g_bind_cb, g_rssi, g_timestamp, and rssi.
espnow_ctrl_responder_clear_bindlist()
esp_err_t espnow_ctrl_responder_clear_bindlist (void)
Remove all bound devices from bindlist.
Returns
ESP_OK: succeed
others: fail
Definition at line 161 of file espnow_ctrl.c.
References ESPNOW_BIND_LIST_MAX_SIZE, and espnow_storage_set().
espnow_ctrl_responder_data()
esp_err_t espnow_ctrl_responder_data (espnow_ctrl_data_cb_t cb)
The responder registers control data callback function.
Parameters
[in] cb the control data callback function
Returns
ESP_OK: succeed
others: fail
Definition at line 333 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_set_config_for_data_type(), and g_data_cb.
espnow_ctrl_responder_get_bindlist()
esp_err_t espnow_ctrl_responder_get_bindlist (espnow_ctrl_bind_info_t * list, size_t * size)
The responder gets bound list.
Parameters
[out] list the buffer that stores the bound list
[in,out] size input maximum bound list size, output the real bound list size
Returns
ESP_OK: succeed
others: fail
Definition at line 116 of file espnow_ctrl.c.
References list.
espnow_ctrl_responder_remove_bindlist()
esp_err_t espnow_ctrl_responder_remove_bindlist (const espnow_ctrl_bind_info_t * info)
The responder removes bound list.
Attention
The bound information will be removed from flash
Parameters
[in] info the bound information to be removed
Returns
ESP_OK: succeed
others: fail
Definition at line 141 of file espnow_ctrl.c.
References espnow_storage_set(), and info.
espnow_ctrl_responder_set_bindlist()
esp_err_t espnow_ctrl_responder_set_bindlist (const espnow_ctrl_bind_info_t * info)
The responder sets bound list.
Attention
The bound information will be stored to flash
Parameters
[in] info the bound information to be set
Returns
ESP_OK: succeed
others: fail
Definition at line 129 of file espnow_ctrl.c.
References espnow_storage_set(), and info.
espnow_ctrl_send()
esp_err_t espnow_ctrl_send (const espnow_addr_t dest_addr, const espnow_ctrl_data_t * data, const espnow_frame_head_t * frame_head, TickType_t wait_ticks)
Send control data frame.
Parameters
[in] dest_addr dest_addr is not used
[in] data control data
[in] frame_head frame header must not be NULL
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK: succeed
others: fail
Definition at line 505 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_send(), espnow_ctrl_data_s::responder_value_s_flag, and espnow_ctrl_data_s::responder_value_s_size.