Kicker Controller: managed_components/espressif__esp-now/src/espnow/src/espnow_group.c File Reference
espnow_group.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/queue.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_wifi.h"
#include "esp_now.h"
#include "esp_log.h"
#include "espnow.h"
#include "esp_crc.h"
Classes
struct espnow_group_item
Typedefs
typedef struct espnow_group_item espnow_group_item_t
Functions
esp_err_t espnow_del_group (const espnow_group_t group_id)
Delete group ID addresses.
int espnow_get_group_num (void)
Get the number of group ID addresses.
esp_err_t espnow_get_group_list (espnow_group_t group_id_list[], size_t num)
bool espnow_is_my_group (const espnow_group_t group_id)
Check whether the specified group address is my group.
Typedef Documentation
espnow_group_item_t
typedef struct espnow_group_item espnow_group_item_t
Function Documentation
espnow_del_group()
esp_err_t espnow_del_group (const espnow_group_t group_id)
Delete group ID addresses.
Parameters
[in] group_id pointer to deleted group ID address
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 62 of file espnow_group.c.
References ESP_FREE, and espnow_group_item::id.
Referenced by espnow_recv_cb().
espnow_get_group_list()
esp_err_t espnow_get_group_list (espnow_group_t group_id_list[], size_t num)
Definition at line 89 of file espnow_group.c.
References espnow_group_item::id.
espnow_get_group_num()
int espnow_get_group_num (void)
Get the number of group ID addresses.
Returns
the number of group ID addresses
Definition at line 77 of file espnow_group.c.
References count.
Referenced by espnow_recv_cb().
espnow_is_my_group()
bool espnow_is_my_group (const espnow_group_t group_id)
Check whether the specified group address is my group.
Parameters
[in] group_id pointer to the specified group ID addresses
Returns
true/false
Definition at line 105 of file espnow_group.c.
References espnow_group_item::id.
Referenced by espnow_recv_cb().