Kicker Controller: managed_components/espressif__esp-now/src/espnow/src/espnow.c File Reference
espnow.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/param.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_wifi.h"
#include "esp_sleep.h"
#include "esp_now.h"
#include "esp_log.h"
#include "espnow.h"
#include "esp_crc.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "espnow_security.h"
Classes
struct espnow_group_info_t
struct __attribute__
HID Descriptor.
struct espnow_pkt_t
Receive data packet temporarily store in queue.
struct espnow_event_ctx_t
struct espnow_recv_handle
Macros
#define SEND_CB_OK BIT0
#define SEND_CB_FAIL BIT1
#define ESPNOW_MSG_CACHE 32
#define ESPNOW_VERSION 2
#define SEND_DELAY_UNIT_MSECS 2
Typedefs
typedef struct espnow_recv_handle espnow_recv_handle_t
Enumerations
enum espnow_msg_id_t {
ESPNOW_EVENT_SEND_ACK , ESPNOW_EVENT_RECV_ACK , ESPNOW_EVENT_FORWARD , ESPNOW_EVENT_RECEIVE ,
ESPNOW_EVENT_STOP
}
Functions
ESP_EVENT_DEFINE_BASE (ESP_EVENT_ESPNOW)
void espnow_recv_cb (const esp_now_recv_info_t *recv_info, const uint8_t *data, int size)
void espnow_send_cb (const uint8_t *addr, esp_now_send_status_t status)
esp_err_t espnow_add_peer (const espnow_addr_t addr, const uint8_t *lmk)
When used for unicast, add the target device.
esp_err_t espnow_del_peer (const espnow_addr_t addr)
When used for unicast, delete the target device.
esp_err_t espnow_send (espnow_data_type_t type, const espnow_addr_t dest_addr, const void *data, size_t size, const espnow_frame_head_t *data_head, TickType_t wait_ticks)
Send ESP-NOW data.
esp_err_t espnow_set_group (const uint8_t addrs_list[][ESPNOW_ADDR_LEN], size_t addrs_num, const uint8_t group_id[ESPNOW_ADDR_LEN], espnow_frame_head_t *data_head, bool type, TickType_t wait_ticks)
esp_err_t espnow_init (const espnow_config_t *config)
Initialize ESP-NOW function.
esp_err_t espnow_deinit (void)
De-initialize ESP-NOW function.
esp_err_t espnow_set_config_for_data_type (espnow_data_type_t type, bool enable, handler_for_data_t handle)
Set configuration when receiving the corresponding ESP-NOW data type Include: Set to enable/disable handling the corresponding ESP-NOW data type Set the callback function when receiving the corresponding ESP-NOW data type.
esp_err_t espnow_get_config_for_data_type (espnow_data_type_t type, bool *enable)
Get the configuration that whether to handle the corresponding ESP-NOW data type.
esp_err_t espnow_set_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
esp_err_t espnow_get_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
esp_err_t espnow_erase_key (void)
Erase the security key info stored in flash.
esp_err_t espnow_set_dec_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
esp_err_t espnow_get_dec_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
esp_err_t espnow_erase_dec_key (void)
Erase the security key info stored in flash.
Variables
g_msg_magic_sec_cache [ESPNOW_MSG_CACHE] = {0}
const espnow_addr_t ESPNOW_ADDR_NONE = {0}
const espnow_addr_t ESPNOW_ADDR_BROADCAST = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0XFF}
const espnow_group_t ESPNOW_ADDR_GROUP_OTA = {'O', 'T', 'A', 0x0, 0x0, 0x0}
const espnow_group_t ESPNOW_ADDR_GROUP_PROV = {'P', 'R', 'O', 'V', 0x0, 0x0}
const espnow_group_t ESPNOW_ADDR_GROUP_SEC = {'S', 'E', 'C', 0x0, 0x0, 0x0}
wifi_country_t g_self_country = {0}
Macro Definition Documentation
ESPNOW_MSG_CACHE
#define ESPNOW_MSG_CACHE 32
Definition at line 35 of file espnow.c.
Referenced by espnow_recv_cb().
ESPNOW_VERSION
#define ESPNOW_VERSION 2
Definition at line 38 of file espnow.c.
Referenced by espnow_init(), espnow_recv_cb(), espnow_send(), and espnow_set_group().
SEND_CB_FAIL
#define SEND_CB_FAIL BIT1
Definition at line 33 of file espnow.c.
Referenced by espnow_send(), and espnow_send_cb().
SEND_CB_OK
#define SEND_CB_OK BIT0
Definition at line 32 of file espnow.c.
Referenced by espnow_send(), and espnow_send_cb().
SEND_DELAY_UNIT_MSECS
#define SEND_DELAY_UNIT_MSECS 2
Definition at line 43 of file espnow.c.
Typedef Documentation
espnow_recv_handle_t
typedef struct espnow_recv_handle espnow_recv_handle_t
Enumeration Type Documentation
espnow_msg_id_t
enum espnow_msg_id_t
Enumerator
ESPNOW_EVENT_SEND_ACK
ESPNOW_EVENT_RECV_ACK
ESPNOW_EVENT_FORWARD
ESPNOW_EVENT_RECEIVE
ESPNOW_EVENT_STOP
Definition at line 100 of file espnow.c.
Function Documentation
ESP_EVENT_DEFINE_BASE()
ESP_EVENT_DEFINE_BASE (ESP_EVENT_ESPNOW)
espnow_add_peer()
esp_err_t espnow_add_peer (const espnow_addr_t addr, const uint8_t * lmk)
When used for unicast, add the target device.
Parameters
[in] addr peer MAC address
[in] lmk peer local master key that is used to encrypt data. It can be null or ESP_NOW_KEY_LEN length data
< If peer exists, delete a peer from peer list
< Add a peer to peer list
Definition at line 422 of file espnow.c.
References addr, ESP_ERROR_RETURN, and ESP_PARAM_CHECK.
Referenced by espnow_init(), and espnow_prov_initiator_send().
espnow_deinit()
esp_err_t espnow_deinit (void)
De-initialize ESP-NOW function.
Returns
ESP_OK
ESP_ERR_ESPNOW_NOT_INIT
< De-initialize ESPNOW function
Definition at line 1102 of file espnow.c.
References ESP_ERROR_RETURN, ESP_FREE, ESPNOW_DATA_TYPE_MAX, ESPNOW_EVENT_STOP, and espnow_sec_deinit().
espnow_del_peer()
esp_err_t espnow_del_peer (const espnow_addr_t addr)
When used for unicast, delete the target device.
Parameters
[in] addr MAC address
Returns
ESP_OK
ESP_ERR_INVALID_ARG
< If peer exists, delete a peer from peer list
Definition at line 450 of file espnow.c.
References addr, ESP_ERROR_RETURN, ESP_PARAM_CHECK, and ESPNOW_ADDR_IS_BROADCAST.
Referenced by espnow_prov_initiator_send().
espnow_erase_dec_key()
esp_err_t espnow_erase_dec_key (void)
Erase the security key info stored in flash.
ESP_OK
ESP_ERR_NVS_NOT_FOUND _cplusplus
Definition at line 1250 of file espnow.c.
References APP_KEY_LEN, and espnow_storage_erase().
espnow_erase_key()
esp_err_t espnow_erase_key (void)
Erase the security key info stored in flash.
ESP_OK
ESP_ERR_NVS_NOT_FOUND
Definition at line 1208 of file espnow.c.
References APP_KEY_LEN, and espnow_storage_erase().
espnow_get_config_for_data_type()
esp_err_t espnow_get_config_for_data_type (espnow_data_type_t type, bool * enable)
Get the configuration that whether to handle the corresponding ESP-NOW data type.
Parameters
[in] type data type defined by espnow_data_type_t
[out] enable store the current receiving status of this data type
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1164 of file espnow.c.
References ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_MAX, and type.
espnow_get_dec_key()
esp_err_t espnow_get_dec_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
Parameters
[out] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1233 of file espnow.c.
References APP_KEY_LEN, ESP_PARAM_CHECK, and espnow_storage_get().
espnow_get_key()
esp_err_t espnow_get_key (uint8_t key_info[APP_KEY_LEN])
Get the security key info stored in flash If no security key info is stored in flash, the function will return failed.
Parameters
[out] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1191 of file espnow.c.
References APP_KEY_LEN, ESP_PARAM_CHECK, and espnow_storage_get().
Referenced by app_espnow_responder(), app_main(), and espnow_send().
espnow_init()
esp_err_t espnow_init (const espnow_config_t * config)
Initialize ESP-NOW function.
Parameters
[in] config configuration of ESP-NOW
Returns
ESP_OK
ESP_FAIL
< Event group for espnow sent cb
Definition at line 1041 of file espnow.c.
References config, ESP_ERROR_RETURN, ESP_MALLOC, ESP_PARAM_CHECK, espnow_add_peer(), ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_MAX, espnow_recv_cb(), espnow_sec_init(), espnow_send_cb(), ESPNOW_VERSION, and g_self_country.
Referenced by app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), app_main(), and app_main().
espnow_recv_cb()
void espnow_recv_cb (const esp_now_recv_info_t * recv_info, const uint8_t * data, int size)
callback function of sending ESPNOW data
< Filter ESP-NOW packets not generated by this project
< Data does not need to be forwarded
Definition at line 177 of file espnow.c.
References espnow_frame_head_s::ack, addr, espnow_group_info_t::addrs_list, espnow_group_info_t::addrs_num, espnow_frame_head_s::broadcast, espnow_frame_head_s::channel, espnow_pkt_t::data, ESP_CALLOC, ESP_FREE, ESP_MALLOC, espnow_add_group(), ESPNOW_ADDR_IS_BROADCAST, ESPNOW_ADDR_IS_SELF, ESPNOW_ADDR_LEN, ESPNOW_CHANNEL_ALL, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_GROUP, ESPNOW_DATA_TYPE_MAX, espnow_del_group(), ESPNOW_EVENT_FORWARD, ESPNOW_EVENT_RECEIVE, ESPNOW_EVENT_RECV_ACK, ESPNOW_EVENT_SEND_ACK, ESPNOW_FORWARD_MAX_COUNT, espnow_get_group_num(), espnow_is_my_group(), ESPNOW_MSG_CACHE, ESPNOW_VERSION, espnow_frame_head_s::filter_adjacent_channel, espnow_frame_head_s::filter_weak_signal, espnow_frame_head_s::forward_rssi, espnow_frame_head_s::forward_ttl, g_msg_magic_sec_cache, espnow_frame_head_s::group, espnow_group_info_t::group_id, espnow_frame_head_s::magic, magic, espnow_pkt_t::rx_ctrl, espnow_frame_head_s::security, espnow_group_info_t::type, and type.
Referenced by espnow_init().
espnow_send()
esp_err_t espnow_send (espnow_data_type_t type, const espnow_addr_t dest_addr, const void * data, size_t size, const espnow_frame_head_t * frame_config, TickType_t wait_ticks)
Send ESP-NOW data.
Parameters
[in] type ESP-NOW data type defined by espnow_data_type_t
[in] dest_addr destination mac address
[in] data the sending data which must not be NULL
[in] size the maximum length of data, must be no more than ESPNOW_DATA_LEN
[in] frame_config if frame_config is NULL, Use ESPNOW_FRAME_CONFIG_DEFAULT configuration
[in] wait_ticks the maximum sending time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
ESP_ERR_TIMEOUT
ESP_ERR_WIFI_TIMEOUT
< Wait for other tasks to be sent before send ESP-NOW data
Definition at line 523 of file espnow.c.
References ack, espnow_frame_head_s::ack, addr, APP_KEY_LEN, espnow_frame_head_s::broadcast, espnow_frame_head_s::channel, count, ESP_ERROR_CONTINUE, ESP_ERROR_GOTO, ESP_ERROR_RETURN, ESP_FREE, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_ADDR_BROADCAST, ESPNOW_ADDR_IS_BROADCAST, ESPNOW_CHANNEL_ALL, ESPNOW_DATA_LEN, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_FORWARD, ESPNOW_DATA_TYPE_MAX, ESPNOW_DATA_TYPE_SECURITY, ESPNOW_DATA_TYPE_SECURITY_STATUS, espnow_get_key(), espnow_sec_auth_encrypt(), ESPNOW_SEC_OVER, espnow_set_key(), ESPNOW_VERSION, espnow_frame_head_s::forward_rssi, g_self_country, IV_LEN, KEY_LEN, espnow_frame_head_s::magic, espnow_frame_head_s::retransmit_count, espnow_frame_head_s::security, SEND_CB_FAIL, SEND_CB_OK, and type.
Referenced by espnow_ctrl_initiator_bind(), espnow_ctrl_initiator_send(), espnow_ctrl_send(), espnow_ota_initiator_scan(), espnow_ota_initiator_send(), espnow_ota_responder_stop(), espnow_prov_initiator_send(), and espnow_sec_initiator_scan().
espnow_send_cb()
void espnow_send_cb (const uint8_t * addr, esp_now_send_status_t status)
Definition at line 404 of file espnow.c.
References addr, SEND_CB_FAIL, SEND_CB_OK, and status.
Referenced by espnow_init().
espnow_set_config_for_data_type()
esp_err_t espnow_set_config_for_data_type (espnow_data_type_t type, bool enable, handler_for_data_t handle)
Set configuration when receiving the corresponding ESP-NOW data type Include: Set to enable/disable handling the corresponding ESP-NOW data type Set the callback function when receiving the corresponding ESP-NOW data type.
Parameters
[in] type data type defined by espnow_data_type_t
[in] enable enable or disable the receive of data type, false - disable, true - enable
[in] handle the receive callback function for data type
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1146 of file espnow.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_ACK, ESPNOW_DATA_TYPE_MAX, and type.
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_main(), espnow_console_deinit(), espnow_console_init(), espnow_ctrl_recv(), espnow_ctrl_responder_bind(), espnow_ctrl_responder_data(), espnow_ota_initiator_scan(), espnow_ota_initiator_send(), espnow_ota_responder_start(), espnow_prov_initiator_scan(), espnow_prov_initiator_send(), espnow_prov_responder_start(), espnow_sec_initiator_scan(), and espnow_sec_initiator_start().
espnow_set_dec_key()
esp_err_t espnow_set_dec_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
Attention
Set sec_enable in espnow_config to true when ESP-NOW initializes, or the function will return failed.
Parameters
[in] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1215 of file espnow.c.
References APP_KEY_LEN, ESP_ERROR_RETURN, ESP_PARAM_CHECK, espnow_sec_setkey(), espnow_storage_set(), and KEY_LEN.
Referenced by app_espnow_responder(), and app_main().
espnow_set_group()
esp_err_t espnow_set_group (const uint8_t addrs_list[][ESPNOW_ADDR_LEN], size_t addrs_num, const uint8_t group_id[ESPNOW_ADDR_LEN], espnow_frame_head_t * data_head, bool type, TickType_t wait_ticks)
Definition at line 714 of file espnow.c.
References espnow_group_info_t::addrs_list, espnow_group_info_t::addrs_num, espnow_frame_head_s::channel, count, ESP_ERROR_CONTINUE, ESP_ERROR_GOTO, ESP_FREE, ESP_MALLOC, ESPNOW_ADDR_BROADCAST, ESPNOW_ADDR_LEN, ESPNOW_CHANNEL_ALL, ESPNOW_DATA_TYPE_GROUP, ESPNOW_PAYLOAD_LEN, ESPNOW_VERSION, g_self_country, espnow_group_info_t::group_id, espnow_frame_head_s::magic, espnow_frame_head_s::retransmit_count, espnow_group_info_t::type, and type.
espnow_set_key()
esp_err_t espnow_set_key (uint8_t key_info[APP_KEY_LEN])
Set the security key info The security key info is used to derive key and stored to flash. The derived key is used to encrypt ESP-NOW data payload when send and decrypt ESP-NOW data payload when receive.
Attention
Set sec_enable in espnow_config to true when ESP-NOW initializes, or the function will return failed.
Parameters
[in] key_info security key info
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 1173 of file espnow.c.
References APP_KEY_LEN, ESP_ERROR_RETURN, ESP_PARAM_CHECK, espnow_sec_setkey(), espnow_storage_set(), and KEY_LEN.
Referenced by app_espnow_responder(), app_main(), and espnow_send().
Variable Documentation
ESPNOW_ADDR_BROADCAST
const espnow_addr_t ESPNOW_ADDR_BROADCAST = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0XFF}
Definition at line 133 of file espnow.c.
Referenced by espnow_ctrl_initiator_bind(), espnow_ctrl_initiator_send(), espnow_ctrl_send(), espnow_init(), espnow_ota_initiator_scan(), espnow_ota_responder_stop(), espnow_sec_initiator_scan(), espnow_send(), and espnow_set_group().
ESPNOW_ADDR_GROUP_OTA
const espnow_group_t ESPNOW_ADDR_GROUP_OTA = {'O', 'T', 'A', 0x0, 0x0, 0x0}
Definition at line 134 of file espnow.c.
Referenced by espnow_ota_initiator_send().
ESPNOW_ADDR_GROUP_PROV
const espnow_group_t ESPNOW_ADDR_GROUP_PROV = {'P', 'R', 'O', 'V', 0x0, 0x0}
Definition at line 135 of file espnow.c.
ESPNOW_ADDR_GROUP_SEC
const espnow_group_t ESPNOW_ADDR_GROUP_SEC = {'S', 'E', 'C', 0x0, 0x0, 0x0}
Definition at line 136 of file espnow.c.
ESPNOW_ADDR_NONE
const espnow_addr_t ESPNOW_ADDR_NONE = {0}
Definition at line 132 of file espnow.c.
g_msg_magic_sec_cache
g_msg_magic_sec_cache[ESPNOW_MSG_CACHE] = {0}
Definition at line 129 of file espnow.c.
Referenced by espnow_recv_cb().
g_self_country
wifi_country_t g_self_country = {0}
Definition at line 140 of file espnow.c.
Referenced by espnow_init(), espnow_send(), and espnow_set_group().
magic
uint16_t magic
Definition at line 128 of file espnow.c.
Referenced by espnow_recv_cb().
type
uint8_t type
Definition at line 127 of file espnow.c.