Kicker Controller: managed_components/espressif__esp-now/src/security/include/espnow_security_handshake.h File Reference
espnow_security_handshake.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "espnow.h"
#include "espnow_utils.h"
Classes
struct espnow_sec_info_s
Security information.
struct espnow_sec_responder_s
Responder security information.
struct espnow_sec_packet_s
Handshake packet.
struct espnow_sec_result_s
List of device status during the security process.
Typedefs
typedef struct espnow_sec_info_s espnow_sec_info_t
Security information.
typedef struct espnow_sec_responder_s espnow_sec_responder_t
Responder security information.
typedef struct espnow_sec_packet_s espnow_sec_packet_t
Handshake packet.
typedef struct espnow_sec_result_s espnow_sec_result_t
List of device status during the security process.
Enumerations
enum espnow_sec_type_t {
ESPNOW_SEC_TYPE_REQUEST , ESPNOW_SEC_TYPE_INFO , ESPNOW_SEC_TYPE_HANDSHAKE , ESPNOW_SEC_TYPE_KEY ,
ESPNOW_SEC_TYPE_KEY_RESP , ESPNOW_SEC_TYPE_REST
}
Type of packet.
enum espnow_sec_ver_type_t { ESPNOW_SEC_VER_NONE , ESPNOW_SEC_VER_V1_0 , ESPNOW_SEC_VER_V1_1 }
Security version.
Functions
esp_err_t espnow_sec_initiator_scan (espnow_sec_responder_t **info_list, size_t *num, TickType_t wait_ticks)
Root scans other node info.
esp_err_t espnow_sec_initiator_scan_result_free (void)
Free memory in the scan information list.
esp_err_t espnow_sec_initiator_start (uint8_t key_info[APP_KEY_LEN], const char *pop_data, const uint8_t addrs_list[][6], size_t addrs_num, espnow_sec_result_t *res)
Root sends security to other nodes.
esp_err_t espnow_sec_initiator_stop ()
Stop Root to send security to other nodes.
esp_err_t espnow_sec_initiator_result_free (espnow_sec_result_t *result)
Free memory in the results list.
esp_err_t espnow_sec_responder_start (const char *pop_data)
Start security process.
esp_err_t espnow_sec_responder_stop ()
Stop security process.
Typedef Documentation
espnow_sec_info_t
typedef struct espnow_sec_info_s espnow_sec_info_t
Security information.
espnow_sec_packet_t
typedef struct espnow_sec_packet_s espnow_sec_packet_t
Handshake packet.
espnow_sec_responder_t
typedef struct espnow_sec_responder_s espnow_sec_responder_t
Responder security information.
espnow_sec_result_t
typedef struct espnow_sec_result_s espnow_sec_result_t
List of device status during the security process.
Enumeration Type Documentation
espnow_sec_type_t
enum espnow_sec_type_t
Type of packet.
< _cplusplus
Enumerator
ESPNOW_SEC_TYPE_REQUEST
Request security information
ESPNOW_SEC_TYPE_INFO
Security information
ESPNOW_SEC_TYPE_HANDSHAKE
Handshake packet to get key
ESPNOW_SEC_TYPE_KEY
Packet containing app key
ESPNOW_SEC_TYPE_KEY_RESP
Response to confirm gotten the app key
ESPNOW_SEC_TYPE_REST
Reset security information
Definition at line 31 of file espnow_security_handshake.h.
espnow_sec_ver_type_t
enum espnow_sec_ver_type_t
Security version.
Enumerator
ESPNOW_SEC_VER_NONE
No security
ESPNOW_SEC_VER_V1_0
The default security version
ESPNOW_SEC_VER_V1_1
Used in the future
Definition at line 43 of file espnow_security_handshake.h.
Function Documentation
espnow_sec_initiator_result_free()
esp_err_t espnow_sec_initiator_result_free (espnow_sec_result_t * result)
Free memory in the results list.
Parameters
[in] result pointer to device security status
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 478 of file espnow_security_initiator.c.
References ESP_FREE, ESP_PARAM_CHECK, espnow_sec_result_s::requested_addr, espnow_sec_result_s::requested_num, espnow_sec_result_s::successed_addr, espnow_sec_result_s::successed_num, espnow_sec_result_s::unfinished_addr, and espnow_sec_result_s::unfinished_num.
Referenced by app_main().
espnow_sec_initiator_scan()
esp_err_t espnow_sec_initiator_scan (espnow_sec_responder_t ** info_list, size_t * num, TickType_t wait_ticks)
Root scans other node info.
Attention
Only called at the root
Parameters
[out] info_list destination nodes of mac
[out] num number of scaned nodes
[in] wait_ticks the maximum scanning time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 141 of file espnow_security_initiator.c.
References CONFIG_ESPNOW_SEC_SEND_FORWARD_RSSI, CONFIG_ESPNOW_SEC_SEND_FORWARD_TTL, ESP_ERROR_RETURN, ESP_FREE, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_SECURITY, ESPNOW_DATA_TYPE_SECURITY_STATUS, ESPNOW_SEC_TYPE_REQUEST, espnow_send(), and espnow_set_config_for_data_type().
Referenced by app_main().
espnow_sec_initiator_scan_result_free()
esp_err_t espnow_sec_initiator_scan_result_free (void)
Free memory in the scan information list.
Returns
ESP_OK
Definition at line 176 of file espnow_security_initiator.c.
References ESP_FREE.
Referenced by app_main().
espnow_sec_initiator_start()
esp_err_t espnow_sec_initiator_start (uint8_t key_info[APP_KEY_LEN], const char * pop_data, const uint8_t addrs_list[][6], size_t addrs_num, espnow_sec_result_t * res)
Root sends security to other nodes.
Attention
Only called at the root
Parameters
[in] key_info the security key info to sent to responder
[in] pop_data Proof of Possession (PoP) string
[in] addrs_list destination nodes of mac
[in] addrs_num number of destination nodes
[out] res must call espnow_sec_initiator_result_free to free memory
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 429 of file espnow_security_initiator.c.
References APP_KEY_LEN, espnow_sec_data_t::data, ESP_ERROR_RETURN, ESP_FREE, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_SECURITY, espnow_set_config_for_data_type(), len, pop_data, and protocomm_client_security1.
Referenced by app_main().
espnow_sec_initiator_stop()
esp_err_t espnow_sec_initiator_stop ()
Stop Root to send security to other nodes.
Returns
ESP_OK
Definition at line 471 of file espnow_security_initiator.c.
espnow_sec_responder_start()
esp_err_t espnow_sec_responder_start (const char * pop_data)
Start security process.
Parameters
[in] pop_data Proof of Possession (PoP) string
Returns
ESP_OK
ESP_FAIL
Definition at line 211 of file espnow_security_responder.c.
References ESP_PARAM_CHECK, len, and pop_data.
Referenced by app_espnow_responder(), and app_main().
espnow_sec_responder_stop()
esp_err_t espnow_sec_responder_stop ()
Stop security process.
Returns
ESP_OK
ESP_FAIL _cplusplus
Definition at line 264 of file espnow_security_responder.c.