Kicker Controller: managed_components/espressif__esp-now/src/control/src/espnow_ctrl.c File Reference
espnow_ctrl.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/param.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_wifi.h"
#include "esp_sleep.h"
#include "esp_now.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "esp_event_base.h"
#include "espnow.h"
#include "espnow_ctrl.h"
#include "espnow_mem.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
Classes
struct espnow_bindlist_t
Macros
#define CONFIG_ESPNOW_CONTROL_SECURITY 0
Functions
esp_err_t espnow_ctrl_responder_get_bindlist (espnow_ctrl_bind_info_t *list, size_t *size)
The responder gets bound list.
esp_err_t espnow_ctrl_responder_set_bindlist (const espnow_ctrl_bind_info_t *info)
The responder sets bound list.
esp_err_t espnow_ctrl_responder_remove_bindlist (const espnow_ctrl_bind_info_t *info)
The responder removes bound list.
esp_err_t espnow_ctrl_responder_clear_bindlist (void)
Remove all bound devices from bindlist.
esp_err_t espnow_ctrl_responder_bind (uint32_t wait_ms, int8_t rssi, espnow_ctrl_bind_cb_t cb)
The responder creates a bind task to process the received bind frame.
esp_err_t espnow_ctrl_responder_data (espnow_ctrl_data_cb_t cb)
The responder registers control data callback function.
esp_err_t espnow_ctrl_initiator_bind (espnow_attribute_t initiator_attribute, bool enable)
The initiator sends a broadcast bind frame.
esp_err_t espnow_ctrl_initiator_send (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The initiator sends a broadcast control data frame.
esp_err_t espnow_ctrl_send (const espnow_addr_t dest_addr, const espnow_ctrl_data_t *data, const espnow_frame_head_t *frame_head, TickType_t wait_ticks)
Send control data frame.
esp_err_t espnow_ctrl_recv (espnow_ctrl_data_raw_cb_t cb)
The responder registers raw control data callback function.
Variables
wifi_country_t g_self_country
int8_t g_rssi = 0
uint32_t g_timestamp = 0
espnow_ctrl_bind_cb_t g_bind_cb = NULL
espnow_ctrl_data_cb_t g_data_cb = NULL
espnow_ctrl_data_raw_cb_t g_data_raw_cb = NULL
Macro Definition Documentation
CONFIG_ESPNOW_CONTROL_SECURITY
#define CONFIG_ESPNOW_CONTROL_SECURITY 0
Definition at line 58 of file espnow_ctrl.c.
Function Documentation
espnow_ctrl_initiator_bind()
esp_err_t espnow_ctrl_initiator_bind (espnow_attribute_t initiator_attribute, bool enable)
The initiator sends a broadcast bind frame.
Parameters
[in] initiator_attribute initiator attribute
[in] enable bind or unbind
Returns
TRUE
FALSE
Definition at line 467 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_BIND, espnow_send(), and espnow_frame_head_s::forward_ttl.
espnow_ctrl_initiator_send()
esp_err_t espnow_ctrl_initiator_send (espnow_attribute_t initiator_attribute, espnow_attribute_t responder_attribute, uint32_t responder_value)
The initiator sends a broadcast control data frame.
Parameters
[in] initiator_attribute the sending initiator's attribute
[in] responder_attribute the sending responder's attribute
[in] responder_value the sending responder value
Returns
ESP_OK: succeed
others: fail
Definition at line 486 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_send(), responder_attribute, and responder_value.
espnow_ctrl_recv()
esp_err_t espnow_ctrl_recv (espnow_ctrl_data_raw_cb_t cb)
The responder registers raw control data callback function.
Parameters
[in] cb the raw control data callback function
Returns
ESP_OK: succeed
others: fail _cplusplus
Definition at line 520 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_set_config_for_data_type(), and g_data_raw_cb.
espnow_ctrl_responder_bind()
esp_err_t espnow_ctrl_responder_bind (uint32_t wait_ms, int8_t rssi, espnow_ctrl_bind_cb_t cb)
The responder creates a bind task to process the received bind frame.
Attention
The bind frame will be processed if the callback function returns true and wait time is not timeout, and bind frame's RSSI is higher than the set RSSI.
The responder will bind or unbind with the sender according to the value in bind frame.
Parameters
[in] wait_ms maximum waiting bind time in millisecond
[in] rssi the minimum bind frame RSSI
[in] cb the bind callback function
Returns
ESP_OK: succeed
others: fail
Definition at line 285 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_BIND, espnow_set_config_for_data_type(), g_bind_cb, g_rssi, g_timestamp, and rssi.
espnow_ctrl_responder_clear_bindlist()
esp_err_t espnow_ctrl_responder_clear_bindlist (void)
Remove all bound devices from bindlist.
Returns
ESP_OK: succeed
others: fail
Definition at line 161 of file espnow_ctrl.c.
References ESPNOW_BIND_LIST_MAX_SIZE, and espnow_storage_set().
espnow_ctrl_responder_data()
esp_err_t espnow_ctrl_responder_data (espnow_ctrl_data_cb_t cb)
The responder registers control data callback function.
Parameters
[in] cb the control data callback function
Returns
ESP_OK: succeed
others: fail
Definition at line 333 of file espnow_ctrl.c.
References ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_set_config_for_data_type(), and g_data_cb.
espnow_ctrl_responder_get_bindlist()
esp_err_t espnow_ctrl_responder_get_bindlist (espnow_ctrl_bind_info_t * list, size_t * size)
The responder gets bound list.
Parameters
[out] list the buffer that stores the bound list
[in,out] size input maximum bound list size, output the real bound list size
Returns
ESP_OK: succeed
others: fail
Definition at line 116 of file espnow_ctrl.c.
References list.
espnow_ctrl_responder_remove_bindlist()
esp_err_t espnow_ctrl_responder_remove_bindlist (const espnow_ctrl_bind_info_t * info)
The responder removes bound list.
Attention
The bound information will be removed from flash
Parameters
[in] info the bound information to be removed
Returns
ESP_OK: succeed
others: fail
Definition at line 141 of file espnow_ctrl.c.
References espnow_storage_set(), and info.
espnow_ctrl_responder_set_bindlist()
esp_err_t espnow_ctrl_responder_set_bindlist (const espnow_ctrl_bind_info_t * info)
The responder sets bound list.
Attention
The bound information will be stored to flash
Parameters
[in] info the bound information to be set
Returns
ESP_OK: succeed
others: fail
Definition at line 129 of file espnow_ctrl.c.
References espnow_storage_set(), and info.
espnow_ctrl_send()
esp_err_t espnow_ctrl_send (const espnow_addr_t dest_addr, const espnow_ctrl_data_t * data, const espnow_frame_head_t * frame_head, TickType_t wait_ticks)
Send control data frame.
Parameters
[in] dest_addr dest_addr is not used
[in] data control data
[in] frame_head frame header must not be NULL
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK: succeed
others: fail
Definition at line 505 of file espnow_ctrl.c.
References ESP_ERROR_RETURN, ESP_PARAM_CHECK, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_CONTROL_DATA, espnow_send(), espnow_ctrl_data_s::responder_value_s_flag, and espnow_ctrl_data_s::responder_value_s_size.
Variable Documentation
g_bind_cb
espnow_ctrl_bind_cb_t g_bind_cb = NULL
Definition at line 50 of file espnow_ctrl.c.
Referenced by espnow_ctrl_responder_bind().
g_data_cb
espnow_ctrl_data_cb_t g_data_cb = NULL
Definition at line 51 of file espnow_ctrl.c.
Referenced by espnow_ctrl_responder_data().
g_data_raw_cb
espnow_ctrl_data_raw_cb_t g_data_raw_cb = NULL
Definition at line 52 of file espnow_ctrl.c.
Referenced by espnow_ctrl_recv().
g_rssi
int8_t g_rssi = 0
Definition at line 48 of file espnow_ctrl.c.
Referenced by espnow_ctrl_responder_bind().
g_self_country
wifi_country_t g_self_country extern
Definition at line 140 of file espnow.c.
Referenced by espnow_init(), espnow_send(), and espnow_set_group().
g_timestamp
uint32_t g_timestamp = 0
Definition at line 49 of file espnow_ctrl.c.
Referenced by espnow_ctrl_responder_bind().