Kicker Controller: managed_components/espressif__esp-now/src/provisioning/include/espnow_prov.h File Reference
espnow_prov.h File Reference
#include "esp_system.h"
#include "espnow.h"
Classes
struct espnow_prov_initiator_s
Initiator information.
struct espnow_prov_responder_s
Responder information.
struct espnow_prov_wifi_s
WiFi configuration.
Macros
#define ESPNOW_PROV_CUSTOM_MAX_SIZE 64
Typedefs
typedef struct espnow_prov_initiator_s espnow_prov_initiator_t
Initiator information.
typedef struct espnow_prov_responder_s espnow_prov_responder_t
Responder information.
typedef struct espnow_prov_wifi_s espnow_prov_wifi_t
WiFi configuration.
typedef esp_err_t(* espnow_prov_cb_t) (uint8_t *src_addr, void *data, size_t size, wifi_pkt_rx_ctrl_t *rx_ctrl)
The provision data callback function.
Enumerations
enum espnow_prov_auth_mode_t { ESPNOW_PROV_AUTH_INVALID , ESPNOW_PROV_AUTH_PRODUCT , ESPNOW_PROV_AUTH_DEVICE , ESPNOW_PROV_AUTH_CERT }
Enumerated list of provision authentication mode.
Functions
esp_err_t espnow_prov_initiator_scan (espnow_addr_t responder_addr, espnow_prov_responder_t *responder_info, wifi_pkt_rx_ctrl_t *rx_ctrl, TickType_t wait_ticks)
Initiator scans provision beacon.
esp_err_t espnow_prov_initiator_send (const espnow_addr_t responder_addr, const espnow_prov_initiator_t *initiator_info, espnow_prov_cb_t cb, TickType_t wait_ticks)
Initiator sends information to request WiFi configuration.
esp_err_t espnow_prov_responder_start (const espnow_prov_responder_t *responder_info, TickType_t wait_ticks, const espnow_prov_wifi_t *wifi_config, espnow_prov_cb_t cb)
Responder starts to send provision beacon, receives initiator request and send WiFi configuration.
Macro Definition Documentation
ESPNOW_PROV_CUSTOM_MAX_SIZE
#define ESPNOW_PROV_CUSTOM_MAX_SIZE 64
Definition at line 24 of file espnow_prov.h.
Typedef Documentation
espnow_prov_cb_t
typedef esp_err_t(* espnow_prov_cb_t) (uint8_t *src_addr, void *data, size_t size, wifi_pkt_rx_ctrl_t *rx_ctrl)
The provision data callback function.
Attention
If it is WiFi configuration callback function, the data buffer stores WiFi configuration.
If it is initiator information callback function, the data buffer stores initiator information. Initiator information should be checked in the function. If the function returns true, responder will send WiFi configuration to initiator. If the function returns false, responder will not send WiFi configuration to initiator.
Parameters
[in] src_addr mac address of sender
[in] data WiFi configuration from responder or initiator information from initiator
[in] size data size
[in] rx_ctrl received packet radio metadata header
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 93 of file espnow_prov.h.
espnow_prov_initiator_t
typedef struct espnow_prov_initiator_s espnow_prov_initiator_t
Initiator information.
espnow_prov_responder_t
typedef struct espnow_prov_responder_s espnow_prov_responder_t
Responder information.
espnow_prov_wifi_t
typedef struct espnow_prov_wifi_s espnow_prov_wifi_t
WiFi configuration.
Enumeration Type Documentation
espnow_prov_auth_mode_t
enum espnow_prov_auth_mode_t
Enumerated list of provision authentication mode.
Enumerator
ESPNOW_PROV_AUTH_INVALID
Invalid mode
ESPNOW_PROV_AUTH_PRODUCT
Product authentication
ESPNOW_PROV_AUTH_DEVICE
Device authentication
ESPNOW_PROV_AUTH_CERT
Certificate authentication
Definition at line 29 of file espnow_prov.h.
Function Documentation
espnow_prov_initiator_scan()
esp_err_t espnow_prov_initiator_scan (espnow_addr_t responder_addr, espnow_prov_responder_t * responder_info, wifi_pkt_rx_ctrl_t * rx_ctrl, TickType_t wait_ticks)
Initiator scans provision beacon.
Parameters
[out] responder_addr mac address of responder
[out] responder_info information of responder
[out] rx_ctrl received packet radio metadata header
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 147 of file espnow_prov.c.
References ESP_CALLOC, ESP_FREE, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_PROV, ESPNOW_PROV_BEACON_INTERVAL, and espnow_set_config_for_data_type().
espnow_prov_initiator_send()
esp_err_t espnow_prov_initiator_send (const espnow_addr_t responder_addr, const espnow_prov_initiator_t * initiator_info, espnow_prov_cb_t cb, TickType_t wait_ticks)
Initiator sends information to request WiFi configuration.
Parameters
[in] responder_addr mac address of responder
[in] initiator_info information of initiator
[in] cb WiFi configuration callback function
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK
ESP_ERR_WIFI_TIMEOUT
ESP_ERR_INVALID_ARG
Definition at line 190 of file espnow_prov.c.
References CONFIG_ESPNOW_PROV_SECURITY, ESP_CALLOC, ESP_ERROR_RETURN, ESP_FREE, ESP_MALLOC, ESP_PARAM_CHECK, espnow_add_peer(), ESPNOW_DATA_TYPE_PROV, espnow_del_peer(), ESPNOW_PROV_TYPE_DEVICE, espnow_send(), and espnow_set_config_for_data_type().
espnow_prov_responder_start()
esp_err_t espnow_prov_responder_start (const espnow_prov_responder_t * responder_info, TickType_t wait_ticks, const espnow_prov_wifi_t * wifi_config, espnow_prov_cb_t cb)
Responder starts to send provision beacon, receives initiator request and send WiFi configuration.
Parameters
[in] responder_info information of responder
[in] wait_ticks provision beacon sending time in ticks
[in] wifi_config WiFi configuration information
[in] cb initiator information callback function
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 270 of file espnow_prov.c.
References ESP_CALLOC, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_PROV, ESPNOW_PROV_BEACON_INTERVAL, ESPNOW_PROV_TYPE_BEACON, and espnow_set_config_for_data_type().