Kicker Controller: managed_components/espressif__esp-now/src/security/src/espnow_security_initiator.c File Reference
espnow_security_initiator.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <esp_err.h>
#include <esp_log.h>
#include "esp_system.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include <protocomm.h>
#include <protocomm_client_security1.h>
#include "esp_wifi.h"
#include "espnow.h"
#include "espnow_security_handshake.h"
Classes
struct espnow_sec_data_t
Macros
#define CONFIG_ESPNOW_SEC_SEND_RETRY_NUM 1
#define CONFIG_ESPNOW_SEC_SEND_FORWARD_TTL 0
#define CONFIG_ESPNOW_SEC_SEND_FORWARD_RSSI -65
Functions
esp_err_t espnow_sec_initiator_scan (espnow_sec_responder_t **info_list, size_t *num, TickType_t wait_ticks)
Root scans other node info.
esp_err_t espnow_sec_initiator_scan_result_free (void)
Free memory in the scan information list.
esp_err_t espnow_sec_initiator_start (uint8_t key_info[APP_KEY_LEN], const char *pop_data, const uint8_t addrs_list[][6], size_t addrs_num, espnow_sec_result_t *res)
Root sends security to other nodes.
esp_err_t espnow_sec_initiator_stop ()
Stop Root to send security to other nodes.
esp_err_t espnow_sec_initiator_result_free (espnow_sec_result_t *result)
Free memory in the results list.
Macro Definition Documentation
CONFIG_ESPNOW_SEC_SEND_FORWARD_RSSI
#define CONFIG_ESPNOW_SEC_SEND_FORWARD_RSSI -65
Definition at line 54 of file espnow_security_initiator.c.
Referenced by espnow_sec_initiator_scan().
CONFIG_ESPNOW_SEC_SEND_FORWARD_TTL
#define CONFIG_ESPNOW_SEC_SEND_FORWARD_TTL 0
Definition at line 50 of file espnow_security_initiator.c.
Referenced by espnow_sec_initiator_scan().
CONFIG_ESPNOW_SEC_SEND_RETRY_NUM
#define CONFIG_ESPNOW_SEC_SEND_RETRY_NUM 1
Definition at line 46 of file espnow_security_initiator.c.
Function Documentation
espnow_sec_initiator_result_free()
esp_err_t espnow_sec_initiator_result_free (espnow_sec_result_t * result)
Free memory in the results list.
Parameters
[in] result pointer to device security status
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 478 of file espnow_security_initiator.c.
References ESP_FREE, ESP_PARAM_CHECK, espnow_sec_result_s::requested_addr, espnow_sec_result_s::requested_num, espnow_sec_result_s::successed_addr, espnow_sec_result_s::successed_num, espnow_sec_result_s::unfinished_addr, and espnow_sec_result_s::unfinished_num.
Referenced by app_main().
espnow_sec_initiator_scan()
esp_err_t espnow_sec_initiator_scan (espnow_sec_responder_t ** info_list, size_t * num, TickType_t wait_ticks)
Root scans other node info.
Attention
Only called at the root
Parameters
[out] info_list destination nodes of mac
[out] num number of scaned nodes
[in] wait_ticks the maximum scanning time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 141 of file espnow_security_initiator.c.
References CONFIG_ESPNOW_SEC_SEND_FORWARD_RSSI, CONFIG_ESPNOW_SEC_SEND_FORWARD_TTL, ESP_ERROR_RETURN, ESP_FREE, ESPNOW_ADDR_BROADCAST, ESPNOW_DATA_TYPE_SECURITY, ESPNOW_DATA_TYPE_SECURITY_STATUS, ESPNOW_SEC_TYPE_REQUEST, espnow_send(), and espnow_set_config_for_data_type().
Referenced by app_main().
espnow_sec_initiator_scan_result_free()
esp_err_t espnow_sec_initiator_scan_result_free (void)
Free memory in the scan information list.
Returns
ESP_OK
Definition at line 176 of file espnow_security_initiator.c.
References ESP_FREE.
Referenced by app_main().
espnow_sec_initiator_start()
esp_err_t espnow_sec_initiator_start (uint8_t key_info[APP_KEY_LEN], const char * pop_data, const uint8_t addrs_list[][6], size_t addrs_num, espnow_sec_result_t * res)
Root sends security to other nodes.
Attention
Only called at the root
Parameters
[in] key_info the security key info to sent to responder
[in] pop_data Proof of Possession (PoP) string
[in] addrs_list destination nodes of mac
[in] addrs_num number of destination nodes
[out] res must call espnow_sec_initiator_result_free to free memory
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 429 of file espnow_security_initiator.c.
References APP_KEY_LEN, espnow_sec_data_t::data, ESP_ERROR_RETURN, ESP_FREE, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_SECURITY, espnow_set_config_for_data_type(), len, pop_data, and protocomm_client_security1.
Referenced by app_main().
espnow_sec_initiator_stop()
esp_err_t espnow_sec_initiator_stop ()
Stop Root to send security to other nodes.
Returns
ESP_OK
Definition at line 471 of file espnow_security_initiator.c.