Kicker Controller: managed_components/espressif__esp-now/src/provisioning/src/espnow_prov.c File Reference
espnow_prov.c File Reference
#include <string.h>
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/timers.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "espnow.h"
#include "espnow_prov.h"
#include "espnow_utils.h"
Classes
struct __attribute__
HID Descriptor.
struct espnow_prov_init_t
struct espnow_prov_resp_t
Macros
#define ESPNOW_PROV_BEACON_INTERVAL 100
#define CONFIG_ESPNOW_PROV_SECURITY 0
Enumerations
enum espnow_prov_type_t { ESPNOW_PROV_TYPE_BEACON , ESPNOW_PROV_TYPE_DEVICE , ESPNOW_PROV_TYPE_WIFI }
Functions
esp_err_t espnow_prov_initiator_scan (espnow_addr_t responder_addr, espnow_prov_responder_t *responder_info, wifi_pkt_rx_ctrl_t *rx_ctrl, TickType_t wait_ticks)
Initiator scans provision beacon.
esp_err_t espnow_prov_initiator_send (const espnow_addr_t responder_addr, const espnow_prov_initiator_t *initiator_info, espnow_prov_cb_t cb, TickType_t wait_ticks)
Initiator sends information to request WiFi configuration.
esp_err_t espnow_prov_responder_start (const espnow_prov_responder_t *responder_info, TickType_t wait_ticks, const espnow_prov_wifi_t *wifi_config, espnow_prov_cb_t cb)
Responder starts to send provision beacon, receives initiator request and send WiFi configuration.
Macro Definition Documentation
CONFIG_ESPNOW_PROV_SECURITY
#define CONFIG_ESPNOW_PROV_SECURITY 0
Definition at line 55 of file espnow_prov.c.
Referenced by espnow_prov_initiator_send().
ESPNOW_PROV_BEACON_INTERVAL
#define ESPNOW_PROV_BEACON_INTERVAL 100
Definition at line 49 of file espnow_prov.c.
Referenced by espnow_prov_initiator_scan(), and espnow_prov_responder_start().
Enumeration Type Documentation
espnow_prov_type_t
enum espnow_prov_type_t
Enumerator
ESPNOW_PROV_TYPE_BEACON
ESPNOW_PROV_TYPE_DEVICE
ESPNOW_PROV_TYPE_WIFI
Definition at line 34 of file espnow_prov.c.
Function Documentation
espnow_prov_initiator_scan()
esp_err_t espnow_prov_initiator_scan (espnow_addr_t responder_addr, espnow_prov_responder_t * responder_info, wifi_pkt_rx_ctrl_t * rx_ctrl, TickType_t wait_ticks)
Initiator scans provision beacon.
Parameters
[out] responder_addr mac address of responder
[out] responder_info information of responder
[out] rx_ctrl received packet radio metadata header
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 147 of file espnow_prov.c.
References ESP_CALLOC, ESP_FREE, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_PROV, ESPNOW_PROV_BEACON_INTERVAL, and espnow_set_config_for_data_type().
espnow_prov_initiator_send()
esp_err_t espnow_prov_initiator_send (const espnow_addr_t responder_addr, const espnow_prov_initiator_t * initiator_info, espnow_prov_cb_t cb, TickType_t wait_ticks)
Initiator sends information to request WiFi configuration.
Parameters
[in] responder_addr mac address of responder
[in] initiator_info information of initiator
[in] cb WiFi configuration callback function
[in] wait_ticks the maximum waiting time in ticks
Returns
ESP_OK
ESP_ERR_WIFI_TIMEOUT
ESP_ERR_INVALID_ARG
Definition at line 190 of file espnow_prov.c.
References CONFIG_ESPNOW_PROV_SECURITY, ESP_CALLOC, ESP_ERROR_RETURN, ESP_FREE, ESP_MALLOC, ESP_PARAM_CHECK, espnow_add_peer(), ESPNOW_DATA_TYPE_PROV, espnow_del_peer(), ESPNOW_PROV_TYPE_DEVICE, espnow_send(), and espnow_set_config_for_data_type().
espnow_prov_responder_start()
esp_err_t espnow_prov_responder_start (const espnow_prov_responder_t * responder_info, TickType_t wait_ticks, const espnow_prov_wifi_t * wifi_config, espnow_prov_cb_t cb)
Responder starts to send provision beacon, receives initiator request and send WiFi configuration.
Parameters
[in] responder_info information of responder
[in] wait_ticks provision beacon sending time in ticks
[in] wifi_config WiFi configuration information
[in] cb initiator information callback function
Returns
ESP_OK
ESP_ERR_INVALID_ARG
Definition at line 270 of file espnow_prov.c.
References ESP_CALLOC, ESP_MALLOC, ESP_PARAM_CHECK, ESPNOW_DATA_TYPE_PROV, ESPNOW_PROV_BEACON_INTERVAL, ESPNOW_PROV_TYPE_BEACON, and espnow_set_config_for_data_type().