Kicker Controller: managed_components/espressif__esp-now/src/utils/src/espnow_timesync.c File Reference
espnow_timesync.c File Reference
#include <esp_log.h>
#include "lwip/apps/sntp.h"
#include <espnow_utils.h>
Macros
#define REF_TIME 1577808000 /* 2020-01-01 00:00:00 */
#define DEFAULT_TICKS (2000 / portTICK_PERIOD_MS) /* 2 seconds in ticks */
#define CONFIG_ESP_SNTP_SERVER_NAME "pool.ntp.org"
Functions
esp_err_t espnow_timesync_start ()
Initialize time synchronization.
bool espnow_timesync_check (void)
Check if current time is updated.
esp_err_t espnow_timesync_wait (TickType_t ticks_to_wait)
Macro Definition Documentation
CONFIG_ESP_SNTP_SERVER_NAME
#define CONFIG_ESP_SNTP_SERVER_NAME "pool.ntp.org"
Definition at line 23 of file espnow_timesync.c.
Referenced by espnow_timesync_start().
DEFAULT_TICKS
#define DEFAULT_TICKS (2000 / portTICK_PERIOD_MS) /* 2 seconds in ticks */
Definition at line 21 of file espnow_timesync.c.
Referenced by espnow_timesync_wait().
REF_TIME
#define REF_TIME 1577808000 /* 2020-01-01 00:00:00 */
Definition at line 20 of file espnow_timesync.c.
Referenced by espnow_timesync_check().
Function Documentation
espnow_timesync_check()
bool espnow_timesync_check (void)
Check if current time is updated.
This API checks if the current system time is updated against the reference time of 1-Jan-2020.
Returns
true if time is updated
false if time is not updated
Definition at line 49 of file espnow_timesync.c.
References REF_TIME, and time.
Referenced by espnow_timesync_wait().
espnow_timesync_start()
esp_err_t espnow_timesync_start (void)
Initialize time synchronization.
This API initializes SNTP for time synchronization.
Returns
ESP_OK
ESP_FAIL
Definition at line 29 of file espnow_timesync.c.
References CONFIG_ESP_SNTP_SERVER_NAME.
Referenced by app_espnow_monitored_device_start(), and app_espnow_responder().
espnow_timesync_wait()
esp_err_t espnow_timesync_wait (TickType_t ticks_to_wait)
Definition at line 61 of file espnow_timesync.c.
References DEFAULT_TICKS, espnow_timesync_check(), and time.