Kicker Controller: managed_components/espressif__esp-now/src/debug/src/espnow_log_flash.h File Reference
espnow_log_flash.h File Reference
Functions
esp_err_t espnow_log_flash_init ()
Initialize espnow log flash Find and get log flash partition which size is not smaller than LOG_FLASH_FILE_MAX_SIZE. Create several files under the spiffs folder. Open the file in the next step for the storage of the log data.
esp_err_t espnow_log_flash_deinit ()
Deinit log flash Log flash operation will be stopped.
esp_err_t espnow_log_flash_erase ()
Erase the flash when the log partition is full.
esp_err_t espnow_log_flash_write (const char *data, size_t size, esp_log_level_t level)
Write memory log data in flash.
Function Documentation
espnow_log_flash_deinit()
esp_err_t espnow_log_flash_deinit ()
Deinit log flash Log flash operation will be stopped.
Returns
ESP_OK
Definition at line 183 of file espnow_log_flash.c.
Referenced by espnow_log_deinit().
espnow_log_flash_erase()
esp_err_t espnow_log_flash_erase ()
Erase the flash when the log partition is full.
Returns
ESP_OK
Definition at line 319 of file espnow_log_flash.c.
References CONFIG_ESPNOW_DEBUG_LOG_PARTITION_OFFSET, ESP_ERROR_RETURN, LOG_FLASH_FILE_MAX_SIZE, and LOG_FLASH_STORE_KEY.
espnow_log_flash_init()
esp_err_t espnow_log_flash_init ()
Initialize espnow log flash Find and get log flash partition which size is not smaller than LOG_FLASH_FILE_MAX_SIZE. Create several files under the spiffs folder. Open the file in the next step for the storage of the log data.
< _cplusplus
Returns
ESP_OK
< Whether file is full
< File index
Definition at line 131 of file espnow_log_flash.c.
References addr, CONFIG_ESPNOW_DEBUG_LOG_PARTITION_LABEL_DATA, CONFIG_ESPNOW_DEBUG_LOG_PARTITION_OFFSET, ESP_CALLOC, ESP_ERROR_RETURN, LOG_FLASH_FILE_MAX_NUM, LOG_FLASH_FILE_MAX_SIZE, and LOG_FLASH_STORE_KEY.
Referenced by espnow_log_init().
espnow_log_flash_write()
esp_err_t espnow_log_flash_write (const char * data, size_t size, esp_log_level_t level)
Write memory log data in flash.
Note
Don't include timestamp in interface input data
Parameters
[in] data log data to be stored in flash's spiffs files
[in] size size of the data in bytes
[in] level level of the log
Returns
ESP_OK _cplusplus ESPNOW_DEBUG_FLASH_H
Get the address of the pointer to the next file and clear the file to be written and clear offset size.
< Get the current timestamp
Change the write file address, then write timestamp data
Change the write file address, then write log data after the timestamp.
Note
First need to get the length of the timestamp, then write the log data after the timestamp
Here in order to read the data address written by the file,Get where the data address is written.
Definition at line 196 of file espnow_log_flash.c.
References addr, DEBUG_LOG_PRINTF, ESP_ERROR_RETURN, ESP_EVENT_ESPNOW_LOG_FLASH_FULL, ESP_PARAM_CHECK, espnow_log_flash_size(), level, LOG_FLASH_FILE_MAX_NUM, LOG_FLASH_FILE_MAX_SIZE, LOG_FLASH_STORE_KEY, and time.