Kicker Controller: managed_components/espressif__esp-now/src/debug/include/espnow_console.h File Reference
espnow_console.h File Reference
#include "argtable3/argtable3.h"
#include "esp_console.h"
Classes
struct espnow_console_config_s
Console configuration.
Typedefs
typedef struct espnow_console_config_s espnow_console_config_t
Console configuration.
Functions
esp_err_t espnow_console_init (const espnow_console_config_t *config)
Initialize console module.
esp_err_t espnow_console_deinit (void)
De-initialize console module Call this once when done using console module functions.
void espnow_console_commands_register ()
Register Common commands.
Typedef Documentation
espnow_console_config_t
typedef struct espnow_console_config_s espnow_console_config_t
Console configuration.
< _cplusplus
Function Documentation
espnow_console_commands_register()
void espnow_console_commands_register ()
Register Common commands.
_cplusplus
Initializing SD card via SDMMC peripheral
Register some commands
Definition at line 19 of file espnow_commands.c.
References register_espnow(), register_iperf(), register_peripherals(), register_sdcard(), register_system(), register_wifi(), register_wifi_sniffer(), sdcard_init(), and sdcard_is_mount().
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), and app_espnow_responder().
espnow_console_deinit()
esp_err_t espnow_console_deinit (void)
De-initialize console module Call this once when done using console module functions.
Returns
ESP_OK
ESP_FAIL
Definition at line 315 of file espnow_console.c.
References ESP_ERROR_RETURN, ESP_FREE, ESPNOW_DATA_TYPE_DEBUG_COMMAND, and espnow_set_config_for_data_type().
espnow_console_init()
esp_err_t espnow_console_init (const espnow_console_config_t * config)
Initialize console module.
Initialize the console
Register help commands
Initialize filesystem
Create console handle task
Parameters
[in] config pointer to the console configuration structure
Returns
ESP_OK
ESP_FAIL
Definition at line 202 of file espnow_console.c.
References config, CONFIG_ESP_CONSOLE_UART_BAUDRATE, CONFIG_ESP_CONSOLE_UART_NUM, ESPNOW_DATA_TYPE_DEBUG_COMMAND, and espnow_set_config_for_data_type().
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), and app_espnow_responder().