Kicker Controller: managed_components/espressif__esp-now/src/debug/src/commands/espnow_commands.c File Reference
espnow_commands.c File Reference
#include "sdcard.h"
#include "espnow_cmd.h"
#include "driver/gpio.h"
Functions
void espnow_console_commands_register (void)
Register Common commands.
Function Documentation
espnow_console_commands_register()
void espnow_console_commands_register ()
Register Common commands.
_cplusplus
Initializing SD card via SDMMC peripheral
Register some commands
Definition at line 19 of file espnow_commands.c.
References register_espnow(), register_iperf(), register_peripherals(), register_sdcard(), register_system(), register_wifi(), register_wifi_sniffer(), sdcard_init(), and sdcard_is_mount().
Referenced by app_espnow_initiator(), app_espnow_monitor_device_start(), app_espnow_monitored_device_start(), and app_espnow_responder().