Kicker Controller: managed_components/espressif__esp-now/examples/get-started/main/app_main.c File Reference
app_main.c File Reference
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "espnow.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
#include "driver/uart.h"
Macros
#define UART_BAUD_RATE 115200
#define UART_PORT_NUM 0
#define UART_TX_IO UART_PIN_NO_CHANGE
#define UART_RX_IO UART_PIN_NO_CHANGE
Functions
void app_main ()
Macro Definition Documentation
UART_BAUD_RATE
#define UART_BAUD_RATE 115200
Definition at line 28 of file app_main.c.
UART_PORT_NUM
#define UART_PORT_NUM 0
Definition at line 29 of file app_main.c.
UART_RX_IO
#define UART_RX_IO UART_PIN_NO_CHANGE
Definition at line 31 of file app_main.c.
UART_TX_IO
#define UART_TX_IO UART_PIN_NO_CHANGE
Definition at line 30 of file app_main.c.
Function Documentation
app_main()
void app_main (void)
Definition at line 117 of file app_main.c.
References ESPNOW_DATA_TYPE_DATA, espnow_init(), ESPNOW_INIT_CONFIG_DEFAULT, espnow_set_config_for_data_type(), and espnow_storage_init().