Kicker Controller: managed_components/espressif__usb_host_hid/hid_host.c File Reference
hid_host.c File Reference
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/queue.h>
#include <sys/param.h>
#include "esp_log.h"
#include "esp_check.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "usb/usb_host.h"
#include "usb/hid_host.h"
Classes
struct hid_host_device
HID Device structure.
struct hid_interface
HID Interface structure in device to interact with. After HID device opening keeps the interface configuration.
struct hid_driver_t
HID driver default context.
struct hid_class_request
HID class specific request.
Macros
#define HID_ENTER_CRITICAL()
#define HID_EXIT_CRITICAL()
#define HID_GOTO_ON_FALSE_CRITICAL(exp, err)
#define HID_RETURN_ON_FALSE_CRITICAL(exp, err)
#define HID_GOTO_ON_ERROR(exp, msg)
#define HID_GOTO_ON_FALSE(exp, err, msg)
#define HID_RETURN_ON_ERROR(exp, msg)
#define HID_RETURN_ON_FALSE(exp, err, msg)
#define HID_RETURN_ON_INVALID_ARG(exp)
#define GET_NEXT_INTERFACE_DESC(p, max_len, offs)
#define GET_NEXT_HID_DESC(p, max_len, offs)
#define DEFAULT_TIMEOUT_MS (5000)
Typedefs
typedef struct hid_host_device hid_device_t
HID Device structure.
typedef struct hid_interface hid_iface_t
HID Interface structure in device to interact with. After HID device opening keeps the interface configuration.
typedef struct hid_class_request hid_class_request_t
HID class specific request.
Enumerations
enum hid_iface_state_t {
HID_INTERFACE_STATE_NOT_INITIALIZED = 0x00 , HID_INTERFACE_STATE_IDLE , HID_INTERFACE_STATE_READY , HID_INTERFACE_STATE_ACTIVE ,
HID_INTERFACE_STATE_WAIT_USER_DELETION , HID_INTERFACE_STATE_MAX
}
HID Interface state.
Functions
esp_err_t hid_host_install (const hid_host_driver_config_t *config)
USB HID Host install USB Host HID Class driver.
esp_err_t hid_host_uninstall (void)
USB HID Host uninstall HID Class driver.
esp_err_t hid_host_device_open (hid_host_device_handle_t hid_dev_handle, const hid_host_device_config_t *config)
USB HID Host open a device with specific device parameters.
esp_err_t hid_host_device_close (hid_host_device_handle_t hid_dev_handle)
USB HID Host close device.
esp_err_t hid_host_handle_events (uint32_t timeout)
HID Host USB event handler.
esp_err_t hid_host_device_get_params (hid_host_device_handle_t hid_dev_handle, hid_host_dev_params_t *dev_params)
HID Device get parameters by handle.
esp_err_t hid_host_device_get_raw_input_report_data (hid_host_device_handle_t hid_dev_handle, uint8_t *data, size_t data_length_max, size_t *data_length)
HID Host get device raw input report data pointer by handle.
esp_err_t hid_host_device_start (hid_host_device_handle_t hid_dev_handle)
HID Host start awaiting event from a device by handle.
esp_err_t hid_host_device_stop (hid_host_device_handle_t hid_dev_handle)
HID Host stop device.
uint8_t * hid_host_get_report_descriptor (hid_host_device_handle_t hid_dev_handle, size_t *report_desc_len)
HID Host Get Report Descriptor.
esp_err_t hid_host_get_device_info (hid_host_device_handle_t hid_dev_handle, hid_host_dev_info_t *hid_dev_info)
HID Host Get device information.
esp_err_t hid_class_request_get_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t *report, size_t *report_length)
HID class specific request GET REPORT.
esp_err_t hid_class_request_get_idle (hid_host_device_handle_t hid_dev_handle, uint8_t report_id, uint8_t *idle_rate)
HID class specific request GET IDLE.
esp_err_t hid_class_request_get_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t *protocol)
HID class specific request GET PROTOCOL.
esp_err_t hid_class_request_set_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t *report, size_t report_length)
HID class specific request SET REPORT.
esp_err_t hid_class_request_set_idle (hid_host_device_handle_t hid_dev_handle, uint8_t duration, uint8_t report_id)
HID class specific request SET IDLE.
esp_err_t hid_class_request_set_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t protocol)
HID class specific request SET PROTOCOL.
Macro Definition Documentation
DEFAULT_TIMEOUT_MS
#define DEFAULT_TIMEOUT_MS (5000)
Definition at line 70 of file hid_host.c.
Referenced by hid_host_device_start().
GET_NEXT_HID_DESC
#define GET_NEXT_HID_DESC (p, max_len, offs)
Value:
    ((const hid_descriptor_t *)usb_parse_next_descriptor_of_type((const usb_standard_desc_t *)p, \
                                                                max_len,                         \
                                                                HID_CLASS_DESCRIPTOR_TYPE_HID,   \
                                                                &(offs)))
Definition at line 62 of file hid_host.c.
GET_NEXT_INTERFACE_DESC
#define GET_NEXT_INTERFACE_DESC (p, max_len, offs)
Value:
    ((const usb_intf_desc_t *)usb_parse_next_descriptor_of_type((const usb_standard_desc_t *)p,  \
                                                                max_len,                         \
                                                                USB_B_DESCRIPTOR_TYPE_INTERFACE, \
                                                                &(offs)))
Definition at line 56 of file hid_host.c.
HID_ENTER_CRITICAL
#define HID_ENTER_CRITICAL ()
Value:
portENTER_CRITICAL(&hid_lock)
Definition at line 24 of file hid_host.c.
Referenced by hid_host_device_close(), hid_host_install(), and hid_host_uninstall().
HID_EXIT_CRITICAL
#define HID_EXIT_CRITICAL ()
Value:
portEXIT_CRITICAL(&hid_lock)
Definition at line 25 of file hid_host.c.
Referenced by hid_host_device_close(), hid_host_install(), and hid_host_uninstall().
HID_GOTO_ON_ERROR
#define HID_GOTO_ON_ERROR (exp, msg)
Value:
ESP_GOTO_ON_ERROR(exp, fail, TAG, msg)
Definition at line 45 of file hid_host.c.
Referenced by hid_host_install().
HID_GOTO_ON_FALSE
#define HID_GOTO_ON_FALSE (exp, err, msg)
Value:
ESP_GOTO_ON_FALSE((exp), err, fail, TAG, msg)
Definition at line 47 of file hid_host.c.
Referenced by hid_host_install().
HID_GOTO_ON_FALSE_CRITICAL
#define HID_GOTO_ON_FALSE_CRITICAL (exp, err)
Value:
    do {                                        \
        if(!(exp)) {                            \
            HID_EXIT_CRITICAL();                \
            ret = err;                          \
            goto fail;                          \
        }                                       \
    } while(0)
Definition at line 28 of file hid_host.c.
Referenced by hid_host_install().
HID_RETURN_ON_ERROR
#define HID_RETURN_ON_ERROR (exp, msg)
Value:
ESP_RETURN_ON_ERROR((exp), TAG, msg)
Definition at line 49 of file hid_host.c.
Referenced by hid_class_request_get_idle(), hid_class_request_get_protocol(), hid_host_device_close(), hid_host_device_open(), and hid_host_get_device_info().
HID_RETURN_ON_FALSE
#define HID_RETURN_ON_FALSE (exp, err, msg)
Value:
ESP_RETURN_ON_FALSE((exp), (err), TAG, msg)
Definition at line 51 of file hid_host.c.
Referenced by hid_host_device_get_params(), hid_host_device_get_raw_input_report_data(), hid_host_device_open(), hid_host_device_start(), hid_host_handle_events(), hid_host_install(), and hid_host_uninstall().
HID_RETURN_ON_FALSE_CRITICAL
#define HID_RETURN_ON_FALSE_CRITICAL (exp, err)
Value:
    do {                                        \
        if(!(exp)) {                            \
            HID_EXIT_CRITICAL();                \
            return err;                         \
        }                                       \
    } while(0)
Definition at line 37 of file hid_host.c.
Referenced by hid_host_uninstall().
HID_RETURN_ON_INVALID_ARG
#define HID_RETURN_ON_INVALID_ARG (exp)
Value:
ESP_RETURN_ON_FALSE((exp) != NULL, ESP_ERR_INVALID_ARG, TAG, "Argument error")
Definition at line 53 of file hid_host.c.
Referenced by hid_class_request_get_idle(), hid_class_request_get_protocol(), hid_class_request_get_report(), hid_class_request_set_idle(), hid_class_request_set_protocol(), hid_class_request_set_report(), hid_host_device_close(), hid_host_device_open(), hid_host_device_start(), hid_host_device_stop(), hid_host_get_device_info(), and hid_host_install().
Typedef Documentation
hid_class_request_t
typedef struct hid_class_request hid_class_request_t
HID class specific request.
hid_device_t
typedef struct hid_host_device hid_device_t
HID Device structure.
hid_iface_t
typedef struct hid_interface hid_iface_t
HID Interface structure in device to interact with. After HID device opening keeps the interface configuration.
Enumeration Type Documentation
hid_iface_state_t
enum hid_iface_state_t
HID Interface state.
Enumerator
HID_INTERFACE_STATE_NOT_INITIALIZED
HID Interface not initialized
HID_INTERFACE_STATE_IDLE
HID Interface has been found in connected USB device
HID_INTERFACE_STATE_READY
HID Interface opened and ready to start transfer
HID_INTERFACE_STATE_ACTIVE
HID Interface is in use
HID_INTERFACE_STATE_WAIT_USER_DELETION
HID Interface wait user to be removed
HID_INTERFACE_STATE_MAX
Definition at line 88 of file hid_host.c.
Function Documentation
hid_class_request_get_idle()
esp_err_t hid_class_request_get_idle (hid_host_device_handle_t hid_dev_handle, uint8_t report_id, uint8_t * idle_rate)
HID class specific request GET IDLE.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_id ReportID
[out] idle_rate Idle rate [ms]
Returns
esp_err_t
Definition at line 1419 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_IDLE, HID_RETURN_ON_ERROR, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_class_request_get_protocol()
esp_err_t hid_class_request_get_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t * protocol)
HID class specific request GET PROTOCOL.
Parameters
[in] hid_dev_handle HID Device handle
[out] protocol Pointer to HID report protocol (boot or report) of device
Returns
esp_err_t
Definition at line 1446 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_PROTOCOL, HID_RETURN_ON_ERROR, HID_RETURN_ON_INVALID_ARG, and protocol.
Referenced by hid_host_test_requests_callback().
hid_class_request_get_report()
esp_err_t hid_class_request_get_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t * report, size_t * report_length)
HID class specific request GET REPORT.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_id Report ID
[out] report Pointer to buffer for a report data
[in/out] report_length Report data length, before the get report contain the maximum value of a report buffer. After get report there is a value of actual data in report buffer.
Returns
esp_err_t
Definition at line 1397 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_REPORT, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_class_request_set_idle()
esp_err_t hid_class_request_set_idle (hid_host_device_handle_t hid_dev_handle, uint8_t duration, uint8_t report_id)
HID class specific request SET IDLE.
Parameters
[in] hid_dev_handle HID Device handle
[in] duration 0 (zero) for the indefinite duration, non-zero, then a fixed duration used.
[in] report_id If 0 (zero) the idle rate applies to all input reports generated by the device, otherwise ReportID
Returns
esp_err_t
Definition at line 1492 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_IDLE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), and hid_host_test_requests_callback().
hid_class_request_set_protocol()
esp_err_t hid_class_request_set_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t protocol)
HID class specific request SET PROTOCOL.
Parameters
[in] hid_dev_handle HID Device handle
[in] protocol HID report protocol (boot or report)
Returns
esp_err_t
Definition at line 1511 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_PROTOCOL, HID_RETURN_ON_INVALID_ARG, and protocol.
Referenced by ps4::hid_host_device_event(), and hid_host_test_requests_callback().
hid_class_request_set_report()
esp_err_t hid_class_request_set_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t * report, size_t report_length)
HID class specific request SET REPORT.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_type Report type
[in] report_id Report ID
[in] report Pointer to a buffer with report data
[in] report_length Report data length
Returns
esp_err_t
Definition at line 1471 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_REPORT, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_host_device_close()
esp_err_t hid_host_device_close (hid_host_device_handle_t hid_dev_handle)
USB HID Host close device.
Parameters
[in] hid_dev_handle Handle of the HID device to close
Returns
esp_err_t
Definition at line 1196 of file hid_host.c.
References HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_HOST_INTERFACE_EVENT_DISCONNECTED, HID_INTERFACE_STATE_ACTIVE, HID_INTERFACE_STATE_READY, HID_INTERFACE_STATE_WAIT_USER_DELETION, HID_RETURN_ON_ERROR, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_interface_callback(), and hid_host_test_interface_callback().
hid_host_device_get_params()
esp_err_t hid_host_device_get_params (hid_host_device_handle_t hid_dev_handle, hid_host_dev_params_t * dev_params)
HID Device get parameters by handle.
Parameters
[in] hid_dev_handle HID Device handle
[out] dev_params Pointer to a dev_params struct to fill
Returns
esp_err_t
Definition at line 1258 of file hid_host.c.
References HID_RETURN_ON_FALSE.
Referenced by access_task(), concurrent_task(), ps4::hid_host_device_event(), ps4::hid_host_interface_callback(), hid_host_test_callback(), hid_host_test_concurrent(), hid_host_test_interface_callback(), and hid_host_test_requests_callback().
hid_host_device_get_raw_input_report_data()
esp_err_t hid_host_device_get_raw_input_report_data (hid_host_device_handle_t hid_dev_handle, uint8_t * data, size_t data_length_max, size_t * data_length)
HID Host get device raw input report data pointer by handle.
This functions should be called after HID Interface device event HID_HOST_INTERFACE_EVENT_INPUT_REPORT to get the actual raw data of input report.
Parameters
[in] hid_dev_handle HID Device handle
[in] data Pointer to buffer where the input data will be copied
[in] data_length_max Max length of data can be copied to data buffer
[out] data_length Length of input report
Returns
esp_err_t
Definition at line 1275 of file hid_host.c.
References HID_RETURN_ON_FALSE.
Referenced by ps4::hid_host_interface_callback(), and hid_host_test_interface_callback().
hid_host_device_open()
esp_err_t hid_host_device_open (hid_host_device_handle_t hid_dev_handle, const hid_host_device_config_t * config)
USB HID Host open a device with specific device parameters.
Parameters
[in] iface_handle Handle of the HID device to open
[in] config Configuration structure HID device to open
Returns
esp_err_t
Definition at line 1165 of file hid_host.c.
References config, HID_INTERFACE_STATE_IDLE, HID_PROTOCOL_MAX, HID_PROTOCOL_NONE, HID_RETURN_ON_ERROR, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), hid_host_test_callback(), hid_host_test_concurrent(), and hid_host_test_requests_callback().
hid_host_device_start()
esp_err_t hid_host_device_start (hid_host_device_handle_t hid_dev_handle)
HID Host start awaiting event from a device by handle.
Calls a callback when the HID Interface event has occurred.
Parameters
[in] hid_dev_handle HID Device handle
Returns
esp_err_t
Definition at line 1304 of file hid_host.c.
References DEFAULT_TIMEOUT_MS, HID_INTERFACE_STATE_ACTIVE, HID_INTERFACE_STATE_READY, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), hid_host_test_callback(), hid_host_test_concurrent(), and hid_host_test_requests_callback().
hid_host_device_stop()
esp_err_t hid_host_device_stop (hid_host_device_handle_t hid_dev_handle)
HID Host stop device.
Parameters
[in] hid_dev_handle HID Device handle
Returns
esp_err_t
Definition at line 1334 of file hid_host.c.
References HID_RETURN_ON_INVALID_ARG.
hid_host_get_device_info()
esp_err_t hid_host_get_device_info (hid_host_device_handle_t hid_dev_handle, hid_host_dev_info_t * hid_dev_info)
HID Host Get device information.
Parameters
[in] hid_dev_handle HID Device handle
Definition at line 1367 of file hid_host.c.
References HID_RETURN_ON_ERROR, HID_RETURN_ON_INVALID_ARG, hid_host_dev_info_t::iManufacturer, hid_host_dev_info_t::iProduct, hid_host_dev_info_t::iSerialNumber, hid_host_dev_info_t::PID, and hid_host_dev_info_t::VID.
Referenced by hid_host_test_requests_callback().
hid_host_get_report_descriptor()
uint8_t * hid_host_get_report_descriptor (hid_host_device_handle_t hid_dev_handle, size_t * report_desc_len)
HID Host Get Report Descriptor.
Parameters
[in] hid_dev_handle HID Device handle
[out] report_desc_len Length of report descriptor
Returns
a uint8_t pointer to report descriptor data
Definition at line 1343 of file hid_host.c.
Referenced by access_task(), concurrent_task(), and hid_host_test_requests_callback().
hid_host_handle_events()
esp_err_t hid_host_handle_events (uint32_t timeout)
HID Host USB event handler.
If HID Host install was made with create_background_task=false configuration, application needs to handle USB Host events itself. Do not used if HID host install was made with create_background_task=true configuration
Parameters
[in] timeout Timeout in ticks. For milliseconds, please use 'pdMS_TO_TICKS()' macros
Returns
esp_err_t
Definition at line 1242 of file hid_host.c.
References HID_RETURN_ON_FALSE, and timeout.
Referenced by hid_host_test_polling_task().
hid_host_install()
esp_err_t hid_host_install (const hid_host_driver_config_t * config)
USB HID Host install USB Host HID Class driver.
Parameters
[in] config configuration structure HID to create
Returns
esp_err_r
Definition at line 1055 of file hid_host.c.
References config, HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_GOTO_ON_ERROR, HID_GOTO_ON_FALSE, HID_GOTO_ON_FALSE_CRITICAL, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::ps4(), and test_hid_setup().
hid_host_uninstall()
esp_err_t hid_host_uninstall (void)
USB HID Host uninstall HID Class driver.
Returns
esp_err_t
Definition at line 1136 of file hid_host.c.
References HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_RETURN_ON_FALSE, and HID_RETURN_ON_FALSE_CRITICAL.
Referenced by test_hid_teardown().