Kicker Controller: managed_components/espressif__usb_host_hid/include/usb/hid_host.h File Reference
hid_host.h File Reference
#include <wchar.h>
#include <stdint.h>
#include "esp_err.h"
#include <freertos/FreeRTOS.h>
#include "hid.h"
Classes
struct hid_host_dev_info_t
HID device descriptor common data.
struct hid_host_dev_params_t
USB HID Host device parameters.
struct hid_host_driver_config_t
HID configuration structure.
struct hid_host_device_config_t
HID device configuration structure (HID Interface)
Macros
#define HID_STR_DESC_MAX_LENGTH 32
USB HID HOST string descriptor maximal length.
Typedefs
typedef struct hid_interface * hid_host_device_handle_t
typedef void(* hid_host_driver_event_cb_t) (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
USB HID driver event callback.
typedef void(* hid_host_interface_event_cb_t) (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void *arg)
USB HID Interface event callback.
Enumerations
enum hid_host_driver_event_t { HID_HOST_DRIVER_EVENT_CONNECTED = 0x00 }
USB HID HOST Device event id.
enum hid_host_interface_event_t { HID_HOST_INTERFACE_EVENT_INPUT_REPORT = 0x00 , HID_HOST_INTERFACE_EVENT_TRANSFER_ERROR , HID_HOST_INTERFACE_EVENT_DISCONNECTED }
USB HID HOST Interface event id.
Functions
esp_err_t hid_host_install (const hid_host_driver_config_t *config)
USB HID Host install USB Host HID Class driver.
esp_err_t hid_host_uninstall (void)
USB HID Host uninstall HID Class driver.
esp_err_t hid_host_device_open (hid_host_device_handle_t hid_dev_handle, const hid_host_device_config_t *config)
USB HID Host open a device with specific device parameters.
esp_err_t hid_host_device_close (hid_host_device_handle_t hid_dev_handle)
USB HID Host close device.
esp_err_t hid_host_handle_events (uint32_t timeout)
HID Host USB event handler.
esp_err_t hid_host_device_get_params (hid_host_device_handle_t hid_dev_handle, hid_host_dev_params_t *dev_params)
HID Device get parameters by handle.
esp_err_t hid_host_device_get_raw_input_report_data (hid_host_device_handle_t hid_dev_handle, uint8_t *data, size_t data_length_max, size_t *data_length)
HID Host get device raw input report data pointer by handle.
esp_err_t hid_host_device_start (hid_host_device_handle_t hid_dev_handle)
HID Host start awaiting event from a device by handle.
esp_err_t hid_host_device_stop (hid_host_device_handle_t hid_dev_handle)
HID Host stop device.
uint8_t * hid_host_get_report_descriptor (hid_host_device_handle_t hid_dev_handle, size_t *report_desc_len)
HID Host Get Report Descriptor.
esp_err_t hid_host_get_device_info (hid_host_device_handle_t hid_dev_handle, hid_host_dev_info_t *hid_dev_info)
HID Host Get device information.
esp_err_t hid_class_request_get_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t *report, size_t *report_length)
HID class specific request GET REPORT.
esp_err_t hid_class_request_get_idle (hid_host_device_handle_t hid_dev_handle, uint8_t report_id, uint8_t *idle_rate)
HID class specific request GET IDLE.
esp_err_t hid_class_request_get_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t *protocol)
HID class specific request GET PROTOCOL.
esp_err_t hid_class_request_set_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t *report, size_t report_length)
HID class specific request SET REPORT.
esp_err_t hid_class_request_set_idle (hid_host_device_handle_t hid_dev_handle, uint8_t duration, uint8_t report_id)
HID class specific request SET IDLE.
esp_err_t hid_class_request_set_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t protocol)
HID class specific request SET PROTOCOL.
Macro Definition Documentation
HID_STR_DESC_MAX_LENGTH
#define HID_STR_DESC_MAX_LENGTH 32
USB HID HOST string descriptor maximal length.
The maximum possible number of characters in an embedded string is device specific. For USB devices, the maximum string length is 126 wide characters (not including the terminating NULL character). This is a length, which is available to upper level application during getting information of HID Device with 'hid_host_get_device_info' call.
To decrease memory usage 32 wide characters (64 bytes per every string) is used.
Definition at line 30 of file hid_host.h.
Typedef Documentation
hid_host_device_handle_t
typedef struct hid_interface* hid_host_device_handle_t
Device Handle. Handle to a particular HID interface
Definition at line 32 of file hid_host.h.
hid_host_driver_event_cb_t
typedef void(* hid_host_driver_event_cb_t) (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
USB HID driver event callback.
Parameters
[in] hid_handle HID device handle (HID Interface)
[in] event HID driver event
[in] arg User argument from HID driver configuration structure
Definition at line 81 of file hid_host.h.
hid_host_interface_event_cb_t
typedef void(* hid_host_interface_event_cb_t) (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void *arg)
USB HID Interface event callback.
Parameters
[in] hid_device_handle HID device handle (HID Interface)
[in] event HID Interface event
[in] arg User argument
Definition at line 92 of file hid_host.h.
Enumeration Type Documentation
hid_host_driver_event_t
enum hid_host_driver_event_t
USB HID HOST Device event id.
Enumerator
HID_HOST_DRIVER_EVENT_CONNECTED
HID Device has been found in connected USB device (at least one)
Definition at line 38 of file hid_host.h.
hid_host_interface_event_t
enum hid_host_interface_event_t
USB HID HOST Interface event id.
Enumerator
HID_HOST_INTERFACE_EVENT_INPUT_REPORT
HID Device input report
HID_HOST_INTERFACE_EVENT_TRANSFER_ERROR
HID Device transfer error
HID_HOST_INTERFACE_EVENT_DISCONNECTED
HID Device has been disconnected
Definition at line 45 of file hid_host.h.
Function Documentation
hid_class_request_get_idle()
esp_err_t hid_class_request_get_idle (hid_host_device_handle_t hid_dev_handle, uint8_t report_id, uint8_t * idle_rate)
HID class specific request GET IDLE.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_id ReportID
[out] idle_rate Idle rate [ms]
Returns
esp_err_t
Definition at line 1419 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_IDLE, HID_RETURN_ON_ERROR, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_class_request_get_protocol()
esp_err_t hid_class_request_get_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t * protocol)
HID class specific request GET PROTOCOL.
Parameters
[in] hid_dev_handle HID Device handle
[out] protocol Pointer to HID report protocol (boot or report) of device
Returns
esp_err_t
Definition at line 1446 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_PROTOCOL, HID_RETURN_ON_ERROR, HID_RETURN_ON_INVALID_ARG, and protocol.
Referenced by hid_host_test_requests_callback().
hid_class_request_get_report()
esp_err_t hid_class_request_get_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t * report, size_t * report_length)
HID class specific request GET REPORT.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_id Report ID
[out] report Pointer to buffer for a report data
[in/out] report_length Report data length, before the get report contain the maximum value of a report buffer. After get report there is a value of actual data in report buffer.
Returns
esp_err_t
Definition at line 1397 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_GET_REPORT, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_class_request_set_idle()
esp_err_t hid_class_request_set_idle (hid_host_device_handle_t hid_dev_handle, uint8_t duration, uint8_t report_id)
HID class specific request SET IDLE.
Parameters
[in] hid_dev_handle HID Device handle
[in] duration 0 (zero) for the indefinite duration, non-zero, then a fixed duration used.
[in] report_id If 0 (zero) the idle rate applies to all input reports generated by the device, otherwise ReportID
Returns
esp_err_t
Definition at line 1492 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_IDLE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), and hid_host_test_requests_callback().
hid_class_request_set_protocol()
esp_err_t hid_class_request_set_protocol (hid_host_device_handle_t hid_dev_handle, hid_report_protocol_t protocol)
HID class specific request SET PROTOCOL.
Parameters
[in] hid_dev_handle HID Device handle
[in] protocol HID report protocol (boot or report)
Returns
esp_err_t
Definition at line 1511 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_PROTOCOL, HID_RETURN_ON_INVALID_ARG, and protocol.
Referenced by ps4::hid_host_device_event(), and hid_host_test_requests_callback().
hid_class_request_set_report()
esp_err_t hid_class_request_set_report (hid_host_device_handle_t hid_dev_handle, uint8_t report_type, uint8_t report_id, uint8_t * report, size_t report_length)
HID class specific request SET REPORT.
Parameters
[in] hid_dev_handle HID Device handle
[in] report_type Report type
[in] report_id Report ID
[in] report Pointer to a buffer with report data
[in] report_length Report data length
Returns
esp_err_t
Definition at line 1471 of file hid_host.c.
References HID_CLASS_SPECIFIC_REQ_SET_REPORT, and HID_RETURN_ON_INVALID_ARG.
Referenced by hid_host_test_requests_callback().
hid_host_device_close()
esp_err_t hid_host_device_close (hid_host_device_handle_t hid_dev_handle)
USB HID Host close device.
Parameters
[in] hid_dev_handle Handle of the HID device to close
Returns
esp_err_t
Definition at line 1196 of file hid_host.c.
References HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_HOST_INTERFACE_EVENT_DISCONNECTED, HID_INTERFACE_STATE_ACTIVE, HID_INTERFACE_STATE_READY, HID_INTERFACE_STATE_WAIT_USER_DELETION, HID_RETURN_ON_ERROR, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_interface_callback(), and hid_host_test_interface_callback().
hid_host_device_get_params()
esp_err_t hid_host_device_get_params (hid_host_device_handle_t hid_dev_handle, hid_host_dev_params_t * dev_params)
HID Device get parameters by handle.
Parameters
[in] hid_dev_handle HID Device handle
[out] dev_params Pointer to a dev_params struct to fill
Returns
esp_err_t
Definition at line 1258 of file hid_host.c.
References HID_RETURN_ON_FALSE.
Referenced by access_task(), concurrent_task(), ps4::hid_host_device_event(), ps4::hid_host_interface_callback(), hid_host_test_callback(), hid_host_test_concurrent(), hid_host_test_interface_callback(), and hid_host_test_requests_callback().
hid_host_device_get_raw_input_report_data()
esp_err_t hid_host_device_get_raw_input_report_data (hid_host_device_handle_t hid_dev_handle, uint8_t * data, size_t data_length_max, size_t * data_length)
HID Host get device raw input report data pointer by handle.
This functions should be called after HID Interface device event HID_HOST_INTERFACE_EVENT_INPUT_REPORT to get the actual raw data of input report.
Parameters
[in] hid_dev_handle HID Device handle
[in] data Pointer to buffer where the input data will be copied
[in] data_length_max Max length of data can be copied to data buffer
[out] data_length Length of input report
Returns
esp_err_t
Definition at line 1275 of file hid_host.c.
References HID_RETURN_ON_FALSE.
Referenced by ps4::hid_host_interface_callback(), and hid_host_test_interface_callback().
hid_host_device_open()
esp_err_t hid_host_device_open (hid_host_device_handle_t hid_dev_handle, const hid_host_device_config_t * config)
USB HID Host open a device with specific device parameters.
Parameters
[in] iface_handle Handle of the HID device to open
[in] config Configuration structure HID device to open
Returns
esp_err_t
Definition at line 1165 of file hid_host.c.
References config, HID_INTERFACE_STATE_IDLE, HID_PROTOCOL_MAX, HID_PROTOCOL_NONE, HID_RETURN_ON_ERROR, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), hid_host_test_callback(), hid_host_test_concurrent(), and hid_host_test_requests_callback().
hid_host_device_start()
esp_err_t hid_host_device_start (hid_host_device_handle_t hid_dev_handle)
HID Host start awaiting event from a device by handle.
Calls a callback when the HID Interface event has occurred.
Parameters
[in] hid_dev_handle HID Device handle
Returns
esp_err_t
Definition at line 1304 of file hid_host.c.
References DEFAULT_TIMEOUT_MS, HID_INTERFACE_STATE_ACTIVE, HID_INTERFACE_STATE_READY, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::hid_host_device_event(), hid_host_test_callback(), hid_host_test_concurrent(), and hid_host_test_requests_callback().
hid_host_device_stop()
esp_err_t hid_host_device_stop (hid_host_device_handle_t hid_dev_handle)
HID Host stop device.
Parameters
[in] hid_dev_handle HID Device handle
Returns
esp_err_t
Definition at line 1334 of file hid_host.c.
References HID_RETURN_ON_INVALID_ARG.
hid_host_get_device_info()
esp_err_t hid_host_get_device_info (hid_host_device_handle_t hid_dev_handle, hid_host_dev_info_t * hid_dev_info)
HID Host Get device information.
Parameters
[in] hid_dev_handle HID Device handle
Definition at line 1367 of file hid_host.c.
References HID_RETURN_ON_ERROR, HID_RETURN_ON_INVALID_ARG, hid_host_dev_info_t::iManufacturer, hid_host_dev_info_t::iProduct, hid_host_dev_info_t::iSerialNumber, hid_host_dev_info_t::PID, and hid_host_dev_info_t::VID.
Referenced by hid_host_test_requests_callback().
hid_host_get_report_descriptor()
uint8_t * hid_host_get_report_descriptor (hid_host_device_handle_t hid_dev_handle, size_t * report_desc_len)
HID Host Get Report Descriptor.
Parameters
[in] hid_dev_handle HID Device handle
[out] report_desc_len Length of report descriptor
Returns
a uint8_t pointer to report descriptor data
Definition at line 1343 of file hid_host.c.
Referenced by access_task(), concurrent_task(), and hid_host_test_requests_callback().
hid_host_handle_events()
esp_err_t hid_host_handle_events (uint32_t timeout)
HID Host USB event handler.
If HID Host install was made with create_background_task=false configuration, application needs to handle USB Host events itself. Do not used if HID host install was made with create_background_task=true configuration
Parameters
[in] timeout Timeout in ticks. For milliseconds, please use 'pdMS_TO_TICKS()' macros
Returns
esp_err_t
Definition at line 1242 of file hid_host.c.
References HID_RETURN_ON_FALSE, and timeout.
Referenced by hid_host_test_polling_task().
hid_host_install()
esp_err_t hid_host_install (const hid_host_driver_config_t * config)
USB HID Host install USB Host HID Class driver.
Parameters
[in] config configuration structure HID to create
Returns
esp_err_r
Definition at line 1055 of file hid_host.c.
References config, HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_GOTO_ON_ERROR, HID_GOTO_ON_FALSE, HID_GOTO_ON_FALSE_CRITICAL, HID_RETURN_ON_FALSE, and HID_RETURN_ON_INVALID_ARG.
Referenced by ps4::ps4(), and test_hid_setup().
hid_host_uninstall()
esp_err_t hid_host_uninstall (void)
USB HID Host uninstall HID Class driver.
Returns
esp_err_t
Definition at line 1136 of file hid_host.c.
References HID_ENTER_CRITICAL, HID_EXIT_CRITICAL, HID_RETURN_ON_FALSE, and HID_RETURN_ON_FALSE_CRITICAL.
Referenced by test_hid_teardown().