Kicker Controller: managed_components/espressif__esp-now/examples/solution/components/espnow_device/include/initiator.h File Reference
initiator.h File Reference
Functions
void app_espnow_initiator_register ()
void app_espnow_initiator ()
Function Documentation
app_espnow_initiator()
void app_espnow_initiator ()
Definition at line 248 of file initiator.c.
References espnow_console_commands_register(), espnow_console_init(), ESPNOW_DATA_TYPE_DEBUG_LOG, and espnow_set_config_for_data_type().
Referenced by app_main().
app_espnow_initiator_register()
void app_espnow_initiator_register ()
Definition at line 238 of file initiator.c.
Referenced by app_main().