Kicker Controller: managed_components/espressif__esp-now/examples/wireless_debug/components/espnow_device/monitor.c File Reference
monitor.c File Reference
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_spiffs.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "espnow.h"
#include "espnow_cmd.h"
#include "espnow_console.h"
#include "espnow_ctrl.h"
#include "espnow_log.h"
#include "espnow_ota.h"
#include "espnow_prov.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
#include "sdcard.h"
#include "mdns.h"
#include "lwip/apps/netbiosns.h"
#include "web_server.h"
Functions
void app_espnow_monitor_device_start ()
Function Documentation
app_espnow_monitor_device_start()
void app_espnow_monitor_device_start ()
Set the log level for serial port printing.
Add debug function, you can use serial command and wireless debugging
< CONFIG_APP_WEB_SERVER
Receive esp-now data from other device
Definition at line 238 of file monitor.c.
References espnow_console_commands_register(), espnow_console_init(), ESPNOW_DATA_TYPE_DEBUG_LOG, espnow_init(), ESPNOW_INIT_CONFIG_DEFAULT, espnow_set_config_for_data_type(), espnow_storage_init(), and espnow_config_t::qsize.
Referenced by app_main().