Kicker Controller: configuration Namespace Reference
configuration Namespace Reference
Classes
class libraries_c
class library_c
class object_c
class paths_c
class sdkconfig_c
Functions
generator (library_file, object_file, function_file, sdkconfig_file, missing_function_info, objdump='riscv32-esp-elf-objdump')
main ()
Variables
int OPT_MIN_LEN = 7
espidf_objdump = None
bool espidf_missing_function_info = True
Function Documentation
generator()
configuration.generator (library_file, object_file, function_file, sdkconfig_file, missing_function_info, objdump = 'riscv32-esp-elf-objdump')
Definition at line 155 of file configuration.py.
Referenced by main().
main()
configuration.main ()
Definition at line 182 of file configuration.py.
References generator(), and main().
Referenced by main().
Variable Documentation
espidf_missing_function_info
bool configuration.espidf_missing_function_info = True
Definition at line 18 of file configuration.py.
espidf_objdump
configuration.espidf_objdump = None
Definition at line 17 of file configuration.py.
OPT_MIN_LEN
int configuration.OPT_MIN_LEN = 7
Definition at line 15 of file configuration.py.