Kicker Controller: relinker Namespace Reference
relinker Namespace Reference
Classes
class filter_c
class relink_c
class target_c
Functions
lib_secs (lib, file, lib_path)
filter_secs (secs_a, secs_b)
strip_secs (secs_a, secs_b)
func2sect (func)
main ()
Variables
espidf_objdump = None
Function Documentation
filter_secs()
relinker.filter_secs (secs_a, secs_b)
Definition at line 40 of file relinker.py.
References list.
Referenced by relinker.relink_c.__transform__().
func2sect()
relinker.func2sect (func)
Definition at line 53 of file relinker.py.
References list.
lib_secs()
relinker.lib_secs (lib, file, lib_path)
Definition at line 23 of file relinker.py.
References len.
main()
relinker.main ()
Definition at line 239 of file relinker.py.
References main().
Referenced by main().
strip_secs()
relinker.strip_secs (secs_a, secs_b)
Definition at line 48 of file relinker.py.
References list, and set.
Variable Documentation
espidf_objdump
relinker.espidf_objdump = None
Definition at line 21 of file relinker.py.