Kicker Controller: gen_custom_ota Namespace Reference
gen_custom_ota Namespace Reference
Functions
xz_compress (store_directory, in_file)
secure_boot_sign (sign_key, in_file, out_file)
get_app_name ()
get_script_version ()
main ()
Variables
dict binary_compress_type = {'none': 0, 'xz':1}
dict header_version = {'v1': 1, 'v2': 2, 'v3': 3}
str SCRIPT_VERSION = '1.0.0'
int ORIGIN_APP_IMAGE_HEADER_LEN = 288
int OLD_APP_CHECK_DATA_SIZE = 4096
Function Documentation
get_app_name()
gen_custom_ota.get_app_name ()
Definition at line 98 of file gen_custom_ota.py.
Referenced by main().
get_script_version()
gen_custom_ota.get_script_version ()
Definition at line 108 of file gen_custom_ota.py.
Referenced by main().
main()
gen_custom_ota.main ()
Definition at line 111 of file gen_custom_ota.py.
References get_app_name(), get_script_version(), main(), secure_boot_sign(), and xz_compress().
Referenced by main().
secure_boot_sign()
gen_custom_ota.secure_boot_sign (sign_key, in_file, out_file)
Definition at line 93 of file gen_custom_ota.py.
Referenced by main().
xz_compress()
gen_custom_ota.xz_compress (store_directory, in_file)
Definition at line 75 of file gen_custom_ota.py.
Referenced by main().
Variable Documentation
binary_compress_type
dict gen_custom_ota.binary_compress_type = {'none': 0, 'xz':1}
Definition at line 23 of file gen_custom_ota.py.
header_version
dict gen_custom_ota.header_version = {'v1': 1, 'v2': 2, 'v3': 3}
Definition at line 24 of file gen_custom_ota.py.
OLD_APP_CHECK_DATA_SIZE
int gen_custom_ota.OLD_APP_CHECK_DATA_SIZE = 4096
Definition at line 29 of file gen_custom_ota.py.
ORIGIN_APP_IMAGE_HEADER_LEN
int gen_custom_ota.ORIGIN_APP_IMAGE_HEADER_LEN = 288
Definition at line 27 of file gen_custom_ota.py.
SCRIPT_VERSION
str gen_custom_ota.SCRIPT_VERSION = '1.0.0'
Definition at line 26 of file gen_custom_ota.py.