Kicker Controller: managed_components/espressif__esp-now/examples/solution/components/espnow_device/responder.c File Reference
responder.c File Reference
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "espnow.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
Functions
void app_espnow_responder_register ()
void app_espnow_responder ()
Function Documentation
app_espnow_responder()
void app_espnow_responder ()
Definition at line 255 of file responder.c.
References APP_KEY_LEN, espnow_console_commands_register(), espnow_console_init(), espnow_get_key(), espnow_log_init(), espnow_ota_responder_start(), espnow_sec_responder_start(), espnow_set_dec_key(), espnow_set_key(), espnow_timesync_start(), and pop_data.
Referenced by app_main().
app_espnow_responder_register()
void app_espnow_responder_register ()
Definition at line 243 of file responder.c.
Referenced by app_main().