Kicker Controller: managed_components/espressif__esp-now/examples/security/main/app_main.c File Reference
app_main.c File Reference
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_random.h"
#include "espnow.h"
#include "espnow_security.h"
#include "espnow_security_handshake.h"
#include "espnow_storage.h"
#include "espnow_utils.h"
#include "driver/uart.h"
Macros
#define UART_PORT_NUM UART_NUM_0
#define UART_BAUD_RATE 115200
#define UART_TX_IO UART_PIN_NO_CHANGE
#define UART_RX_IO UART_PIN_NO_CHANGE
Functions
void app_main ()
Variables
const char * pop_data = CONFIG_APP_ESPNOW_SESSION_POP
Macro Definition Documentation
UART_BAUD_RATE
#define UART_BAUD_RATE 115200
Definition at line 34 of file app_main.c.
UART_PORT_NUM
#define UART_PORT_NUM UART_NUM_0
Definition at line 33 of file app_main.c.
UART_RX_IO
#define UART_RX_IO UART_PIN_NO_CHANGE
Definition at line 36 of file app_main.c.
UART_TX_IO
#define UART_TX_IO UART_PIN_NO_CHANGE
Definition at line 35 of file app_main.c.
Function Documentation
app_main()
void app_main (void)
Definition at line 166 of file app_main.c.
References APP_KEY_LEN, ESP_ERROR_GOTO, ESP_FREE, ESP_MALLOC, ESPNOW_ADDR_LEN, ESPNOW_DATA_TYPE_DATA, espnow_get_key(), espnow_init(), ESPNOW_INIT_CONFIG_DEFAULT, espnow_sec_initiator_result_free(), espnow_sec_initiator_scan(), espnow_sec_initiator_scan_result_free(), espnow_sec_initiator_start(), espnow_sec_responder_start(), espnow_set_config_for_data_type(), espnow_set_dec_key(), espnow_set_key(), espnow_storage_init(), mac, pop_data, espnow_config_t::sec_enable, espnow_sec_result_s::successed_num, and espnow_sec_result_s::unfinished_num.
Variable Documentation
pop_data
const char* pop_data = CONFIG_APP_ESPNOW_SESSION_POP
Definition at line 30 of file app_main.c.
Referenced by app_espnow_responder(), app_main(), espnow_sec_initiator_start(), and espnow_sec_responder_start().