Kicker Controller: managed_components/espressif__esp-now/examples/solution/main/app_main.c File Reference
app_main.c File Reference
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "espnow.h"
#include "espnow_utils.h"
#include "iot_button.h"
#include "led_strip.h"
#include <wifi_provisioning/manager.h>
Functions
void app_led_set_color (uint8_t red, uint8_t green, uint8_t blue)
void app_main ()
Function Documentation
app_led_set_color()
void app_led_set_color (uint8_t red, uint8_t green, uint8_t blue)
Definition at line 140 of file app_main.c.
app_main()
void app_main (void)
Definition at line 430 of file app_main.c.
References app_espnow_initiator(), app_espnow_initiator_register(), app_espnow_responder(), app_espnow_responder_register(), espnow_init(), ESPNOW_INIT_CONFIG_DEFAULT, espnow_storage_init(), espnow_config_t::qsize, and espnow_config_t::sec_enable.