Kicker Controller: managed_components/espressif__usb_host_hid/test_app/main/test_hid_basic.h File Reference
test_hid_basic.h File Reference
#include "usb/hid_host.h"
Enumerations
enum hid_test_event_handle_t { HID_TEST_EVENT_HANDLE_IN_DRIVER = 0 , HID_TEST_EVENT_HANDLE_EXTERNAL }
Functions
void test_hid_setup (hid_host_driver_event_cb_t device_callback, hid_test_event_handle_t hid_test_event_handle)
Setups HID testing.
void test_hid_teardown (void)
Teardowns HID testing.
Enumeration Type Documentation
hid_test_event_handle_t
enum hid_test_event_handle_t
Enumerator
HID_TEST_EVENT_HANDLE_IN_DRIVER
HID_TEST_EVENT_HANDLE_EXTERNAL
Definition at line 15 of file test_hid_basic.h.
Function Documentation
test_hid_setup()
void test_hid_setup (hid_host_driver_event_cb_t device_callback, hid_test_event_handle_t hid_test_event_handle)
Setups HID testing.
Create USB lib task
Install HID Host driver
Definition at line 520 of file test_hid_basic.c.
References hid_host_install(), and HID_TEST_EVENT_HANDLE_IN_DRIVER.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
test_hid_teardown()
void test_hid_teardown (void)
Teardowns HID testing.
Disconnect connected USB device manually by PHY triggering
Wait for USB lib task was closed
Uninstall HID Host driver
Clear the notification value to 0
Short delay to allow task to be cleaned up
Definition at line 554 of file test_hid_basic.c.
References hid_host_uninstall().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().