Kicker Controller: managed_components/espressif__usb_host_hid/test_app/main/test_hid_basic.c File Reference
test_hid_basic.c File Reference
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include "unity.h"
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "esp_private/usb_phy.h"
#include "usb/usb_host.h"
#include "usb/hid_host.h"
#include "usb/hid_usage_keyboard.h"
#include "usb/hid_usage_mouse.h"
#include "test_hid_basic.h"
#include "hid_mock_device.h"
Classes
struct hid_host_test_event_queue_t
Macros
#define MULTIPLE_TASKS_TASKS_NUM 10
Enumerations
enum hid_host_test_touch_way_t { HID_HOST_TEST_TOUCH_WAY_ASSERT = 0x00 , HID_HOST_TEST_TOUCH_WAY_SUDDEN_DISCONNECT = 0x01 }
Functions
void hid_host_test_interface_callback (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void *arg)
void hid_host_test_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
void hid_host_test_concurrent (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
void hid_host_test_device_callback_to_queue (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
void hid_host_test_requests_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void *arg)
void hid_host_test_task (void *pvParameters)
void hid_host_test_polling_task (void *pvParameters)
void concurrent_task (void *arg)
void access_task (void *arg)
void test_multiple_tasks_access (void)
Creates MULTIPLE_TASKS_TASKS_NUM to get report descriptor and get protocol from HID device. After test_num_passed - is a global static variable that increases during every successful task test.
void test_task_access (void)
void test_hid_setup (hid_host_driver_event_cb_t device_callback, hid_test_event_handle_t hid_test_event_handle)
Setups HID testing.
void test_hid_teardown (void)
Teardowns HID testing.
TEST_CASE ("memory_leakage", "[hid_host]")
TEST_CASE ("multiple_task_access", "[hid_host]")
TEST_CASE ("class_specific_requests", "[hid_host]")
TEST_CASE ("class_specific_requests_with_external_polling", "[hid_host]")
TEST_CASE ("class_specific_requests_with_external_polling_without_polling", "[hid_host]")
TEST_CASE ("sudden_disconnect", "[hid_host]")
TEST_CASE ("mock_hid_device", "[hid_device][ignore]")
TEST_CASE ("mock_hid_device_with_two_ifaces", "[hid_device2][ignore]")
Variables
QueueHandle_t hid_host_test_event_queue
TaskHandle_t hid_test_task_handle
Macro Definition Documentation
MULTIPLE_TASKS_TASKS_NUM
#define MULTIPLE_TASKS_TASKS_NUM 10
Definition at line 397 of file test_hid_basic.c.
Referenced by TEST_CASE(), and test_multiple_tasks_access().
Enumeration Type Documentation
hid_host_test_touch_way_t
enum hid_host_test_touch_way_t
Enumerator
HID_HOST_TEST_TOUCH_WAY_ASSERT
HID_HOST_TEST_TOUCH_WAY_SUDDEN_DISCONNECT
Definition at line 59 of file test_hid_basic.c.
Function Documentation
access_task()
void access_task (void * arg)
Definition at line 416 of file test_hid_basic.c.
References hid_host_device_get_params(), hid_host_get_report_descriptor(), and HID_HOST_TEST_TOUCH_WAY_ASSERT.
Referenced by test_task_access().
concurrent_task()
void concurrent_task (void * arg)
Definition at line 399 of file test_hid_basic.c.
References hid_host_device_get_params(), hid_host_get_report_descriptor(), and HID_HOST_TEST_TOUCH_WAY_ASSERT.
Referenced by test_multiple_tasks_access().
hid_host_test_callback()
void hid_host_test_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg)
Definition at line 115 of file test_hid_basic.c.
References hid_host_dev_params_t::addr, hid_host_device_get_params(), hid_host_device_open(), hid_host_device_start(), HID_HOST_DRIVER_EVENT_CONNECTED, hid_host_test_interface_callback(), hid_host_dev_params_t::iface_num, hid_host_dev_params_t::proto, and hid_host_dev_params_t::sub_class.
Referenced by TEST_CASE().
hid_host_test_concurrent()
void hid_host_test_concurrent (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg)
Definition at line 146 of file test_hid_basic.c.
References hid_host_dev_params_t::addr, hid_host_device_get_params(), hid_host_device_open(), hid_host_device_start(), HID_HOST_DRIVER_EVENT_CONNECTED, hid_host_test_interface_callback(), hid_host_dev_params_t::iface_num, hid_host_dev_params_t::proto, and hid_host_dev_params_t::sub_class.
Referenced by TEST_CASE(), and TEST_CASE().
hid_host_test_device_callback_to_queue()
void hid_host_test_device_callback_to_queue (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg)
Definition at line 178 of file test_hid_basic.c.
References hid_host_test_event_queue.
Referenced by TEST_CASE(), TEST_CASE(), and TEST_CASE().
hid_host_test_interface_callback()
void hid_host_test_interface_callback (hid_host_device_handle_t hid_device_handle, const hid_host_interface_event_t event, void * arg)
Definition at line 74 of file test_hid_basic.c.
References hid_host_dev_params_t::addr, hid_host_device_close(), hid_host_device_get_params(), hid_host_device_get_raw_input_report_data(), HID_HOST_INTERFACE_EVENT_DISCONNECTED, HID_HOST_INTERFACE_EVENT_INPUT_REPORT, HID_HOST_INTERFACE_EVENT_TRANSFER_ERROR, and hid_host_dev_params_t::iface_num.
Referenced by hid_host_test_callback(), hid_host_test_concurrent(), and hid_host_test_requests_callback().
hid_host_test_polling_task()
void hid_host_test_polling_task (void * pvParameters)
Definition at line 342 of file test_hid_basic.c.
References hid_host_handle_events().
hid_host_test_requests_callback()
void hid_host_test_requests_callback (hid_host_device_handle_t hid_device_handle, const hid_host_driver_event_t event, void * arg)
Definition at line 190 of file test_hid_basic.c.
References hid_host_dev_params_t::addr, hid_class_request_get_idle(), hid_class_request_get_protocol(), hid_class_request_get_report(), hid_class_request_set_idle(), hid_class_request_set_protocol(), hid_class_request_set_report(), hid_host_device_get_params(), hid_host_device_open(), hid_host_device_start(), HID_HOST_DRIVER_EVENT_CONNECTED, hid_host_get_device_info(), hid_host_get_report_descriptor(), hid_host_test_interface_callback(), HID_PROTOCOL_KEYBOARD, HID_PROTOCOL_MOUSE, HID_PROTOCOL_NONE, HID_REPORT_PROTOCOL_BOOT, HID_REPORT_TYPE_INPUT, HID_REPORT_TYPE_OUTPUT, hid_host_dev_params_t::iface_num, hid_host_dev_info_t::iManufacturer, hid_host_dev_info_t::iProduct, hid_host_dev_info_t::iSerialNumber, hid_host_dev_info_t::PID, hid_host_dev_params_t::proto, hid_host_dev_params_t::sub_class, and hid_host_dev_info_t::VID.
Referenced by hid_host_test_task().
hid_host_test_task()
void hid_host_test_task (void * pvParameters)
Definition at line 322 of file test_hid_basic.c.
References hid_host_test_event_queue_t::arg, hid_host_test_event_queue_t::event, hid_host_test_event_queue_t::hid_device_handle, hid_host_test_event_queue, and hid_host_test_requests_callback().
TEST_CASE() [1/8]
TEST_CASE ("class_specific_requests" , "" [hid_host])
Definition at line 613 of file test_hid_basic.c.
References hid_host_test_device_callback_to_queue(), HID_TEST_EVENT_HANDLE_IN_DRIVER, test_hid_setup(), and test_hid_teardown().
TEST_CASE() [2/8]
TEST_CASE ("class_specific_requests_with_external_polling" , "" [hid_host])
Definition at line 627 of file test_hid_basic.c.
References hid_host_test_device_callback_to_queue(), HID_TEST_EVENT_HANDLE_EXTERNAL, test_hid_setup(), and test_hid_teardown().
TEST_CASE() [3/8]
TEST_CASE ("class_specific_requests_with_external_polling_without_polling" , "" [hid_host])
Definition at line 643 of file test_hid_basic.c.
References hid_host_test_device_callback_to_queue(), HID_TEST_EVENT_HANDLE_EXTERNAL, test_hid_setup(), and test_hid_teardown().
TEST_CASE() [4/8]
TEST_CASE ("memory_leakage" , "" [hid_host])
Definition at line 587 of file test_hid_basic.c.
References hid_host_test_callback(), HID_TEST_EVENT_HANDLE_IN_DRIVER, test_hid_setup(), and test_hid_teardown().
TEST_CASE() [5/8]
TEST_CASE ("mock_hid_device" , "" [hid_device][ignore])
Definition at line 670 of file test_hid_basic.c.
References hid_mock_device(), and TUSB_IFACE_COUNT_ONE.
TEST_CASE() [6/8]
TEST_CASE ("mock_hid_device_with_two_ifaces" , "" [hid_device2][ignore])
Definition at line 678 of file test_hid_basic.c.
References hid_mock_device(), and TUSB_IFACE_COUNT_TWO.
TEST_CASE() [7/8]
TEST_CASE ("multiple_task_access" , "" [hid_host])
Definition at line 596 of file test_hid_basic.c.
References hid_host_test_concurrent(), HID_TEST_EVENT_HANDLE_IN_DRIVER, MULTIPLE_TASKS_TASKS_NUM, test_hid_setup(), test_hid_teardown(), and test_multiple_tasks_access().
TEST_CASE() [8/8]
TEST_CASE ("sudden_disconnect" , "" [hid_host])
Definition at line 658 of file test_hid_basic.c.
References hid_host_test_concurrent(), HID_TEST_EVENT_HANDLE_IN_DRIVER, test_hid_setup(), test_hid_teardown(), and test_task_access().
test_hid_setup()
void test_hid_setup (hid_host_driver_event_cb_t device_callback, hid_test_event_handle_t hid_test_event_handle)
Setups HID testing.
Create USB lib task
Install HID Host driver
Definition at line 520 of file test_hid_basic.c.
References hid_host_install(), and HID_TEST_EVENT_HANDLE_IN_DRIVER.
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
test_hid_teardown()
void test_hid_teardown (void)
Teardowns HID testing.
Disconnect connected USB device manually by PHY triggering
Wait for USB lib task was closed
Uninstall HID Host driver
Clear the notification value to 0
Short delay to allow task to be cleaned up
Definition at line 554 of file test_hid_basic.c.
References hid_host_uninstall().
Referenced by TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), TEST_CASE(), and TEST_CASE().
test_multiple_tasks_access()
void test_multiple_tasks_access (void)
Creates MULTIPLE_TASKS_TASKS_NUM to get report descriptor and get protocol from HID device. After test_num_passed - is a global static variable that increases during every successful task test.
Definition at line 438 of file test_hid_basic.c.
References concurrent_task(), and MULTIPLE_TASKS_TASKS_NUM.
Referenced by TEST_CASE().
test_task_access()
void test_task_access (void)
Definition at line 448 of file test_hid_basic.c.
References access_task().
Referenced by TEST_CASE().
Variable Documentation
hid_host_test_event_queue
QueueHandle_t hid_host_test_event_queue
Definition at line 35 of file test_hid_basic.c.
Referenced by hid_host_test_device_callback_to_queue(), and hid_host_test_task().
hid_test_task_handle
TaskHandle_t hid_test_task_handle
Definition at line 36 of file test_hid_basic.c.