Kicker Controller: managed_components/espressif__cmake_utilities/test_apps/components/TEST-component2/test_component2.h File Reference
test_component2.h File Reference
#include <stdio.h>
Functions
int test_component2_version_major ()
int test_component2_version_minor ()
int test_component2_version_patch ()
Function Documentation
test_component2_version_major()
int test_component2_version_major ()
Definition at line 3 of file test_component2.c.
Referenced by TEST_CASE().
test_component2_version_minor()
int test_component2_version_minor ()
Definition at line 8 of file test_component2.c.
Referenced by TEST_CASE().
test_component2_version_patch()
int test_component2_version_patch ()
Definition at line 13 of file test_component2.c.
Referenced by TEST_CASE().