Kicker Mainbaord: oDrive Class Reference
oDrive Class Reference
This is the class to control an odrive motor controller.
#include <oDrive.h>
Public Member Functions
oDrive (uint8_t node_IDV)
The constructor for the Odrive class.
void send_message (const uint8_t message_ID, const uint8_t *message_contents, uint8_t message_length, const bool data_returned)
send a command to the Odrive
Private Member Functions
void update_battery_voltage (twai_message_t rx_message)
the function that is called to update the display's battery voltage
void receive_message (uint8_t message_ID)
the function that handles when a message needs to be received from the Odrive
void clear_battery_voltage ()
the function that is called when something has gone wrong, and no message is received when Get_Bus_Voltage_Current is called
void update_current_motor_velocity (twai_message_t rx_message)
Read the motor velocity from an odrive.
Private Attributes
uint8_t node_ID
node id as set in the Odrive configurator
Detailed Description
This is the class to control an odrive motor controller.
Definition at line 35 of file oDrive.h.
Constructor & Destructor Documentation
oDrive()
oDrive::oDrive (uint8_t node_IDV)
The constructor for the Odrive class.
Parameters
node_IDV : uint8_t the value of the node id to have commands sent to
Definition at line 12 of file oDrive.cpp.
References node_ID.
Member Function Documentation
clear_battery_voltage()
void oDrive::clear_battery_voltage () private
the function that is called when something has gone wrong, and no message is received when Get_Bus_Voltage_Current is called
Definition at line 149 of file oDrive.cpp.
References battery_voltage, battery_voltage_mutex, battery_voltage_string, and main_menu_values_mutex.
Referenced by receive_message(), and send_message().
receive_message()
void oDrive::receive_message (uint8_t message_ID) private
the function that handles when a message needs to be received from the Odrive
Parameters
message_ID : the id of the message that is going to be recived
Definition at line 73 of file oDrive.cpp.
References clear_battery_voltage(), Get_Bus_Voltage_Current, Get_Encoder_Estimates, Get_Error, Get_Iq, Get_Powers, Get_Temperature, Get_Torques, Get_Version, node_ID, node_id_offset, update_battery_voltage(), and update_current_motor_velocity().
Referenced by send_message().
send_message()
void oDrive::send_message (const uint8_t message_ID, const uint8_t * message_contents, uint8_t message_length, const bool data_returned)
send a command to the Odrive
Parameters
message_ID : const uint8_t the ID of the message to be sent
message_contents : const uint8_t* the data to be sent with the message
message_length : uint8_t the length of the data
data_returned : const bool if data is returned (determines if receive_message is called or not)
Definition at line 19 of file oDrive.cpp.
References clear_battery_voltage(), Get_Bus_Voltage_Current, lower_five_bits, max_message_size, node_ID, node_id_offset, and receive_message().
update_battery_voltage()
void oDrive::update_battery_voltage (twai_message_t rx_message) private
the function that is called to update the display's battery voltage
Parameters
rx_message : twai_message_t the message that has been received containing the id of Get_Bus_Voltage_Current
Definition at line 120 of file oDrive.cpp.
References battery_voltage, battery_voltage_mutex, battery_voltage_string, bytes_in_float, main_menu_values_mutex, values_0, values_1, values_2, and values_3.
Referenced by receive_message().
update_current_motor_velocity()
void oDrive::update_current_motor_velocity (twai_message_t rx_message) private
Read the motor velocity from an odrive.
Parameters
rx_message : twai_message_t the message that has been received containing the id of Get_Encoder_Estimates
This function will read the velocity of the motor from the odrive and update the velocity estimate
Definition at line 165 of file oDrive.cpp.
References bytes_in_float, left_drive_velocity_estimate, left_drive_velocity_estimate_mutex, node_ID, oDrive_0_ID, oDrive_1_ID, right_drive_velocity_estimate, right_drive_velocity_estimate_mutex, values_0, values_1, values_2, values_3, values_4, values_5, values_6, and values_7.
Referenced by receive_message().
Member Data Documentation
node_ID
uint8_t oDrive::node_ID private
node id as set in the Odrive configurator
Definition at line 37 of file oDrive.h.
Referenced by oDrive(), receive_message(), send_message(), and update_current_motor_velocity().
The documentation for this class was generated from the following files:
include/drivers/oDrive.h
main/drivers/oDrive.cpp