Kicker Mainbaord: led_strip_driver Class Reference
led_strip_driver Class Reference
This is a class to control ws2812b led strips.
#include <led_strip_driver.h>
Public Member Functions
led_strip_driver (uint8_t strip_gpio_pin, uint8_t number_of_leds_in_strip)
Constructor for the led_strip_driver class.
void set_color (uint8_t r, uint8_t g, uint8_t b, uint8_t led_start, uint8_t led_end)
set the color for a set of leds in the strip
Private Attributes
led_strip_rmt_config_t rmt_config
rmt setup (Remote Control Transceiver)
led_strip_config_t led_strip_config
the config for the led strip
led_strip_handle_t led_strip
the handle for the led strip
Detailed Description
This is a class to control ws2812b led strips.
Definition at line 19 of file led_strip_driver.h.
Constructor & Destructor Documentation
led_strip_driver()
led_strip_driver::led_strip_driver (uint8_t strip_gpio_pin, uint8_t number_of_leds_in_strip)
Constructor for the led_strip_driver class.
Parameters
strip_gpio_pin : uint8_t, the GPIO pin where the led strip is connected
number_of_leds_in_strip : uint8_t the number of leds in the strip, max addressable is n-1, 16 leds can address 0-15
Definition at line 11 of file led_strip_driver.cpp.
References led_strip, led_strip_config, rmt_config, and set_color().
Member Function Documentation
set_color()
void led_strip_driver::set_color (uint8_t r, uint8_t g, uint8_t b, uint8_t led_start, uint8_t led_end)
set the color for a set of leds in the strip
Parameters
r : uint8_t set the red value for the range of leds
g : uint8_t set the green value for the range of leds
b : uint8_t set the blue value for the range of leds
led_start : uint8_t the index of the led to start this color change (starts at 0)
led_end : uint8_t the index of the led to stop this color change (max value of number_of_leds_in_strip-1)
Definition at line 26 of file led_strip_driver.cpp.
References led_strip.
Referenced by led_setup(), and led_strip_driver().
Member Data Documentation
led_strip
led_strip_handle_t led_strip_driver::led_strip private
the handle for the led strip
Definition at line 30 of file led_strip_driver.h.
Referenced by led_strip_driver(), and set_color().
led_strip_config
led_strip_config_t led_strip_driver::led_strip_config private
the config for the led strip
Definition at line 29 of file led_strip_driver.h.
Referenced by led_strip_driver().
rmt_config
led_strip_rmt_config_t led_strip_driver::rmt_config private
Initial value:
= {
        .clk_src = RMT_CLK_SRC_DEFAULT,
        .resolution_hz = rmt_counter_clock_frequency,
        .mem_block_symbols = rmt_channel_memory_size,
        .flags = {
            .with_dma = false,
        }}
rmt setup (Remote Control Transceiver)
Definition at line 21 of file led_strip_driver.h.
Referenced by led_strip_driver().
The documentation for this class was generated from the following files:
include/drivers/led_strip_driver.h
main/drivers/led_strip_driver.cpp