Kicker Mainbaord: kicker_drive_train Class Reference
kicker_drive_train Class Reference
This class is for controlling the kicker drive train (2 odrives)
#include <kicker_drive_train.h>
Public Member Functions
kicker_drive_train (oDrive *left_drive, oDrive *right_drive, uint32_t battery_voltage_refresh)
constructor for the kicker_drive_train class
void update ()
The main loop for the drive train, updates values, checks battery, and drives motors.
Private Member Functions
void periodic_voltage_reading ()
update the battery voltage if the correct amount of time has passed
void ramped_settings_updater ()
update the ramped velocity parameters if they have been changed
void drive_motors (bool boosted)
drive the motors based on set parameters and last joystick values
void calibrating ()
run the calibration sequence with periodic messages over can bus to prevent the odrives from entering watchdog timeout
void clear_errors ()
clear the errors on the odrives
void disable_motors ()
set the motors to their idle state
void enable_motors ()
set the motors to their active state
void motor_status_updater ()
change the status of the motors
void motor_speed_multiplier_updater ()
modify the speed multipliers
void motor_speeds_updater ()
update the speeds of the motors based on the joysticks
void estop ()
send estop to the odrives
void break_motors ()
brake the motors by setting the velocity to 0
Private Attributes
oDrive * left_drive
pointer to an instance of the odrive class for the left motor
oDrive * right_drive
pointer to an instance of the odrive class for the right motor
int64_t last_time
last time that the battery voltage was updated
int32_t battery_update_time
how often the battery voltage is updated
uint8_t last_motor_state
the last motor state
uint8_t last_driving_speed
the last left joystick reading
uint8_t last_turning_speed
the last right joystick reading
uint8_t last_driving_speed_mult
the last left motor speed multiplier
uint8_t last_turning_speed_mult
the last right motor speed multiplier
uint8_t CLOSED_LOOP_CONTROL = 0x8
options for Set_Axis_State
uint8_t NO_DATA = 0x0
empty byte if no data is needed to be sent
uint8_t IDLE_STATE = 0x1
data to set the motor to the idle state
uint8_t FULL_CALIBRATION_SEQUENCE = 0x3
data to run the calibration sequence
Detailed Description
This class is for controlling the kicker drive train (2 odrives)
Controls two odrives in a tank drive configuration
Definition at line 78 of file kicker_drive_train.h.
Constructor & Destructor Documentation
kicker_drive_train()
kicker_drive_train::kicker_drive_train (oDrive * left_drive, oDrive * right_drive, uint32_t battery_voltage_refresh)
constructor for the kicker_drive_train class
Parameters
left_drive : oDrive* a pointer to the left odrive class instance
right_drive : oDrive* a pointer to the right odrive class instance
battery_voltage_refresh : uint32_t the amount of time to wait to update the battery voltage (in micro seconds)
Definition at line 11 of file kicker_drive_train.cpp.
References battery_update_time, DISABLED, last_driving_speed, last_driving_speed_mult, last_motor_state, last_time, last_turning_speed, last_turning_speed_mult, left_drive, and right_drive.
Member Function Documentation
break_motors()
void kicker_drive_train::break_motors () private
brake the motors by setting the velocity to 0
Definition at line 290 of file kicker_drive_train.cpp.
References brake_turn_off_velocity, brake_velocity_ramp, disable_motors(), eight_bytes, full_message_middle_index, full_message_size, Get_Encoder_Estimates, left_drive, left_drive_velocity_estimate, left_drive_velocity_estimate_mutex, max_braking_time, odrive_write_rx, ramped_values_updated, ramped_values_updated_bool, right_drive, right_drive_velocity_estimate, right_drive_velocity_estimate_mutex, RxSdo, Set_Input_Vel, timeout_clock, vel_ramp_rate_id, and zero_bytes.
Referenced by motor_status_updater(), and update().
calibrating()
void kicker_drive_train::calibrating () private
run the calibration sequence with periodic messages over can bus to prevent the odrives from entering watchdog timeout
Definition at line 135 of file kicker_drive_train.cpp.
References calibration_time, FULL_CALIBRATION_SEQUENCE, Get_Error, left_drive, one_byte, right_drive, Set_Axis_State, timeout_clock, and zero_bytes.
Referenced by motor_status_updater().
clear_errors()
void kicker_drive_train::clear_errors () private
clear the errors on the odrives
Definition at line 152 of file kicker_drive_train.cpp.
References Clear_Errors, left_drive, NO_DATA, one_byte, and right_drive.
Referenced by motor_status_updater().
disable_motors()
void kicker_drive_train::disable_motors () private
set the motors to their idle state
Definition at line 159 of file kicker_drive_train.cpp.
References IDLE_STATE, left_drive, one_byte, right_drive, and Set_Axis_State.
Referenced by break_motors(), and motor_status_updater().
drive_motors()
void kicker_drive_train::drive_motors (bool boosted) private
drive the motors based on set parameters and last joystick values
Definition at line 234 of file kicker_drive_train.cpp.
References boost_amount, eight_bit_maximum, eight_bit_minimum, eight_bytes, full_message_middle_index, full_message_size, full_message_start_index, input_velocity_deadzone, last_driving_speed, last_driving_speed_mult, last_turning_speed, last_turning_speed_mult, left_drive, map, motor_drive_speed_multiplier_value, motor_turn_speed_multiplier_value, odrive_motor_torque, right_drive, and Set_Input_Vel.
Referenced by update().
enable_motors()
void kicker_drive_train::enable_motors () private
set the motors to their active state
Definition at line 166 of file kicker_drive_train.cpp.
References CLOSED_LOOP_CONTROL, left_drive, one_byte, right_drive, and Set_Axis_State.
Referenced by motor_status_updater().
estop()
void kicker_drive_train::estop () private
send estop to the odrives
Definition at line 283 of file kicker_drive_train.cpp.
References Estop, left_drive, NO_DATA, and right_drive.
motor_speed_multiplier_updater()
void kicker_drive_train::motor_speed_multiplier_updater () private
modify the speed multipliers
Definition at line 173 of file kicker_drive_train.cpp.
References driving_speed_mult, last_driving_speed_mult, last_turning_speed_mult, motor_speeds_settings_mutex, and turning_speed_mult.
Referenced by update().
motor_speeds_updater()
void kicker_drive_train::motor_speeds_updater () private
update the speeds of the motors based on the joysticks
Definition at line 184 of file kicker_drive_train.cpp.
References driving_speed, last_driving_speed, last_turning_speed, motor_speeds, and turning_speed.
Referenced by update().
motor_status_updater()
void kicker_drive_train::motor_status_updater () private
change the status of the motors
Definition at line 76 of file kicker_drive_train.cpp.
References break_motors(), CALIBRATING, calibrating(), clear_errors(), disable_motors(), DISABLED, enable_motors(), ENABLED, ERRORLESS, last_motor_state, motor_status, and motor_status_mutex.
Referenced by update().
periodic_voltage_reading()
void kicker_drive_train::periodic_voltage_reading () private
update the battery voltage if the correct amount of time has passed
Definition at line 65 of file kicker_drive_train.cpp.
References battery_update_time, Get_Bus_Voltage_Current, last_time, and left_drive.
Referenced by update().
ramped_settings_updater()
void kicker_drive_train::ramped_settings_updater () private
update the ramped velocity parameters if they have been changed
Definition at line 195 of file kicker_drive_train.cpp.
References eight_bytes, full_message_middle_index, left_drive, odrive_write_rx, ramped_mutex, ramped_values_updated, ramped_values_updated_bool, right_drive, RxSdo, Set_Vel_Gains, vel_ramp_rate_id, velocity_gain, velocity_integrator_gain, and velocity_ramp_limit.
Referenced by update().
update()
void kicker_drive_train::update ()
The main loop for the drive train, updates values, checks battery, and drives motors.
Definition at line 28 of file kicker_drive_train.cpp.
References BOOSTED, break_motors(), CONNECTED, controller_connected, controller_connected_mutex, drive_motors(), motor_speed_multiplier_updater(), motor_speeds_updater(), motor_status, motor_status_mutex, motor_status_updater(), periodic_voltage_reading(), and ramped_settings_updater().
Referenced by kicker_drive_train_task().
Member Data Documentation
battery_update_time
int32_t kicker_drive_train::battery_update_time private
how often the battery voltage is updated
Definition at line 84 of file kicker_drive_train.h.
Referenced by kicker_drive_train(), and periodic_voltage_reading().
CLOSED_LOOP_CONTROL
uint8_t kicker_drive_train::CLOSED_LOOP_CONTROL = 0x8 private
options for Set_Axis_State
Data to set Odrive to closed loop control
Definition at line 156 of file kicker_drive_train.h.
Referenced by enable_motors().
FULL_CALIBRATION_SEQUENCE
uint8_t kicker_drive_train::FULL_CALIBRATION_SEQUENCE = 0x3 private
data to run the calibration sequence
Definition at line 159 of file kicker_drive_train.h.
Referenced by calibrating().
IDLE_STATE
uint8_t kicker_drive_train::IDLE_STATE = 0x1 private
data to set the motor to the idle state
Definition at line 158 of file kicker_drive_train.h.
Referenced by disable_motors().
last_driving_speed
uint8_t kicker_drive_train::last_driving_speed private
the last left joystick reading
Definition at line 89 of file kicker_drive_train.h.
Referenced by drive_motors(), kicker_drive_train(), and motor_speeds_updater().
last_driving_speed_mult
uint8_t kicker_drive_train::last_driving_speed_mult private
the last left motor speed multiplier
Definition at line 92 of file kicker_drive_train.h.
Referenced by drive_motors(), kicker_drive_train(), and motor_speed_multiplier_updater().
last_motor_state
uint8_t kicker_drive_train::last_motor_state private
the last motor state
Definition at line 86 of file kicker_drive_train.h.
Referenced by kicker_drive_train(), and motor_status_updater().
last_time
int64_t kicker_drive_train::last_time private
last time that the battery voltage was updated
Definition at line 83 of file kicker_drive_train.h.
Referenced by kicker_drive_train(), and periodic_voltage_reading().
last_turning_speed
uint8_t kicker_drive_train::last_turning_speed private
the last right joystick reading
Definition at line 90 of file kicker_drive_train.h.
Referenced by drive_motors(), kicker_drive_train(), and motor_speeds_updater().
last_turning_speed_mult
uint8_t kicker_drive_train::last_turning_speed_mult private
the last right motor speed multiplier
Definition at line 93 of file kicker_drive_train.h.
Referenced by drive_motors(), kicker_drive_train(), and motor_speed_multiplier_updater().
left_drive
oDrive* kicker_drive_train::left_drive private
pointer to an instance of the odrive class for the left motor
Definition at line 80 of file kicker_drive_train.h.
Referenced by break_motors(), calibrating(), clear_errors(), disable_motors(), drive_motors(), enable_motors(), estop(), kicker_drive_train(), periodic_voltage_reading(), and ramped_settings_updater().
NO_DATA
uint8_t kicker_drive_train::NO_DATA = 0x0 private
empty byte if no data is needed to be sent
Definition at line 157 of file kicker_drive_train.h.
Referenced by clear_errors(), and estop().
right_drive
oDrive* kicker_drive_train::right_drive private
pointer to an instance of the odrive class for the right motor
Definition at line 81 of file kicker_drive_train.h.
Referenced by break_motors(), calibrating(), clear_errors(), disable_motors(), drive_motors(), enable_motors(), estop(), kicker_drive_train(), and ramped_settings_updater().
The documentation for this class was generated from the following files:
include/supporting/kicker_drive_train.h
main/supporting/kicker_drive_train.cpp