Kicker Mainbaord: ssd1306 Class Reference
ssd1306 Class Reference
This is a class to drive an ssd1306 over i2c.
#include <ssd1306.h>
Public Member Functions
ssd1306 (i2c_master_dev_handle_t ssd1306_handle)
Constructor for the SSD1306 class.
void write_string_SSD1306 (std::string word, uint8_t x_pos, uint8_t y_pos)
Writes a string to the display.
void clear_buffer ()
Clears the display buffer.
void write_buffer_SSD1306 ()
Writes the buffer to the display.
Private Member Functions
void send_command_SSD1306 (uint8_t command)
Sends a command to the SSD1306.
void send_data_SSD1306 (uint8_t *data, size_t len)
Sends data to the SSD1306.
void init_SSD1306 ()
Initializes the SSD1306.
void clear_SSD1306 ()
void draw_pixel_SSD1306 (uint8_t x, uint8_t y)
Draws a pixel on the display buffer.
void write_letter_SSD1306 (uint8_t letter, uint8_t x_pos, uint8_t y_pos)
Writes a letter to the display buffer.
Private Attributes
font font_instance
instance of the font class
uint8_t buffer [SSD1306_BUFFER_SIZE_128x32] = {0}
SSD1306 display buffer.
i2c_master_dev_handle_t ssd1306_handle
I2C handle for the SSD1306.
Detailed Description
This is a class to drive an ssd1306 over i2c.
Definition at line 54 of file ssd1306.h.
Constructor & Destructor Documentation
ssd1306()
ssd1306::ssd1306 (i2c_master_dev_handle_t ssd1306_handle)
Constructor for the SSD1306 class.
Parameters
ssd1306_handle : i2c_master_dev_handle_t The handle for the SSD1306
Definition at line 139 of file ssd1306.cpp.
References clear_buffer(), clear_SSD1306(), init_SSD1306(), and ssd1306_handle.
Member Function Documentation
clear_buffer()
void ssd1306::clear_buffer ()
Clears the display buffer.
Definition at line 152 of file ssd1306.cpp.
References buffer, and SSD1306_BUFFER_SIZE_128x32.
Referenced by display_driver_task(), and ssd1306().
clear_SSD1306()
void ssd1306::clear_SSD1306 () private
Clears the display display
Definition at line 56 of file ssd1306.cpp.
References send_command_SSD1306(), send_data_SSD1306(), SSD1306_horizontal_resolution, SSD1306_LOWER_COLUMN_START, SSD1306_page_count, SSD1306_PAGE_OFFSET, and SSD1306_UPPER_COLUMN_START.
Referenced by ssd1306().
draw_pixel_SSD1306()
void ssd1306::draw_pixel_SSD1306 (uint8_t x, uint8_t y) private
Draws a pixel on the display buffer.
Parameters
x : uint8_t The x coordinate of the pixel
y : uint8_t The y coordinate of the pixel
Definition at line 75 of file ssd1306.cpp.
References buffer, SSD1306_horizontal_resolution, SSD1306_page_height, and SSD1306_vertical_resolution.
Referenced by write_letter_SSD1306().
init_SSD1306()
void ssd1306::init_SSD1306 () private
Initializes the SSD1306.
Definition at line 29 of file ssd1306.cpp.
References send_command_SSD1306(), SSD1306_CHARGE_PUMP_ON, SSD1306_COM_PINS_128x32, SSD1306_CONTRAST_DEFAULT, SSD1306_DISPLAY_OFF, SSD1306_DISPLAY_OFFSET, SSD1306_DISPLAY_ON, SSD1306_ENABLE_CHARGE_PUMP, SSD1306_ENTIRE_DISPLAY_ON, SSD1306_MEMORY_HORIZONTAL, SSD1306_MUX_128x32, SSD1306_OSC_FREQ_DEFAULT, SSD1306_SET_COM_PINS, SSD1306_SET_COM_SCAN_DIR, SSD1306_SET_CONTRAST, SSD1306_SET_DISPLAY_OFFSET, SSD1306_SET_MEMORY_MODE, SSD1306_SET_MUX_RATIO, SSD1306_SET_NORMAL_DISPLAY, SSD1306_SET_OSC_FREQ, SSD1306_SET_SEGMENT_REMAP, and SSD1306_SET_START_LINE.
Referenced by ssd1306().
send_command_SSD1306()
void ssd1306::send_command_SSD1306 (uint8_t command) private
Sends a command to the SSD1306.
Parameters
command : uint8_t The command to send
Definition at line 10 of file ssd1306.cpp.
References SSD1306_COMMAND_PREFIX, SSD1306_COMMAND_SIZE, ssd1306_handle, and SSD1306_I2C_TIMEOUT.
Referenced by clear_SSD1306(), init_SSD1306(), and write_buffer_SSD1306().
send_data_SSD1306()
void ssd1306::send_data_SSD1306 (uint8_t * data, size_t len) private
Sends data to the SSD1306.
Parameters
data : uint8_t* The data to send
len : size_t The length of the data
Definition at line 18 of file ssd1306.cpp.
References SSD1306_DATA_PREFIX, ssd1306_handle, and SSD1306_I2C_TIMEOUT.
Referenced by clear_SSD1306(), and write_buffer_SSD1306().
write_buffer_SSD1306()
void ssd1306::write_buffer_SSD1306 ()
Writes the buffer to the display.
Definition at line 92 of file ssd1306.cpp.
References buffer, send_command_SSD1306(), send_data_SSD1306(), SSD1306_horizontal_resolution, SSD1306_LOWER_COLUMN_START, SSD1306_page_count, SSD1306_PAGE_OFFSET, and SSD1306_UPPER_COLUMN_START.
Referenced by display_driver_task().
write_letter_SSD1306()
void ssd1306::write_letter_SSD1306 (uint8_t letter, uint8_t x_pos, uint8_t y_pos) private
Writes a letter to the display buffer.
Parameters
letter : uint8_t The letter to write
x_pos : uint8_t The x position to write the letter
y_pos : uint8_t The y position to write the letter
Definition at line 106 of file ssd1306.cpp.
References draw_pixel_SSD1306(), font_height, font_instance, and font_width.
Referenced by write_string_SSD1306().
write_string_SSD1306()
void ssd1306::write_string_SSD1306 (std::string word, uint8_t x_pos, uint8_t y_pos)
Writes a string to the display.
Parameters
word : std::string The string to write
x_pos : uint8_t The x position to write the string
y_pos : uint8_t The y position to write the string
Definition at line 128 of file ssd1306.cpp.
References font_width, and write_letter_SSD1306().
Member Data Documentation
buffer
uint8_t ssd1306::buffer[SSD1306_BUFFER_SIZE_128x32] = {0} private
SSD1306 display buffer.
Definition at line 57 of file ssd1306.h.
Referenced by clear_buffer(), draw_pixel_SSD1306(), and write_buffer_SSD1306().
font_instance
font ssd1306::font_instance private
instance of the font class
Definition at line 56 of file ssd1306.h.
Referenced by write_letter_SSD1306().
ssd1306_handle
i2c_master_dev_handle_t ssd1306::ssd1306_handle private
I2C handle for the SSD1306.
Definition at line 105 of file ssd1306.h.
Referenced by send_command_SSD1306(), send_data_SSD1306(), and ssd1306().
The documentation for this class was generated from the following files:
include/drivers/ssd1306.h
main/drivers/ssd1306.cpp