Kicker Mainbaord: menu< T > Class Template Reference
menu< T > Class Template Reference
This class is for creating menus.
#include <menus.h>
Public Member Functions
menu (uint8_t lines, bool *have_values, std::string *words, T **values, ssd1306 *display, bool *selectable_values)
This is the constructor for the menu class.
void change_selected (int8_t direction)
This function changes what value is selected in the menu (if modifiable)
void draw_to_display ()
This function draws the menu to the display.
void increase_selected_value ()
This function increases the selected value in the menu (if modifiable)
void decrease_selected_value ()
This function decreases the selected value in the menu (if modifiable)
void draw_to_display ()
void draw_to_display ()
void draw_to_display ()
void draw_to_display ()
void increase_selected_value ()
void decrease_selected_value ()
void increase_selected_value ()
void decrease_selected_value ()
Private Attributes
uint8_t lines
The amount of lines for this menu (max 4 for 128x64 display, or 2 for 128x32 display)
std::string words [current_max_line_count]
The (constant) words that are displayed on the menu.
bool have_values [current_max_line_count]
If the words have an associated value to be displayed.
T ** values [current_max_line_count]
The values that are displayed on the menu.
ssd1306 * display
The display that the menu is displayed on.
int8_t currently_selected
The currently selected value (shown as an X on the display)
const uint8_t font_rows [max_line_count] = {vertical_font_row_0, vertical_font_row_1, vertical_font_row_2, vertical_font_row_3}
The rows that the text is displayed on 0-63 split evenly.
bool has_selectable_values = false
If the menu has selectable values.
bool selectable_values [current_max_line_count]
If the values can be modified.
Detailed Description
template<typename T>
class menu< T >
This class is for creating menus.
This class is for creating menus that can be displayed on the ssd1306 display, multiple lines are supported, and multiple data types if int or float with 2 decimal places are not what is needed, then consider using the string version of this class
Template Parameters
T The type of the values that can be modified in the menu
Definition at line 33 of file menus.h.
Constructor & Destructor Documentation
menu()
template<typename T> menu< T >::menu (uint8_t lines, bool * have_values, std::string * words, T ** values, ssd1306 * display, bool * selectable_values)
This is the constructor for the menu class.
Parameters
lines The amount of lines for the menu
have_values If the lines have values
words The words that are displayed on the menu
values The values that are displayed on the menu
display The display that the menu is displayed on
selectable_values If the values can be selected
Definition at line 12 of file menus.cpp.
References currently_selected, display, has_selectable_values, have_values, lines, max_line_count, selectable_values, values, and words.
Referenced by decrease_selected_value(), draw_to_display(), and increase_selected_value().
Member Function Documentation
change_selected()
template<typename T> void menu< T >::change_selected (int8_t direction)
This function changes what value is selected in the menu (if modifiable)
Parameters
direction The direction to move the selection
Definition at line 170 of file menus.cpp.
References currently_selected, display, font_rows, has_selectable_values, lines, and selectable_values.
Referenced by draw_to_display().
decrease_selected_value() [1/3]
template<typename T> void menu< T >::decrease_selected_value ()
This function decreases the selected value in the menu (if modifiable)
Referenced by decrease_selected_value().
decrease_selected_value() [2/3]
void menu< changeable_values< float > >::decrease_selected_value ()
Definition at line 208 of file menus.cpp.
References currently_selected, decrease_selected_value(), menu(), and values.
decrease_selected_value() [3/3]
void menu< changeable_values< uint8_t > >::decrease_selected_value ()
Definition at line 224 of file menus.cpp.
References currently_selected, decrease_selected_value(), menu(), selectable_values, and values.
draw_to_display() [1/5]
template<typename T> void menu< T >::draw_to_display ()
This function draws the menu to the display.
Referenced by display_driver_task(), and draw_to_display().
draw_to_display() [2/5]
void menu< changeable_values< float > >::draw_to_display ()
Definition at line 57 of file menus.cpp.
References change_selected(), display, divide_by_two, draw_to_display(), float_display_length, font_rows, font_width, have_values, lines, menu(), SSD1306_horizontal_resolution, values, and words.
draw_to_display() [3/5]
void menu< changeable_values< uint8_t > >::draw_to_display ()
Definition at line 87 of file menus.cpp.
References change_selected(), display, divide_by_two, draw_to_display(), font_rows, font_width, have_values, lines, menu(), SSD1306_horizontal_resolution, values, and words.
draw_to_display() [4/5]
void menu< uint8_t >::draw_to_display ()
Definition at line 115 of file menus.cpp.
References change_selected(), display, divide_by_two, font_rows, font_width, have_values, lines, SSD1306_horizontal_resolution, values, and words.
draw_to_display() [5/5]
void menu< std::string >::draw_to_display ()
Definition at line 143 of file menus.cpp.
References change_selected(), display, divide_by_two, font_rows, font_width, have_values, lines, SSD1306_horizontal_resolution, values, and words.
increase_selected_value() [1/3]
template<typename T> void menu< T >::increase_selected_value ()
This function increases the selected value in the menu (if modifiable)
Referenced by increase_selected_value().
increase_selected_value() [2/3]
void menu< changeable_values< float > >::increase_selected_value ()
Definition at line 199 of file menus.cpp.
References currently_selected, increase_selected_value(), menu(), selectable_values, and values.
increase_selected_value() [3/3]
void menu< changeable_values< uint8_t > >::increase_selected_value ()
Definition at line 215 of file menus.cpp.
References currently_selected, increase_selected_value(), menu(), selectable_values, and values.
Member Data Documentation
currently_selected
template<typename T> int8_t menu< T >::currently_selected private
The currently selected value (shown as an X on the display)
Definition at line 40 of file menus.h.
Referenced by change_selected(), decrease_selected_value(), increase_selected_value(), and menu().
display
template<typename T> ssd1306* menu< T >::display private
The display that the menu is displayed on.
Definition at line 39 of file menus.h.
Referenced by change_selected(), draw_to_display(), and menu().
font_rows
template<typename T> const uint8_t menu< T >::font_rows[max_line_count] = {vertical_font_row_0, vertical_font_row_1, vertical_font_row_2, vertical_font_row_3} private
The rows that the text is displayed on 0-63 split evenly.
Definition at line 41 of file menus.h.
Referenced by change_selected(), and draw_to_display().
has_selectable_values
template<typename T> bool menu< T >::has_selectable_values = false private
If the menu has selectable values.
Definition at line 42 of file menus.h.
Referenced by change_selected(), and menu().
have_values
template<typename T> bool menu< T >::have_values[current_max_line_count] private
If the words have an associated value to be displayed.
Definition at line 37 of file menus.h.
Referenced by draw_to_display(), and menu().
lines
template<typename T> uint8_t menu< T >::lines private
The amount of lines for this menu (max 4 for 128x64 display, or 2 for 128x32 display)
Definition at line 35 of file menus.h.
Referenced by change_selected(), draw_to_display(), and menu().
selectable_values
template<typename T> bool menu< T >::selectable_values[current_max_line_count] private
If the values can be modified.
Definition at line 43 of file menus.h.
Referenced by change_selected(), decrease_selected_value(), increase_selected_value(), and menu().
values
template<typename T> T** menu< T >::values[current_max_line_count] private
The values that are displayed on the menu.
Definition at line 38 of file menus.h.
Referenced by decrease_selected_value(), draw_to_display(), increase_selected_value(), and menu().
words
template<typename T> std::string menu< T >::words[current_max_line_count] private
The (constant) words that are displayed on the menu.
Definition at line 36 of file menus.h.
Referenced by draw_to_display(), and menu().
The documentation for this class was generated from the following files:
include/supporting/menus.h
main/supporting/menus.cpp