Kicker Mainbaord: include/tasks/display_driver_task.h File Reference
display_driver_task.h File Reference
Contains the externs and defines for the display driver task.
#include "../all_includes.h"
#include "../pinout.h"
#include "../drivers/ssd1306.h"
#include "../supporting/menus.h"
Macros
#define float_display_length 4
the number of points in a float XX.XX
#define minimum_battery_voltage 0
the minimum battery voltage to display
#define maximum_battery_voltage 30
the maximum battery voltage to display
#define display_driver_wait_time 1000
The amount of time to wait between display updates (in ms)
Functions
void display_driver_task (void *pv)
The display driver task.
Variables
i2c_master_bus_handle_t bus_handle
bus_handle : i2c_master_bus_handle_t i2c bus handle
SemaphoreHandle_t main_menu_values_mutex
mutex protecting the main menu values
std::string controller_connected_string
controller_connected_string : string, guarded by main_menu_values_mutex
SemaphoreHandle_t battery_voltage_mutex
mutex protecting battery_voltage
std::string battery_voltage_string
battery_voltage_string : string, guarded by main_menu_values_mutex
float battery_voltage
battery_voltage : float, guarded by battery_voltage_mutex
Detailed Description
Contains the externs and defines for the display driver task.
Author
Shane Wood
Definition in file display_driver_task.h.
Macro Definition Documentation
display_driver_wait_time
#define display_driver_wait_time 1000
The amount of time to wait between display updates (in ms)
Definition at line 26 of file display_driver_task.h.
Referenced by display_driver_task().
float_display_length
#define float_display_length 4
the number of points in a float XX.XX
Definition at line 23 of file display_driver_task.h.
maximum_battery_voltage
#define maximum_battery_voltage 30
the maximum battery voltage to display
Definition at line 25 of file display_driver_task.h.
Referenced by display_driver_task().
minimum_battery_voltage
#define minimum_battery_voltage 0
the minimum battery voltage to display
Definition at line 24 of file display_driver_task.h.
Referenced by display_driver_task().
Function Documentation
display_driver_task()
void display_driver_task (void * pv)
The display driver task.
This task is responsible for updating the display with the current values, in this case
Definition at line 11 of file display_driver_task.cpp.
References battery_voltage, battery_voltage_mutex, battery_voltage_string, bus_handle, ssd1306::clear_buffer(), controller_connected_string, display_driver_wait_time, menu< T >::draw_to_display(), float_display_length, i2c_frequency, main_menu_values_mutex, maximum_battery_voltage, minimum_battery_voltage, SSD1306_address, values_2, and ssd1306::write_buffer_SSD1306().
Referenced by app_main().
Variable Documentation
battery_voltage
float battery_voltage extern
battery_voltage : float, guarded by battery_voltage_mutex
Definition at line 53 of file main.cpp.
battery_voltage_mutex
SemaphoreHandle_t battery_voltage_mutex extern
mutex protecting battery_voltage
Definition at line 52 of file main.cpp.
battery_voltage_string
std::string battery_voltage_string extern
battery_voltage_string : string, guarded by main_menu_values_mutex
Definition at line 88 of file main.cpp.
bus_handle
i2c_master_bus_handle_t bus_handle extern
bus_handle : i2c_master_bus_handle_t i2c bus handle
Definition at line 108 of file main.cpp.
controller_connected_string
std::string controller_connected_string extern
controller_connected_string : string, guarded by main_menu_values_mutex
Definition at line 87 of file main.cpp.
main_menu_values_mutex
SemaphoreHandle_t main_menu_values_mutex extern
mutex protecting the main menu values
Definition at line 86 of file main.cpp.