Kicker Mainbaord: main/tasks/display_driver_task.cpp File Reference
display_driver_task.cpp File Reference
source file for the task that drives the display, displays controller connected status, and battery voltage
#include "../../include/tasks/display_driver_task.h"
Functions
void display_driver_task (void *pv)
The display driver task.
Detailed Description
source file for the task that drives the display, displays controller connected status, and battery voltage
Author
Shane Wood
Date
15/02/2025
Definition in file display_driver_task.cpp.
Function Documentation
display_driver_task()
void display_driver_task (void * pv)
The display driver task.
This task is responsible for updating the display with the current values, in this case
Definition at line 11 of file display_driver_task.cpp.
References battery_voltage, battery_voltage_mutex, battery_voltage_string, bus_handle, ssd1306::clear_buffer(), controller_connected_string, display_driver_wait_time, menu< T >::draw_to_display(), float_display_length, i2c_frequency, main_menu_values_mutex, maximum_battery_voltage, minimum_battery_voltage, SSD1306_address, values_2, and ssd1306::write_buffer_SSD1306().
Referenced by app_main().