Kicker Mainbaord: include/setup/esp_now_setup.h File Reference
esp_now_setup.h File Reference
Contains the code that sets up the ESP-NOW communication.
#include "../all_includes.h"
#include "../pinout.h"
#include "esp_now_callback_setup.h"
Functions
void esp_now_setup ()
Sets up the ESP-NOW communication, including setting up the callback functions.
Detailed Description
Contains the code that sets up the ESP-NOW communication.
Author
Shane Wood
Definition in file esp_now_setup.h.
Function Documentation
esp_now_setup()
void esp_now_setup ()
Sets up the ESP-NOW communication, including setting up the callback functions.
Definition at line 11 of file esp_now_setup.cpp.
References controller_mac_address, mac_address_length, on_receive(), and on_send().
Referenced by app_main().